### ISSUE TITLE
MalformedUrlException when trying to load schema with $refs

### ISSUE THREAD

**Issue by spandananitdgp** [everit-org/json-schema#100]
I am trying to load a schema json file which has $refs defined as "#/definitions/abc" where abc is defined in definitions of the main object. There are no URIs linked to these definitions. Does the current implementation support this use case? If yes, how to initiate a custom loader for such schema?

**Comment by erosb** [comment]
Hello @spandananitdgp , could you please send a minimal schema file reproducing the problem?

**Comment by spandananitdgp** [comment]
I'm not able to reproduce it in a smaller schema. Do you know why this exception would occur?
Stacktrace: 
java.io.UncheckedIOException: java.net.MalformedURLException: no protocol: string
   [testng] 	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:35)
   [testng] 	at org.everit.json.schema.loader.internal.JSONPointer.executeWith(JSONPointer.java:81)
   [testng] 	at org.everit.json.schema.loader.internal.JSONPointer.lambda$forURL$1(JSONPointer.java:133)
   [testng] 	at org.everit.json.schema.loader.internal.JSONPointer.query(JSONPointer.java:152)
   [testng] 	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:99)
   [testng] 	at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:253)
   [testng] 	at org.everit.json.schema.loader.SchemaLoader.lambda$load$0(SchemaLoader.java:290)

**Comment by erosb** [comment]
I'm afraid I can't recall this exception message. Please try to create a schema for reproducing it, otherwise I can't help you.

**Comment by spandananitdgp** [comment]
Nevermind. I declared primitive type "string" as "$ref" instead of "type".

**Comment by alfredim88** [comment]
I'm not able to load schema, getting this exception:
java.lang.IllegalArgumentException: a JSON pointer should start with '/' or '#/'

Here is the schema:
`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "StockAvailableToPromise",
  "description": "Available Stock (for Customer Orders) at INGKA units",
  "type": "object",
  "definitions": {
    "UTCdatetime": {
      "$id": "#UTCdatetime",
      "type": "number",
      "format": "date-time",
      "pattern": "^(.{20})([0-9]{3})[+-]((2[0-3]|[01][0-9])[:]([0-5][0-9]))$",
      "description": "Timestamp according to ISO 8601 including milliseconds and UTC offset as +/-hh:mm"
    },
    "OrderSource": {
      "$id": "#OrderSource",
      "type": "string",
      "maxLength": 10,
      "minLength": 1
    },
    "Decimal_11_2": {
      "$id": "#Decimal_11_2",
      "type": "number",
      "minimum": -999999999.99,
      "maximum": 999999999.99,
      "multipleOf": 0.01,
      "description": "Pattern for Decimal 11.2, max 9 digits before and max 2 digits after decimal point"
    },
    "LogicalRoutingIdentifier": {
      "$id": "#LogicalRoutingIdentifier",
      "type": "object",
      "additionalProperties": false,
      "description": "Identification used to route Information between different system instances or compartments",
      "required": [
        "SourceCode",
        "SourceType",
        "SourceLookupType"
      ],
      "properties": {
        "SourceCode": {
          "type": "string",
          "minLength": 1,
          "description": "Code for stockkeeping Business Unit, typically a CDC or Store"
        },
        "SourceType": {
          "sourceType": "string",
          "minLength": 1,
          "description": "Type for stockkeeping Business Unit, typically a CDC or Store"
        },
        "SourceLookupType": {
          "type": "string",
          "minLength": 1,
          "description": "description of the Type of Information that is used for the routing. e.g. Logistical unit in case of Business Units that are involved in the Transaction",
          "example": "LOGISTIC_UNIT"
        }
      }
    },
    "Allocation": {
      "$id": "#Allocation",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "OrderSource",
        "AllocatedQuantity"
      ],
      "properties": {
        "OrderSource": {
          "$ref": "#OrderSource",
          "description": "The order source holding the allocation(s)"
        },
        "AllocatedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Quantity allocated against stock on hand"
        }
      }
    },
    "Block": {
      "$id": "#Block",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "BlockCode",
        "BlockedQuantity"
      ],
      "properties": {
        "BlockCode": {
          "type": "string",
          "maxLength": 3,
          "minLength": 1,
          "description": "IKEA Block code"
        },
        "BlockedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Blocked quantity on Logistical Unit/Item/Supplier/Block Code level"
        }
      }
    },
    "Reservation": {
      "$id": "#Reservation",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "OrderSource",
        "ReservedQuantity",
        "ReservedAgainstGiTQuantity",
        "BackorderedQuantity"
      ],
      "properties": {
        "OrderSource": {
          "$ref": "#OrderSource",
          "description": "The order source holding the reservation(s)"
        },
        "ReservedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Quantity reserved against stock on hand"
        },
        "ReservedAgainstGiTQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Quantity reserved against GiT (Git-Goods in Transit)"
        },
        "BackorderedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Backordered quantity"
        }
      }
    },
    "Supplier": {
      "$id": "#Supplier",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "BusinessUnitCodeSupplier",
        "BusinessUnitTypeSupplier",
        "OnHandQuantity",
        "TotalBlockedSupplierQuantity"
      ],
      "properties": {
        "BusinessUnitCodeSupplier": {
          "type": "string",
          "maxLength": 5,
          "minLength": 1,
          "description": "Business unit code of the supplier of the item."
        },
        "BusinessUnitTypeSupplier": {
          "type": "string",
          "maxLength": 3,
          "minLength": 1,
          "description": "Type of the business unit of the supplier of the item. The value is always SUP"
        },
        "OnHandQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated on hand quantity on supplier level"
        },
        "TotalBlockedSupplierQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated blocked quantity on supplier level (excluding multiple blocks on stock object(s))"
        },
        "ListOfAllocations": {
          "description": "List of allocations for the item/supplier combination can be omitted if no allocations exist for the related Logistical Unit/Item/Supplier combination",
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#Allocation",
            "description": "List of allocations for specific Item/Supplier combinations within the specified Unit"
          }
        },
        "ListOfBlocks": {
          "description": "List of blocks for the item/supplier combination can be omitted if no block exist for the related Logistical Unit/Item/Supplier combination",
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#Block",
            "description": "List of blocks for specific Item/Supplier combinations within the specified Unit"
          }
        }
      }
    },
    "StockAvailableToPromiseLine": {
      "$id": "#StockAvailableToPromiseLine",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "ItemNo",
        "ItemType",
        "TotalOnHandQuantity",
        "TotalAllocatedQuantity",
        "TotalBlockedQuantity",
        "TotalReservedQuantity",
        "AvailableQuantity",
        "TotalReservedAgainstGiTQuantity",
        "TotalBackorderedQuantity",
        "UoMCode"
      ],
      "properties": {
        "ItemNo": {
          "type": "string",
          "maxLength": 15,
          "minLength": 1,
          "description": "ItemNumber, part of IKEA item identification, empty string is not accepted",
          "example": "01234567"
        },
        "ItemType": {
          "type": "string",
          "maxLength": 3,
          "minLength": 1,
          "description": "Itemtype, part of IKEA item identification, empty string is not accepted",
          "example": "ART"
        },
        "TotalOnHandQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated on hand quantity"
        },
        "TotalAllocatedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated allocated quantity"
        },
        "TotalBlockedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated blocked quantity (excluding multiple blocks on stock object(s))"
        },
        "TotalReservedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated reserved against stock on hand quantity(does NOT include backordered and reserved against GiT Quantity) (Git-Goods in Transit)"
        },
        "AvailableQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Stock available to promise quantity: AvailableQuantity = TotalOnHandQuantity - TotalAllocatedQuantity - TotalBlockedQuantity - TotalReservedQuantity  (Can be less then 0!)"
        },
        "TotalReservedAgainstGiTQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated reserved against GIT quantity (Git-Goods in Transit)"
        },
        "TotalBackorderedQuantity": {
          "$ref": "#Decimal_11_2",
          "description": "Aggregated backordered quantity"
        },
        "UoMCode": {
          "type": "string",
          "maxLength": 10,
          "minLength": 1,
          "description": "Unit of Measurement for all Quantity attributes PCS/MTR"
        },
        "ListOfReservations": {
          "type": "array",
          "minItems": 1,
          "description": "List of reservations for the item, can be omitted if there are no preservations existing",
          "items": {
            "$ref": "#Reservation",
            "description": "List of Reservations for specific Items within the specified Unit"
          }
        },
        "ListOfSuppliers": {
          "type": "array",
          "minItems": 1,
          "description": "List of supliers for the item",
          "items": {
            "type": "object",
            "$ref": "#Supplier",
            "description": "List of Suppliers including allocations and blocks for a specific ITEM within the specified Logistical Unit"
          }
        }
      }
    }
  },
  "properties": {
    "MsgHeader": {
      "type": "object",
      "required": [
        "MsgName",
        "MsgVersNo",
        "MsgDateTime",
        "LogicalRoutingIdentifier",
        "MsgReference",
        "SendingSystem"
      ],
      "properties": {
        "MsgName": {
          "type": "string",
          "maxLength": 35,
          "minLength": 1,
          "description": "Name of the message",
          "example": "SyncStockAvailableToPromiseMsg"
        },
        "MsgVersNo": {
          "type": "string",
          "maxLength": 10,
          "minLength": 1,
          "description": "Version of the message",
          "example": "1.0"
        },
        "MsgDateTime": {
          "type": "number",
          "description": "Event date and time in milliseconds and timezone UTC"
        },
        "LogicalRoutingIdentifier": {
          "$ref": "#LogicalRoutingIdentifier"
        },
        "MsgReference": {
          "type": "string",
          "maxLength": 36,
          "minLength": 1,
          "description": "GlobalUniqueReference (transaction GUID)",
          "example": " 1234567890"
        },
        "SendingSystem": {
          "type": "string",
          "maxLength": 20,
          "minLength": 1,
          "description": "Name of the system that is providing the Infromation",
          "example": "CWIS"
        }
      }
    },
    "MsgBody": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "StockAvailableToPromise"
      ],
      "properties": {
        "StockAvailableToPromise": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "BusinessUnitCode",
            "BusinessUnitType",
            "ReportDateTime",
            "StockAvailableToPromiseLineList"
          ],
          "properties": {
            "BusinessUnitCode": {
              "type": "string",
              "maxLength": 5,
              "minLength": 1,
              "description": "Code for stockkeeping Business Unit, typically a CDC or Store"
            },
            "BusinessUnitType": {
              "type": "string",
              "maxLength": 3,
              "minLength": 1,
              "description": "Type for stockkeeping Business Unit, typically a CDC or Store"
            },
            "ReportDateTime": {
              "type": "number",
              "description": "Time of transmission by source with timestamp"
            },
            "StockAvailableToPromiseLineList": {
              "type": "array",
              "minItems": 1,
              "items": {
                "$ref": "#StockAvailableToPromiseLine",
                "description": "List of ITEM/Supplier combinations in the specified Logistical Unit"
              }
            }
          }
        }
      }
    }
  }
}`

**Comment by alfredim88** [comment]
I'm using the latest version:
```
        <dependency>
            <groupId>org.everit.json</groupId>
            <artifactId>org.everit.json.schema</artifactId>
            <version>1.5.1</version>
        </dependency>
```
