### ISSUE TITLE
Run Time Error in SchemaJson.toMap()

### ISSUE THREAD

**Issue by santpandey** [everit-org/json-schema#101]
I am using 1.6.0 version of the jar. I have created a sample schema and when I run my JSON against this schema, I get the following Run Time Exception:

Exception in thread "main" java.lang.NoSuchMethodError: org.json.JSONObject.toMap()Ljava/util/Map;
	at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.schemaJson(SchemaLoader.java:160)

**Comment by erosb** [comment]
Please check if there is an other dependency in your project which uses an older version of org.json. There was a similar issue recently here: #98

**Comment by santpandey** [comment]
It worked. My issue was exactly the same as #98. Thanks

**Comment by muenchowk24** [comment]
Similar issue.
Found multiple occurrences of org.json.JSONObject on the class path:

        jar:file:/C:/Users/user/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class
        jar:file:/C:/Users/user/.m2/repository/org/json/json/20180130/json-20180130.jar!/org/json/JSONObject.class

The         jar:file:/C:/Users/user/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class comes with your Version 1.7.1? There is no toMap() method.

**Comment by zhjobs** [comment]
@santpandey How do you solve this problem?

**Comment by santpandey** [comment]
@zhjobs When I encountered the problem, I made sure that I was using `20170516 ` of org.json by manually adding it to pom. After this run `mvn dependency:tree -Dverbose` command and see whether are you getting old jars of org.json or not. If yes, you must exclude them. Let me know if this helps.

**Comment by zhjobs** [comment]
@santpandey Brilliant！It did work! Thanks for your answer!

**Comment by zhjobs** [comment]
#202
