### ISSUE TITLE
date-time format doesn't support full ISO-8601 spec

### ISSUE THREAD

**Issue by bmudda** [everit-org/json-schema#102]
Currently the date-time validation expects the `Z` variable and not the `time-numoffset`. Therefore date strings like this `2017-11-28T21:45:59-0100` are deemed invalid when it is legitimate to have that format. In contrary this format is supported (`2017-11-28T20:45:59Z`). I think either of those two formats should be validated as a valid formats as it is listed in this spec. https://tools.ietf.org/html/rfc3339#section-5.6

**Comment by erosb** [comment]
Hello @bmudda , according to the section you linked above, `-0100` is not a valid offset, while `-01:00` is valid. The colon is mandatory according to this rule of the referenced ABNF: ` time-numoffset  = ("+" / "-") time-hour ":" time-minute`

**Comment by erosb** [comment]
Closing this. Please let me know of if you have any further questions.

**Comment by bmudda** [comment]
@erosb correct, missed the semicolon. This now validates correctly.
