### ISSUE TITLE
Could not initialize class org.everit.json.schema.loader.SpecificationVersion

### ISSUE THREAD

**Issue by santpandey** [everit-org/json-schema#103]
I am unable to initialize SpecificationVersion class. It says:

java.lang.NoClassDefFoundError : Could not initialize class org.everit.json.schema.loader.SpecificationVersion.

This happens when I try to create the SchemaLoader object.
`SchemaLoader loader = SchemaLoader.builder()
                    .schemaJson(rawSchema)
                    .draftV6Support()
                    .build();`

I am unable to find the resolution for it. I am using Spring Boot application and I have 1.6.0 version of com.github.everit-org.json-schema and my or.json has 20170516 version.

Any suggestion would be very helpful

**Comment by erosb** [comment]
Hello @santpandey , I'm afraid I can't help with it without being able to reproduce it. Could you please create a minimal project for reproducing the exception so I can investigate deeper?

**Comment by santpandey** [comment]
Hi @erosb . The jitpack repository which I was using in my pom had some issue. I deleted and imported it later and the issue was resolved. I don't know what was the issues in the first place. Anyways we can close this issue. Thank you.
