### ISSUE TITLE
Unable to retrieve causing Exceptions for all the Exceptions which have occured in Sub Schema

### ISSUE THREAD

**Issue by santpandey** [everit-org/json-schema#106]
I have a schema where the exception occurred and further down the schema further exceptions also occurred. But there is no method in ValidateException class which actually collects all the Exception right from say(node to leaf) and returns list of that.

I was debugging and I got a ValidationException object through getCausingException(). But when I expand this object through debugger tool, I could see that it has further 3 ValidationException objects which have specific error message I was looking for.

So what I mean is that the structure is like a graph and we might need to do Depth First Search to retrieve all messages(which I am looking) ValidationObject.

Do we need to do DFS for this or is there an endpoint to get this(which I might have missed)

Another point I want to bring is that there is an instance variable called "detailMessage" in ValidationException object when I see through debugger tool, but ValidationException class doesn't have this "detailMessage" defined in it.(Screenshot attached)
![everit1](https://user-images.githubusercontent.com/6648862/30443221-6ace05b6-999c-11e7-8822-48fdbf076f4e.PNG)

Please do let me know if I have missed something

**Comment by erosb** [comment]
Hello @santpandey , I assume you are looking for the `ValidationException#getAllMessages()` method? It was added in #54
