### ISSUE TITLE
Not validating required property of merged array or object

### ISSUE THREAD

**Issue by vkarthikesan** [everit-org/json-schema#107]
SchemaWithMerge.txt contains the schema with merge, but it is not failing the schema validation if "name" is not passed for "entitities" but the same is working fine if merge is not used as per attached SchemaWithoutMerge.txt

**Test Schema with Merging:**

[SchemaWithMerge.txt](https://github.com/everit-org/json-schema/files/1306222/SchemaWithMerge.txt)

**Test Schema without Merging:**
[SchemaWithoutMerge.txt](https://github.com/everit-org/json-schema/files/1306230/SchemaWithoutMerge.txt)

Test Json (This should fail as "name" is not available for the item of "entities"

`
{
  "name":"test",
  "dataStoreType": "DOCUMENT",
  "entities": [
    {
      "softDelete": true,
      "attributes": [
        {
          "name": "parentMessageId",
          "type": "STRING"
        }
      ]
    }
  ]
}
`

**Comment by erosb** [comment]
Hello, `"$merge"` is not a standard keyword of json schema, and it isn't supported by this library.

`"$merge"` and `"$patch"` is [currently a proposal](https://github.com/json-schema-org/json-schema-spec/issues/15) which was early adopted by a few implementations.

**Comment by vkarthikesan** [comment]
Thanks for the reply
