### ISSUE TITLE
Line number on json file where the error has occured

### ISSUE THREAD

**Issue by Rameshkumar1990** [everit-org/json-schema#112]
Thanks for the wonderful library.

We have a requirement to validate JSON against Schema and display error message along with the line number to user. Is there any way we can get the Line number on JSON file from the "Pointer to Violation" attribute provided as part of ValidationException

**Comment by erosb** [comment]
Hello @Rameshkumar1990 , unfortunately we can't include the line number. The library takes a `JSONObject` instance as its argument, so the schema is already parsed by the `org.json` library, which doesn't hold the line numbers after parsing. You may [open an issue for them](https://github.com/stleary/JSON-java) to support your usecase.

**Comment by Rameshkumar1990** [comment]
Thanks for the quick response.
