### ISSUE TITLE
Can I ignore a field to be validated?

### ISSUE THREAD

**Issue by spandananitdgp** [everit-org/json-schema#115]
I have a case where json contains a field as string but in schema that needs to be declared as object. When I do that validation fails saying "expected type: JSONObject, found: String". Is there a way I can ignore this field during validation?

**Comment by erosb** [comment]
Can you please post your schema and input json here? Thanks

**Comment by erosb** [comment]
Closing this issue due to the lack of response - please reopen it if the question is still relevant.
