### ISSUE TITLE
Type Validation failing when a huge number (More than 19 Digits) is given in place of String

### ISSUE THREAD

**Issue by Rameshkumar1990** [everit-org/json-schema#120]
Hi Team,

I have given here a sample schema to understand the scenario. Schema has an element UserName of type String. 

**Sample Schema:**
{
  "$schema": "http://json-schema.org/schema#",
  "properties": {
    "User": {
      "type": "object",
      "properties": {
        "UserName": {
          "type": "string"
        }
      },
      "required": [
        "UserName"
      ]
    }
  }
}

**Sample Json 1:**
{
	"User": {
		"UserName": 100
	}
}

When I try to give a number for UserName as given in Sample Json 1, ValidationException is thrown with Message "expected type: String, found: Integer".

**Sample Json 2:**
{
	"User": {
		"UserName": 1234567890123456789
	}
}

When I try to give a number in range of Long for UserName as given in Sample Json 2, ValidationException is thrown with Message "expected type: String, found: Long".

**Sample Json 3:**
{
	"User": {
		"UserName": 1234567890123456789012345
	}
}

When I try to give a huge number out of range of Long for UserName as given in Sample Json 3, Validation is passing without any error. But as it is not a String value, it has to throw ValidationException.

**Comment by erosb** [comment]
Hello,

I played around with it a bit, and unfortunately I couldn't find any reliable way through the org.json library to determine if the very long number is really a json number, or a string containing the number. My attempts were:

```JSONObject obj = new JSONObject("{\"a\":123456789101112131415,\"b\":\"123456789101112131415\"}");
        System.out.println(obj.get("a").getClass());
        System.out.println(obj.getBigInteger("a").getClass());
        System.out.println(obj.getNumber("a").getClass());

        System.out.println(obj.get("b").getClass());
        System.out.println(obj.getBigInteger("b").getClass());
        System.out.println(obj.getNumber("b").getClass());
```

Output:

```class java.lang.String
class java.math.BigInteger
class java.math.BigInteger
class java.lang.String
class java.math.BigInteger
class java.math.BigInteger
```

So probably it would be necessary to look around the parsing code of org.json. I'm not sure if it can/will be fixed any time soon.

**Comment by erosb** [comment]
I investigated the related parts of org.json today evening, and it seems this cannot be fixed without breaking other uses of that library. Quite unfortunate situation. Sorry I couldn't help.
