### ISSUE TITLE
Draft 7 support

### ISSUE THREAD

**Issue by srmo** [everit-org/json-schema#125]
Ahoi,

I just stumbled upon JSON Schema (http://json-schema.org/) which mentions it has published Draft 7.
Their list of implementations doesn't list any java implementation that supports this. Do you consider adding draft-7 support?

**Comment by erosb** [comment]
Hello @srmo , probably it _will_ be supported, but no ETA for this. Saying that it will come in the upcoming few months is realistic, so don't expect it in this year. Anyway, contribution would speed it up :)

**Comment by srmo** [comment]
Hi @erosb . Thanks for the quick answer. The "contribution-factor" is well understood :)

**Comment by erosb** [comment]
@srmo I just released version [1.8.0](https://github.com/everit-org/json-schema/releases/tag/1.8.0) which brings draft 7 support.

Closing this issue.
