### ISSUE TITLE
Enum: Validating allowed null value fails

### ISSUE THREAD

**Issue by heneke** [everit-org/json-schema#126]
Consider the following enum schema:

`"enum": [null, "foo", "bar"]`

A valid null value in the JSON instance will be considered invalid, because the null is not added to the set of possible values.

**Comment by heneke** [comment]
Sorry, it is added, but validation fails nevertheless.

**Comment by heneke** [comment]
See https://github.com/everit-org/json-schema/pull/127

**Comment by erosb** [comment]
Fixed in 60cbcca1887949f5935b6989d5a579746330cc2f .
