### ISSUE TITLE
Validation of extra properties

### ISSUE THREAD

**Issue by ejgreenwald** [everit-org/json-schema#140]
Is there a way to fail validation if an extra property is found? In other words if the schema I am comparing against doesn't have a property that the json I'm comparing to has can I enforce a strict mode that would make validation fail?

Thanks!

**Comment by ejgreenwald** [comment]
My mistake - you can use "additionalProperties":false Thanks for a great framework!

**Comment by borgogelli** [comment]
I have tried it. The error message from the Validator is not friendly:
` "extraneous key [channel] is not permitted".`
It doesn't point out the name of the extraneous keys .
Any advice ?

**Comment by erosb** [comment]
The error message says that the name of the extraneous key is "channel".

**Comment by borgogelli** [comment]
Hi @erosb thank you for the reply, but no way, I have already checked it
I have opened an new [issue](https://github.com/everit-org/json-schema/issues/371)
