### ISSUE TITLE
Json-Schema do not validate if the JSONObject is well formed?

### ISSUE THREAD

**Issue by PabloThiele** [everit-org/json-schema#143]
Hi, 

I just tried your lib with a simple test:

    @Test
    public void QuickTest() throws ValidationException {
        JSONObject jsonSchema = new JSONObject(
                new JSONTokener(JsonSchemaTest.class.getResourceAsStream("/schema.json")));
        JSONObject jsonSubject = new JSONObject(
                new JSONTokener(JsonSchemaTest.class.getResourceAsStream("/product_invalid.json")));

        Schema schema = SchemaLoader.load(jsonSchema);
        schema.validate(jsonSubject);
    }

[resources.zip](https://github.com/everit-org/json-schema/files/1682995/resources.zip)

In the resource you can find the files used.

The simple question is: A not well formed JSON like the attached one will not raise an error since the schema is not offended?  (In my example there's a comma on the final of the last JSON item)

If yes, how will be best option to:
1. Receive the JSON and check the well format
2. Use your lib to check the SCHEMA

**Comment by erosb** [comment]
Hello,

this library is not responsible on its own to check the syntax, it validates structure. The parsing of the raw JSON text happens in the org.json library (namely in the `new JSONObject(...)` call).
The org.json parser is quite liberal about what does it accept, ie. it accepts trailing commas, like in your product_invalid.json.

**Comment by PabloThiele** [comment]
Thanks for the prompt response! :) Unfortunately this is odd. The another lib that uses Jackson capture that kind of problem but lacks of update to at least the 6 schema version. :( 

Thanks anyway for your great lib, I'll try to adjust my code here to support my needs. BTW,  anything related to that worth for a PR in the future (JSON format strict check)? 

Have a nice day.

**Comment by erosb** [comment]
I think a considerable option would be to generate a JSON parser from [the existing antlr grammar](https://github.com/antlr/grammars-v4/blob/master/json/JSON.g4#L69) and check if it can parse your input. I think it can be faster than eg. parsing with jackson, since the antlr parser just recognizes the  structure, but doesn't build any in-memory model of it, like a JSONObject. 

I'm not sure though how accurate the grammar file is.
