### ISSUE TITLE
exponential runtime for pattern matching with Java's builtin PCRE regex engine

### ISSUE THREAD

**Issue by rkeytacked** [everit-org/json-schema#147]
In this test case the JSON schema validation will end up eating all your CPU power for the next million years, without terminating.
- `schema.json`:
```
{"type":"object", "properties": {"prop": {"pattern": "a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}}}
```
- `subject-valid.json`
```
{"prop": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}
```

The reason behind is exponentially bad runtime behaviour of all PCRE regex engines.

You should consider using RE2 (https://github.com/google/re2j) instead, because this issue creates an easy denial-of-service-attack to all APIs using JSON schema validation for client-defined schemas.

**Comment by rkeytacked** [comment]
As seen in the PR using `com.google.re2j.Pattern` instead of `java.util.regex.Pattern` fixes the exponential runtime.

But https://github.com/google/re2j is BSD-3 licensed. Is this compatible with this project's Apache 2 License?

**Comment by erosb** [comment]
@rkeytacked in case you plan to upgrade to version 1.9.0 please keep in mind that we don't use re2j by default, because it caused some backward-compatibility problems for some users. You can still turn it on manually with a [one-line change](https://github.com/everit-org/json-schema#regexp-implementations).

**Comment by rkeytacked** [comment]
Thanks @erosb for the info.
(And regarding the spec compliance of the regexes I'm still trying to figure out how to influence the community behind JSON Schema Spec in a way that we can remove this "vulnerability by design" in future versions…)
