### ISSUE TITLE
If then else 

### ISSUE THREAD

**Issue by tipoca99** [everit-org/json-schema#154]
Hello,

I am trying to get If-then-else to work, but the validation just seems to ignore the if-then-else part of my schema. I am using the draftV7Support() option, when creating the schema loader. My schema looks like this:

{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "General validation schema for data sent from fromend to backend",
	"description": "Responsefinance.com",
	"type": "object",
	"properties": {
		"loan_amount": {
			"type": "integer"
		}
	},
	"if": {
		"properties": {
			"loan_amount": {
				"maximum": 9000
			}
		}
	},
	"then": {
		"required": [
			"first_name_co_apps"
		]
	},
	"else": {
		"required": [
			"last_name_co_apps"
		]
	},
	"required": [
			"loan_amount"
		]
}

Thanks for the help.

/Thomas

**Comment by erosb** [comment]
Hello Tomas, please provide a sample JSON instance which you expect to fail to validate. Thanks.

**Comment by tipoca99** [comment]
Hello,

Thanks for the quick reply.

I would expect this to fail, but it does not:

{ 
	"loan_amount": 14000
}

/Thomas

My code for creating the schema:

				JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));
				SchemaLoader loader = SchemaLoader.builder()
						.schemaJson(rawSchema)
						.useDefaults(true)
						.draftV7Support()
						.build(); 
				Schema schema = loader.load().build();

**Comment by tipoca99** [comment]
Hello,

I have also tried the example in the bottom of this page, with the same result:

https://epoberezkin.github.io/ajv/keywords.html#ifthenelse

Schema:
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "General validation schema for data sent from fromend to backend",
	"description": "Responsefinance.com",
	"type": "object",
    "if": { "properties": { "power": { "minimum": 9000 } } },
    "then": { "required": [ "disbelief" ] },
    "else": { "required": [ "confidence" ] }
}

Data:
{ "power": 10000 }

/Thomas

**Comment by tipoca99** [comment]
Hello,

Sorry for my spaming :-).

Now I tried this and now it actually fails as expected:

Schema:
{
    "if": { "properties": { "power": { "minimum": 9000 } } },
    "then": { "required": [ "disbelief" ] },
    "else": { "required": [ "confidence" ] }
}

Data:
{"loan_amount":14000}

**Comment by erosb** [comment]
Ok, I got this. The problem is that when the schema loader finds "type":"object" in the schema object then it assumes that the schema is an object schema and is looking only for object-specific keywords, so it ignores the if-then-else. You can work it around by using `"allOf"` :

```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "description": "Responsefinance.com",
  "title": "General validation schema for data sent from fromend to backend",
  "allOf": [
    {
      "type": "object",
      "properties": {
        "loan_amount": {
          "type": "integer"
        }
      },
      "required": [
        "loan_amount"
      ]
    },
    {
      "if": {
        "properties": {
          "loan_amount": {
            "maximum": 9000
          }
        }
      },
      "then": {
        "required": [
          "first_name_co_apps"
        ]
      },
      "else": {
        "required": [
          "last_name_co_apps"
        ]
      }
    }
  ]
}
```

**Comment by tipoca99** [comment]
Hello Bence,

Thank you very much for the help.

/Thomas
