### ISSUE TITLE
date-time format does not seem to work correctly

### ISSUE THREAD

**Issue by apiwoni** [everit-org/json-schema#158]
org.everit.json.schema.ValidationException: #/Timestamp: [2018-03-16T00:38:21.2665846Z] is not a valid date-time

Library Version: 1.4.0 
Validation against draft 6
"$schema": "http://json-schema.org/draft-06/schema#"

**Comment by erosb** [comment]
Please use the latest version of the library (1.8.0). Thanks.

**Comment by erosb** [comment]
Closing this ticket, please let me know if it is reproducible with 1.8.0. Thanks.

**Comment by apiwoni** [comment]
It does work now. My bad here I should have checked library versions against supported specs.
Thanks,
Andre
