### ISSUE TITLE
Optional attributes with null values

### ISSUE THREAD

**Issue by andrejserafim** [everit-org/json-schema#16]
If I have an optional field, for exapmle of type string, to be valid a document can either have the string, have the field missing or have null instead of the string. Are my expectations incorrect?

Currently the null case errors with a ValidationException.

**Comment by erosb** [comment]
> or have null instead of the string
Thats incorrect. An optional field with type "string" can be a string or the key can be omitted from the document. But it will be valid by this schema:

{
    "properties": {
        "myStringProp": {
            "anyOf": [
                { "type": "null"},
                {"type": "string"}
            ]
        }
    }
}

**Comment by andrejserafim** [comment]
Fair enough - thank you for clarifying.
