### ISSUE TITLE
$schema not validated against when a $schema is set

### ISSUE THREAD

**Issue by tzhoumsm** [everit-org/json-schema#160]
dateschema.json File:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "date": {
      "type": "string",
      "format": "date"
    }
  }
}
```

date.json file containing invalid date:
```
{
  "date": "2017-04-0"
}
```

Code run against:
```
        String schemaJson = Resources.toString(Resources.getResource("dateschema.json"), Charsets.UTF_8);
        String resultImpression = Resources.toString(Resources.getResource("date.json"), Charsets.UTF_8);

        JSONObject rawSchema = new JSONObject(new JSONTokener(schemaJson));
        JSONObject eventJson = new JSONObject(resultImpression);

        Schema schema = SchemaLoader.load(rawSchema);

        try {
            schema.validate(eventJson);
        } catch (ValidationException exception) {
            printError(exception, resultImpression);
        }
```
When debugging I can see that the specVersion is set to DRAFT_7 and the SchemaLoader.class config.specVersion is set to DRAFT_7

The issue is when the Schema line is run, it still validates against DRAFT_4. - the schema in debug mode can be seen to drop the "format":"date".
{"type":"object","properties":{"date":{"type":"string"}}}

When I create a custom SchemaLoader as below with the draftV7Support specified:
```
SchemaLoader schemaLoader = SchemaLoader.builder().useDefaults(false).schemaJson().draftV7Support().build();
        Schema schema = schemaLoader.load().build();
```
Then the "format":"date" appears at the Schema line.
{"type":"object","properties":{"date":{"type":"string","format":"date"}}}

What I don't want to do is create a custom schemaLoader like above as that appears to then validate all schemas against draft07?

Am I doing something wrong when specifying: "$schema": "http://json-schema.org/draft-07/schema#" ?

**Comment by erosb** [comment]
The fix is available in the latest release: [1.9.0](https://github.com/everit-org/json-schema/releases/tag/1.9.0)
