### ISSUE TITLE
Data-ref treated as number

### ISSUE THREAD

**Issue by kashif-imran** [everit-org/json-schema#162]
my schema property is like

"fromYear": {
            "array": false,
            "type": "number",
            "title": "From Year",
            "minimum": {
                "$data": "1/toYear"
             },
            "key": "fromYear",
            "required": false
        }

but when we call validate method of Schema then it throws error like

"#/properties/qualificationsection/items/properties/fromYear/minimum: expected type: Number, found: JsonObject"

JSON Schema supports minimum number as well as a jsonobject (ie., it supports union types) where we can specify data ref.

The library is unable to deal with this as is expecting minumum to always be of type number

**Comment by erosb** [comment]
Hello, `$data` is not currently the part of the json schema specification. It is currently a proposal, which may be supported by _some_ implementations (ajv, maybe?)
