### ISSUE TITLE
New version downloading from Jitpack.io seems not working well 

### ISSUE THREAD

**Issue by mrrllbb** [everit-org/json-schema#163]
For supporting draft06 and 07 later, I tried version 1.8.0 downloading from Jitpack.io maven repository.
And when I run the following code:
```
JSONObject jsonSchema = new JSONObject(schema);
try (InputStream inputStream = this.getClass().getClassLoader().getResourceAsStream("schema")) {
			JSONObject rawSchema = new JSONObject(new JSONTokener(new InputStreamReader(inputStream)));
			Schema validation = SchemaLoader.load(rawSchema);
			validation.validate(jsonSchema);
}
```
which is same as the README. But wahtever ths json or the schema is, the result is no any Exception.
For example, I set the rawSchema and the json both to `new JSONObject("{\"hello\" : \"world\"}")`, it also passed the validation.

When I change the version back to the 1.5.1, everything become ok. It is so odd.
When my pom flie contains:
```
	<repositories>
	    <repository>
	        <id>jitpack.io</id>
	        <url>https://jitpack.io</url>
	    </repository>
	</repositories>
        <dependency>
		<groupId>com.github.everit-org.json-schema</groupId>
		<artifactId>org.everit.json.schema</artifactId>
		<version>1.8.0</version>
	</dependency>
```
It doesn't work.

If:
```
        <dependency>
		<groupId>org.everit.json</groupId>
		<artifactId>org.everit.json.schema</artifactId>
		<version>1.5.1</version>
	</dependency>
```
It works well.

**Comment by VaaniSai** [comment]
Why has this issue been closed? I am not able to download artifacts from JitPack. Followed what given in README.
