### ISSUE TITLE
No location provided for SchemaException if a type is invalid

### ISSUE THREAD

**Issue by octavianN** [everit-org/json-schema#168]
If I load the following schema a SchemaException is thrown:
> \<unknown location\>: unknown type: [integger]

```json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "integger"
        }
    }
}
```
It seems that no location is set for this exception.

**Comment by erosb** [comment]
Hello @octavianN , thank you for raising this ticket. We fixed it in https://github.com/everit-org/json-schema/commit/2d8e68fac8df919c9291ddb840e1cc2f121f3e98 .

**Comment by octavianN** [comment]
Great. Thank you.
