### ISSUE TITLE
An IllegalArgumentException is thrown instead of a SchemaException

### ISSUE THREAD

**Issue by octavianN** [everit-org/json-schema#170]
If I load the following JSON Schema using `SchemaLoader.load(new JSONObject(new JSONTokener(schemaJson)))`  an `IllegalArgumentException `is thrown.  This is because the meta-schema URL is incorrect.
I think that a `SchemaException ` should be thrown in this case and have also the `schemaLocation ` set.
```JSON
{
    "$schema": "http://json-schema.org123/draft-06/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "integger"
        }
    }
}
```

**Comment by erosb** [comment]
The fix is available in the latest release: [1.9.0](https://github.com/everit-org/json-schema/releases/tag/1.9.0)
