### ISSUE TITLE
Misleading Readme

### ISSUE THREAD

**Issue by Wafflemon** [everit-org/json-schema#173]
There's another Jackson based json schema validator library that claims to be faster than your library. The last bullet in your "When to use this library?" section probably could be removed since you're comparing against the weaker of the two Jackson based libraries.

https://github.com/networknt/json-schema-validator

**Comment by Wafflemon** [comment]
Also, this library has quite a bit of compilation dependencies and isn't being published to the Maven repos anymore. That turned me off quite a bit.

**Comment by erosb** [comment]
Hello,

I think all of the performance benchmarks are outdated, so some re-testing of all libraries would be necessary.

I'm sorry to see that JitPack is not a sufficient repository for you.

**Comment by Wafflemon** [comment]
I missed the part in your readme that said that this library was being published to JitPack. I guess I just assumed that it was supposed to be in the maven repos because some older versions already live there.

**Comment by VaaniSai** [comment]
I am unable to get artifacts from JitPack. Followed README.
