### ISSUE TITLE
Only first element of an array is validated

### ISSUE THREAD

**Issue by OverLordDev** [everit-org/json-schema#175]
I defined a schema that contains an array of objects. When validating a JSON file against that schema only the first element of an array is validated. If there is a missing property in the second element of that array, the validation does not complain.

 schema_text = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
            "hash": {"type": ["string", "null"]},
            "affiliateId": {
                "type": "integer"
            },
            "status": {
                "type": "integer"
            },
            "ipAddress": {
                "anyOf": [
                    {"type": ["string"]},
                    {"format": "ipv4"},
                    {"format": "ipv6"}
                ]
            },
            "datePurchased": {
                "type": "string"
            },
            "orderTotal": {
                "type": "number"
            },
            "customerId": {
                "type": "integer"
            },
            "shipping": {
                "type": "object",
                "properties": {
                    "method": {
                        "type": "string"
                    },
                    "scheduleDate": {
                        "type": "string"
                    },
                    "cost": {
                        "type": "number"
                    },
                    "address": {
                        "type": "object",
                        "properties": {
                            "firstname": {
                                "type": "string"
                            },
                            "lastname": {
                                "type": "string"
                            },
                            "postcode": {
                                "type": "string"
                            },
                            "street": {
                                "type": "string"
                            },
                            "number": {
                                "type": "integer"
                            },
                            "complement": {
                                "type": "string"
                            },
                            "suburb": {
                                "type": "string"
                            },
                            "city": {
                                "type": "string"
                            },
                            "state": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "firstname",
                            "lastname",
                            "postcode",
                            "street",
                            "number",
                            "complement",
                            "suburb",
                            "city",
                            "state"
                        ]
                    }
                },
                "required": [
                    "method",
                    "scheduleDate",
                    "cost",
                    "address"
                ]
            },
            "payment": {
                "type": "object",
                "properties": {
                    "method": {
                        "type": "string"
                    },
                    "installments": {
                        "type": "integer"
                    }
                },
                "required": [
                    "method",
                    "installments"
                ]
            },
            "products": {
                "type": "array",
                "items": [{
                    "type": "object",

                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "quantity": {
                            "type": "integer"
                        },
                        "unitPrice": {
                            "type": "number"
                        },
                        "finalPrice": {
                            "type": "number"
                        },
                        "giftWrap": {
                            "type": "boolean"
                        },
                        "isFree": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "id",
                        "quantity",
                        "unitPrice",
                        "finalPrice",
                        "giftWrap",
                        "isFree"
                    ]
                }]
             }
        },
        "required": [
            "hash",
            "affiliateId",
            "status",
            "ipAddress",
            "datePurchased",
            "orderTotal",
            "customerId",
            "shipping",
            "payment",
            "products"
        ]
    }

**Comment by erosb** [comment]
It looks like a schema bug. You want to do list validation, but you actually do tuple validation.

See list vs tuple validation here: https://spacetelescope.github.io/understanding-json-schema/reference/array.html
