### ISSUE TITLE
json-schema with springboot

### ISSUE THREAD

**Issue by crazynet** [everit-org/json-schema#180]
I am considering to use json-schema for one of my project which is built in spring boot.
currently we are using hibernate-validator to validate the incoming request at controller level.

I understand the way json-schema works by seeing couple of examples.

I am actually not able to connect the dots between how the json-schema validation will fit into my existing project structure.
Could you please point me to any sample project preferably in Spring Boot so that I can co-relate with what I need to do in my current project.
Thanks in advance.

**Comment by erosb** [comment]
Hello, hibernate-validator and json-schema can both do validation, but in different tiers. hibernate-validator is at the data acces/entity layer, while json-schema can be used on the web tier. I would advise using json-schema from a servlet filter. In the filter you can read the request body, parse it into JSON and perform the validation, then proceed to the controller only if the input is valid.

I hope this helps.

**Comment by erosb** [comment]
Hello, hibernate-validator and json-schema can both do validation, but in different tiers. hibernate-validator is at the data acces/entity layer, while json-schema can be used on the web tier. I would advise using json-schema from a servlet filter. In the filter you can read the request body, parse it into JSON and perform the validation, then proceed to the controller only if the input is valid.

I hope this helps.
