### ISSUE TITLE
Default values of JSON sub-object is not written after validation

### ISSUE THREAD

**Issue by DatPhanTien** [everit-org/json-schema#181]
Dear,

Thanks to your project, I am currently using JSON in more organized manner. 

In an effort to define my JSON schema, I was facing an issue that the default value of a sub-object is not written after validation.

Please take a look at my simple example of my schema:

{
  "definitions" : {
    "stringField": {
      "type": "string",
      "minLength": 1
    }
  },
  "properties": {
    "name" : {
      "default" : "abc",
      "$ref": "#/definitions/stringField"
    }
  }
}

After validating and empty object `{}` against this schema, the result is NOT what I expect: `{"name" : "abc"}` BUT just an empty object as its initial content.

Do you know how to fix it?

**Comment by erosb** [comment]
Hi! According to [section 8.3 of the json schema core specification](http://json-schema.org/latest/json-schema-core.html#rfc.section.8.3) if `$ref` appears in an object, all other properties should be ignored. So the current behavior conforms to the spec.

If you want to work it around, you can probably do 
```
"name" : {
    "allOf": [
       {"default" : "abc"},
       {"$ref": "#/definitions/stringField"}
    ]
}
```

(I didn't test it)

**Comment by DatPhanTien** [comment]
Many thanks for you answer.

Regarding your suggest using allOf, I actually tried it before posting this issue. Unfortunately, it did not work.

Do you have any other idea?

**Comment by DatPhanTien** [comment]
Dear,

I finally can fix it. `allOf` is still what I needed, but the syntax is slightly different:

`"name" : {
    "allOf": [ {"$ref": "#/definitions/stringField"} ],
    "default" : "abc",
}`

Thank you again. We may close the issue now.

**Comment by erosb** [comment]
:+1: 

Have a nice day!
