### ISSUE TITLE
Json pointer references with the same name in different schema files are not resolved correctly

### ISSUE THREAD

**Issue by vierbergenlars** [everit-org/json-schema#182]
When using json pointers with the same name in different schema files, they all resolve to the schema that is pointed to by the first one that is resolved.

We have a schema that refers to two remote schema files.
Both of these files happen to have a `definition` with the same name, and both files refer to their own definition with a local json pointer (one that starts with `#`).

Expected behavior: Both references are resolved to the definition in their own file
Actual behavior: Both references are resolved to the definition that is resolved first

**Comment by vierbergenlars** [comment]
I have narrowed the cause down to here: https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/loader/ReferenceLookup.java#L118-L120 Commenting out these 3 lines fixes the issue.

I was thinking about prefixing the mapKey with `ls.id` before putting them in the `pointerSchemas` cache, but I don't know if that would cause unexpected side effects.

**Comment by erosb** [comment]
Thanks for your investigation. Unfortunately if you comment out those 3 lines then recursive schemas won't work. This will need a bit more work.
