### ISSUE TITLE
"useDefault" feature should work for "required" properties as well

### ISSUE THREAD

**Issue by fujianyang** [everit-org/json-schema#185]
Currently with version 1.8 "useDefault" works for non-required properties that have default value defined. If a property is "required" and is missing validation will report a ValidationException: #: required key not found.

Would it be working for "required" properties as well?

**Comment by erosb** [comment]
Hello @fujianyang , what is the usecase for declaring a property as required, while it also has a default value? Either you require the document to have the property (then why to have a default value), or you provide a default that you use when the property is not present (then why to make it required?)

I may be wrong, but I don't think it makes sense to use these keywords together. Can you please justify the usecase?
