### ISSUE TITLE
jackson as the JSON parser instead of org.json

### ISSUE THREAD

**Issue by ramuramaiah** [everit-org/json-schema#189]
Hi,
I have modified the original source code of everit JSON schema parser to make use of jackson as the underlying JSON schema parser instead of org.json due to the business unfriendly license of org.json JSON parser.
I have made sure the following
* The original design and the interfaces remains the same. The modification is only minimal.
* All tests pass.

Let me know if I can share the changes and anyone is interested to make use of the same.
I am not sure about the copyrights etc. Hence I don't want to create a new GitHub project.

**Comment by erosb** [comment]
Hello @ramuramaiah , thank you for your efforts. This sounds promising, though I doubt it doesn't break any of the method signatures. Please create a fork of this project and share your changes in the form of a pull request. If you are not familiar with this workflow please refer to [the GitHub documentation](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) .

Making the json implementation replaceable has been under consideration for quite some while, but for me it doesn't look simple to replace the data model of the library in a backward-compatible way (which is a top-priority for the project). I'm curious about what you figured out.

Thanks.

**Comment by ramuramaiah** [comment]
erosb,
Do I need some permissions to create a pull request for this project? The "create pull request" tab is disabled for me. I did login with my GitHub account.

**Comment by erosb** [comment]
You have to go to the [GH page of your fork](https://github.com/ramuramaiah/json-schema) and find the Pull Request button there.

**Comment by ramuramaiah** [comment]
erosb,
I have created a new pull request and you should be able to see it.
Following is the heading of the pull request
>>
Replaced the org.json JSON parser with jackson JSON parser #190
<<
Please review and let me know your opinion.

**Comment by Yobikap** [comment]
@ramuramaiah Is it possible to create a fork and implement your changes into that fork?

I also need this functionality as for now it is giving me a lot of headache to let the code work with existing POJO's and with Jackson

**Comment by erosb** [comment]
@Yobikap if you need jackson then TBH I would look for an other json schema library. There [are a few options nowadays](https://json-schema.org/implementations.html#validator-java).
