### ISSUE TITLE
Unit test failure on fresh clone

### ISSUE THREAD

**Issue by EXPEaneparaczki** [everit-org/json-schema#197]
![image](https://user-images.githubusercontent.com/19188570/42763860-7c36df04-8914-11e8-96e6-4a3994016e1b.png)

repro:

git clone [this repo]
mvn clean install

latest commit is:
https://github.com/everit-org/json-schema/commit/2d5ebf8ff4e956594937abfad7ba44bca729a36b

In fact it very much looks like this commit broke that test, it has edit in the method that is called in the test

I'm on windows 10 and using 1.8.0_144 JDK

**Comment by erosb** [comment]
The build is passing on CI: https://travis-ci.org/everit-org/json-schema/builds/404460352

Can you please post any additional error message, if any? Also what OS and JDK version do you use?

**Comment by erosb** [comment]
@EXPEaneparaczki can we close this ticket or do you still face the problem?

**Comment by EXPEaneparaczki** [comment]
no, it's perfect, thanks!
