### ISSUE TITLE
Validating enums, and other POJO fields

### ISSUE THREAD

**Issue by EXPEaneparaczki** [everit-org/json-schema#199]
Hi! So long story short, there is a utility to generate java POJOs from json schemas:

http://www.jsonschema2pojo.org/

Passing a schema the page returns with Java code that should comply with json schema, at least that's the idea.

For enums it generates nice Java enums and POJOs using them.

The problem is that any validation on these fields fail, since this library expects the type of these fields to be String.

Currently the only workaround is to serialize the JSONObject to string, then back to a JSONObject, and validate after that. Our use case disregards this because we serialize in a different way, and don't want to do so two times for each json.

**Do you think there is a way we can add to the functionality of this? There is already an enum schema, it's probably extensible to recognize java Enum types.**

Also this question raises the same issue for any other field, like the other day with BigIntegers.

Our services accept these JSONs and validates them, also us providing the schemas to send against. We would like to provide as easy usage as possible, ideally generate the POJOS with http://www.jsonschema2pojo.org/ and all clients have to do is fill it.

I'm happy to contribute if our workload allows it.

Thanks!
Attila

**Comment by erosb** [comment]
Hi! I' afraid I don't completely understand this request. Could you please give any examples?

**Comment by EXPEaneparaczki** [comment]
- Have a json schema with a field f with an "enum" = ["a","b","c"]
 - Have f in your POJO as a regular java enum that serializes to one of ["a","b","c"]
 - call org.everit.json.schema.Schema#validate on any instance of the POJO, validation fails because this lib says it should be type String

**Comment by erosb** [comment]
You shouldn't call `Schema#validate()` with any arbitary POJO. The library validates JSONObject and JSONArray instances (also JSON primitives like String/Number/Boolean), but not any java object. Maybe we should add some run-time typechecking there.
