### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by pjr1060** [everit-org/json-schema#20]
Thanks for an excellent and fast schema validator.   One question, is it possible to call Schema.validate()  concurrently so that we can validate two or more documents simultaneously?   

This would be fantastic as we could then build the Schema once and reuse it and potentially parallelize validations.

Thanks again.  Great work.

Peter

**Comment by erosb** [comment]
Hello @pjr1060 , the Schema subclasses were developed with keeping immutability in mind. So after obtaining a Schema object via SchemaLoader.load() , you can use the `validate()` method concurrently, to validate different JSON documents against the same schema.

You're welcome :)

**Comment by pjr1060** [comment]
Excellent!  Thank you!
