### ISSUE TITLE
SchemaLoader.load giving {} result

### ISSUE THREAD

**Issue by praveenbommali** [everit-org/json-schema#201]
Hi,  

I'm trying to convert  json file  to json-schema , as per the document , i'm following below code wise. 

>  ```
public static void main(String args[]) throws FileNotFoundException {
        try (InputStream inputStream = new FileInputStream("device.json")) {
            JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));
            **Schema schema = SchemaLoader.load(rawSchema);**
            schema.validate(new JSONObject("{\"hello\" : \"world\"}")); // throws a ValidationException if this object is invalid
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

```
Always I'm getting  Schema schema = SchemaLoader.load(rawSchema) as {} ,Please look into this

**Comment by erosb** [comment]
Hello, could you please post your device.json so I can help you with
investigating this.

PraveenBommali <notifications@github.com> ezt írta (időpont: 2018. aug. 3.,
P 12:27):

**Comment by praveenbommali** [comment]
Hi erosb, I tried with small sample json file, its not working with any json file. 
Please take below as sample json. 
`{
	"device": {
		"type": "module",
		"container1": {
			"type": "container",
			"leafname": {
				"type": "string",
				"description": "sample leaf "
			}
		}
	}
}`

If you mind please sample working code. Actually I'm interested to  convert the json to  json-schema with out using any model class.
Thanks in advance

**Comment by erosb** [comment]
Hello, this json seems to be an input json. Without knowing your schema json, I can't tell why doesn't it get validated properly. About json to json schema conversion: this is not the purpose of this library (this is for validation), but you may try to find some tools for this.
