### ISSUE TITLE
DefaultSchemaClient propagates IOException as a RuntimeException

### ISSUE THREAD

**Issue by vjrasane** [everit-org/json-schema#203]
```
    @Override
    public InputStream get(final String url) {
        try {
            return (InputStream) new URL(url).getContent();
        } catch (IOException e) {
            throw Throwables.propagate(e);
        }
    }
```

Catching this on a higher level would require catching all exceptions or all runtime exceptions, which generally is not a good idea. Similarly in JSONPointer (that calls clients get):

```
private static JSONObject executeWith(final SchemaClient client, final String url) {
        String resp = null;
        BufferedReader buffReader = null;
        InputStreamReader reader = null;
        try {
            InputStream responseStream = client.get(url);
            reader = new InputStreamReader(responseStream, Charset.defaultCharset());
            buffReader = new BufferedReader(reader);
            String line;
            StringBuilder strBuilder = new StringBuilder();
            while ((line = buffReader.readLine()) != null) {
                strBuilder.append(line);
            }
            resp = strBuilder.toString();
            return new JSONObject(new JSONTokener(resp));
        } catch (IOException e) {
            throw Throwables.propagate(e);
        } catch (JSONException e) {
            throw new SchemaException("failed to parse " + resp, e);
        } finally {
            try {
                if (buffReader != null) {
                    buffReader.close();
                }
                if (reader != null) {
                    reader.close();
                }
            } catch (IOException e) {
                throw Throwables.propagate(e);
            }
        }
    }
```

So it would be easier to just declare the exception in the method signatures and would allow callers to catch it when calling SchemaLoader.load. Throwables.propagate has also been [deprecated](https://github.com/google/guava/wiki/Why-we-deprecated-Throwables.propagate).

**Comment by erosb** [comment]
Hi!

Thanks for raising this issue. I think you are looking at an older version of the library, since currently we support JSON pointers [in an other class](https://github.com/everit-org/json-schema/blob/d947724e41704e6826b595edbeca18018b0049fa/core/src/main/java/org/everit/json/schema/loader/JsonPointerEvaluator.java), and we throw `UncheckedIOException`s which are easier to catch (also we use guava only on test scope).

**Comment by vjrasane** [comment]
Thank you. Yes, I'm using the Java 7 version. Is that version not updated anymore?

**Comment by erosb** [comment]
I'm not the maintainer of the [java7 fork](https://github.com/Doctusoft/json-schema). @fpeter8 do you have any plans to maintain it?

**Comment by fpeter8** [comment]
We're not actively maintaining it. You can fork and release it yourself, or create a PR in ours.
