### ISSUE TITLE
validatoin fails for valid datetime because of ZONE_OFFSET_PATTERN  value set as "XXX" instead of "XXXX"

### ISSUE THREAD

**Issue by smile18** [everit-org/json-schema#204]
I am not sure whether it is bug or made purposefully the ZONE_OFFSET_PATTERN to "XXX" instead of "XXXX" . Because of this our validation is failing for given valid datetime value say `2018-08-10T03:11:17+0000` . Question here is why the ZONE_OFFSET_PATTERN "XXX" is added to DateTimeFormatterBuilder? Thanks.

**Comment by erosb** [comment]
Hi,

the offset should be written as `+00:00` (mind the colon).
The date-time format [should conform](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.1) to RFC3339 - see the "time-numoffset" rule in  [this section](https://tools.ietf.org/html/rfc3339#section-5.6).
