### ISSUE TITLE
No static method getNames

### ISSUE THREAD

**Issue by kayvannj** [everit-org/json-schema#209]
I'm trying to use this lib in my Android project but I'm running into this runtime exception. 

```
    java.lang.NoSuchMethodError: No static method getNames(Lorg/json/JSONObject;)[Ljava/lang/String; in class Lorg/json/JSONObject; or its super classes (declaration of 'org.json.JSONObject' appears in /system/framework/core-libart.jar)
        at org.everit.json.schema.loader.ReferenceLookup.withoutRef(ReferenceLookup.java:76)
        at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:105)
        at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:255)
        at org.everit.json.schema.loader.SchemaLoader.access$100(SchemaLoader.java:25)
        at org.everit.json.schema.loader.SchemaLoader$6.get(SchemaLoader.java:319)
        at com.google.common.base.Absent.or(Absent.java:65)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:315)
        at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:397)
        at org.everit.json.schema.loader.CombinedSchemaLoader.load(CombinedSchemaLoader.java:85)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:314)
        at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:397)
        at org.everit.json.schema.loader.CombinedSchemaLoader.load(CombinedSchemaLoader.java:85)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:314)
```

the `getNames` method is not found in the org.json.JSONObject

![image](https://user-images.githubusercontent.com/2337268/44434611-f45d5180-a560-11e8-8a5a-37047453a121.png)

Any help is appreciated.

**Comment by erosb** [comment]
Hi! Android has its own version of the org.json library, built into their SDK, so the org.json maven dependency is simply ignored and this "slightly different" built-in library is used, with which this library isn't compatible.

The only thing that surprises me is that you hit the missing `getNames()` method sooner than the missing `JSONObject.toMap()` method. Can you please share your schema files? (or a minimal set of files on which the problem is reproducible?

**Comment by kayvannj** [comment]
Yeah, I suspect that is the case. Is there any alternative lib that I can use for validation purposes? 

I'm using this version:
```groovy
implementation("com.doctusoft:json-schema-java7:1.4.1")
```
And the way I'm loading the schema in android is like this:
```kotlin
object Validator {
	@WorkerThread
	fun verify(context: Application, jsonString: String) {

		val inputStream = context.resources.assets.open("dox-analytics/schemas/validate.json")

		val readText = InputStreamReader(inputStream).readText()
		val rawSchema = JSONObject(JSONTokener(readText))

		val schema = SchemaLoader.SchemaLoaderBuilder().schemaJson(rawSchema)
				.httpClient(SchemaLoaderClient(context))
				.build().load().build()
		// throws a ValidationException if this object is invalid
		schema.validate(JSONObject(jsonString))
	}

	class SchemaLoaderClient(private val context: Application) : SchemaClient() {
		override fun get(url: String?): InputStream {
			var filePath = url ?: ""
			if (filePath.startsWith("../")) {
				filePath = filePath.replaceFirst("../", "")
			}
			return context.resources.assets.open("dox-analytics/schemas/$filePath")
		}
	}
}
```
I don't believe this issue is related to my schema and it should be reproducable on any android project. 
however just to make it more specific here is are my android targetting:
```groovy
compile_sdk_version = 28
target_sdk_version = 28
min_sdk_version = 21
```

**Comment by erosb** [comment]
Hi! The `com.doctusoft:json-schema-java7:1.4.1` artifact is an external backport developed by [doctusoft](https://github.com/Doctusoft/json-schema) , and it isn't maintained by this project - and as far as I can tell they also don't have plans for maintaining it.

There are not many up-to-date json-schema implementations for java, for draft-6 and draft-7 this library is the only implementation. There are a couple of things I know about for draft-3 and draft-4 though:
 - there are 2 of them listed on the [list of obsolete implementations](http://json-schema.org/obsolete-implementations#validator-java) , I assume these are fairly well tested, but I have no clue if they work on android.

I also know that these exist but I don't know about their compliance / completeness / maturity, so I would think twice before relying on them:
 - https://github.com/bolerio/mjson/wiki/JSON-Schema-Support
 - https://github.com/FasterXML/jackson-module-jsonSchema

**Comment by kayvannj** [comment]
Thank you so much. I'm going to close this issue.
