### ISSUE TITLE
$ref points to id instead of file name

### ISSUE THREAD

**Issue by AlexTo** [everit-org/json-schema#212]
Hi I need to validate my json with TinCan schema, the schema files can be found here [TinCan Schema](https://github.com/RusticiSoftware/TinCanSchema/tree/master/1.0.1)

when I validate my statement, I  call schemaLoader.schemaJson(statementSchema), statementSchema comes from statement.json as folllows

    `{    
        "$schema": "http://json-schema.org/draft-04/schema#",
        "id": "#statement",
        "type": "object",
        "allOf": [{"$ref": "#statement_base"}],
        ....
    }`

And this is statement_base.json

    `{
        "$schema": "http://json-schema.org/draft-04/schema#",
        "id": "#statement_base",
        "type": "object",
        "required": ["actor", "verb", "object"],
        ....
    }`

As you can see, statement.json references statement_base.json by id (#statement_base) not file name (statement_base.json)

Currently, my work around is to manually update all the $ref from #someid to someid.json and use resolutionScope and it seems to work.

But is it possible to resolve references without manually updating the $ref in all the files? Because each time TinCan releases a new version, I will need to go update them all again.

Previously, I used another library in Scala and what I could do was to "preloadSchema" like this

`loader.preloadSchema(statementSchema)
    .preloadSchema(statementBaseSchema)
    .preloadSchema(activitySchema)
    ....`

By doing so, the "loader" stores all the schemas with their id so that reference by id will just work, can I do something similar with this library?

Thanks a lot

**Comment by erosb** [comment]
Hello @AlexTo , do you know about any json schema implementation which can do it for you?
This request doesn't seem to be related to any sections of the json schema spec, and actually your problem can probably be worked around by generating one schema json including all the dependency schemas.
