### ISSUE TITLE
API documentation for json-schema

### ISSUE THREAD

**Issue by ankshah** [everit-org/json-schema#221]
Hi,
I could not find any javadocs style API documentation for json-schema. Is any API documentation available apart from the github readme?

P.S: Not sure if this was supposed to be filed as an issue. Is there any alternative for asking questions?

**Comment by ankshah** [comment]
Hi @erosb , I was looking for something as simple as the return value of schema.validate method.

**Comment by erosb** [comment]
Hello, I published the javadoc of the latest version (1.9.2) here: http://erosb.github.io/everit-json-schema/javadoc/1.9.2/
