### ISSUE TITLE
#: only 1 subschema matches out of 2 no detailed message.

### ISSUE THREAD

**Issue by saurabhdwivedi13** [everit-org/json-schema#226]
This was claimed to be fixed in 1.6.0 but I am using 1.9.2 and I am still receiving this message.

**Comment by erosb** [comment]
That's fine, you need to look into the causing exception's message. The `ValidationException` instances form a tree structure, so you can either
 * traverse using the getCausingExceptions() method and print what you need
 * or get a flattened list of error messages using `ValidationException#getAllMessages()`
 * or just dump the tree as a json object using `ValidationException#toJSON()` and print it

**Comment by saurabhdwivedi13** [comment]
wow man ..so quick ..It is working .. ValidationException#getAllMessages() is  awesome. 
Thanks a ton for your quick response. All the best for future releases :)

**Comment by hitesh010** [comment]
That was awesome, Thanks!
