### ISSUE TITLE
Does validation happen for nested entities referred too?

### ISSUE THREAD

**Issue by indrajra** [everit-org/json-schema#227]
It appears that only the root schema is validated. The nested child entity schema isn't. Is this expected or is there a setting that I am missing to enforce this? I'd like to validate against a nested child entity schema too, as long as they are internal (not referring to external world).

**Comment by erosb** [comment]
Hello, this library validates json objects and not entities, but anyway, it definitely does validate child objects.

 Please raise a PR with a failing test [as described in the contribution guide](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md) to demonstrate your problem.

**Comment by indrajra** [comment]
Hi @erosb - I've created PR https://github.com/everit-org/json-schema/pull/228 for this. Take a look. Sorry, I had used object and entity in a synonymous way. Thanks for the correction.

**Comment by erosb** [comment]
Hello, I can see that this  reference causes the SchemaException: ` "$ref": "subdir/color.json#/definitions/name"`

It fails because it is a relative URI, and the loader needs an absolute base URI to resolve it against. It is documented as [resolution scopes](https://github.com/everit-org/json-schema#resolution-scopes).

**Comment by indrajra** [comment]
Well, if I set the resolution scope as suggested, it leads to a connection refused error. Is it that this library expects a http server even for local relative references?

**Comment by indrajra** [comment]
Once I setup a http server (for trial), I could see the child schemas was getting validated. Thanks @erosb for your guidance on this. I'm marking this ticket closed and withdraw my PR.

**Comment by indrajra** [comment]
Closing this issue and PR associated. I served the child schema through a http server and thereafter the validation happened on the child object as expected.
