### ISSUE TITLE
if then else validation message doesnt identify fields that have failed

### ISSUE THREAD

**Issue by felixvolz** [everit-org/json-schema#230]
I have a draft-07/schema with conditional mandatory field (see snippet below), when the schema fails validation I see the following error message which contains no references to the fields being referenced. Is there a way to make the error message more explicit (e.g. replay the fields being validated)

 
 ```
#: #: only 1 subschema matches out of 2
#: input is invalid against the "then" schema

```

 
```
"$schema": "http://json-schema.org/draft-07/schema#",
..
,
	"if": {
		"$id": "#/properties/condiitional",
		"properties": {
			"BORROWERNAME": {
				"enum": [
					"felix"
				]
			}
		}
	},
	"then": {
		"required": [
			"ADDRESSLINE1"
		]
	},
```

**Comment by erosb** [comment]
Hello, you may want to look into the `#getCausingExceptions()` of the thrown `ValidationException`

**Comment by felixvolz** [comment]
Thanks, I now understand I need to iterate over the chain of causing exceptions
