### ISSUE TITLE
Swagger spec support

### ISSUE THREAD

**Issue by cannondt** [everit-org/json-schema#234]
Hi,
I am trying to use this library for the following validation:
Inputs are:
a. swagger spec JSON
b. a payload JSON
Given these 2 inputs I would like to perform a validation wrt to the schema. So in the line below
`InputStream inputStream = getClass().getResourceAsStream("/path/to/your/schema.json"`
I provided the swagger spec JSON
and called
`schema.validate(<<payload JSON object>>`
However this does not work, it always returns as valid. 

Is my expectation wrong? If I provide a hand coded JSON schema and the payload, validation happens fine but something goes amiss if I provide a swagger spec JSON. 

Can you please help me out with this issue?

Ananth

**Comment by erosb** [comment]
Hi!

The problem doesn't seem to be related to openapi (swagger).
Please raise a PR reproducing the problem [as described in the contribution guide](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md) . Thanks.

**Comment by cannondt** [comment]
Hi !
This whole PR thing was new to me. However I think I have done it correctly, please do let me know if I have messed up something!

Here is the snippet of code that I used to test:
`System.out.println("Hello testing schema validation via everit");
        		try (InputStream inputStream = new FileInputStream(new Test().getFile("schema.json")) {})
        {
            System.out.println("input stream is " + inputStream);
            JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));
            Schema schema = SchemaLoader.load(rawSchema);
            InputStream jsonInputStream = new FileInputStream(new Test().getFile("subject-invalid.json"));
            JSONObject object = new JSONObject(IOUtils.toString(jsonInputStream, "UTF-8"));
            schema.validate(object);

        } catch (JSONException | IOException | ValidationException e) {
            System.out.println("Failed");
        }
        System.out.println("Done with everit");`
