### ISSUE TITLE
 How to verify string numbers

### ISSUE THREAD

**Issue by suifengpiao14** [everit-org/json-schema#236]
Hello！ There is a doubt to ask, the number in the network request will be treated as a string in the transmission, at this time with json-schema verification will prompt the type error. How to solve it, thank you

**Comment by erosb** [comment]
Hello, you can define it as a string in the json schema, and verify with regex that it is a proper number (you will have to use the [pattern keyword](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.3.3))

**Comment by suifengpiao14** [comment]
I get it.
thank you very match
