### ISSUE TITLE
hot to name reference schemas correctyl with $ref

### ISSUE THREAD

**Issue by rklueber** [everit-org/json-schema#245]
Hi guys,

I am pretty new to Java and I got stuck with the documentation on how to use $ref in the schema definition.

I am a bit stuck. Can someone point me into the right direction how a basic/example of such a referenced schema could look like with json files loaded from a local file and all json-schemas are in the same subdir?

Assuming I have the following schema definitions with 

./schemas/boundingBoxRef.json
`{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "Raw Data Export Configuration",
    "$id": "http://example.com/boundingBoxRef.json",
    "required": [
      "lllatitude",
      "lllongitude",
      "urlatitude",
      "urlongitude"
    ],
    "properties": {
      "lllatitude" : { "$ref": "file://latlon.json#/properties/LATITUDE" },
      "lllongitude": { "$ref": "file://latlon.json#/properties/LONGITUDE" },
      "urlatitude" : { "$ref": "file://latlon.json#/properties/LATITUDE" },
      "urlongitude": { "$ref": "file://latlon.json#/properties/LONGITUDE" }
    }
  }
`
and ./schemas/boundingBoxRef.json
`
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "Raw Data Export Configuration",
    "$id": "http://example.com/boundingBoxRef.json",
    "required": [
      "lllatitude",
      "lllongitude",
      "urlatitude",
      "urlongitude"
    ],
    "properties": {
      "lllatitude" : { "$ref": "latlon.json#/properties/LATITUDE" },
      "lllongitude": { "$ref": "latlon.json#/properties/LONGITUDE" },
      "urlatitude" : { "$ref": "latlon.json#/properties/LATITUDE" },
      "urlongitude": { "$ref": "latlon.json#/properties/LONGITUDE" }
    }
  }
`

I try to validate with this json

`{
    "lllatitude": 0.0,
    "lllongitude": 0.0,
    "urlatitude": 0.0,
    "urlongitude": 181.0
}
`

The Java code I use is this
`
			JSONObject rawSchema = readFileToJSONObject(schemaFilename);
			JSONObject rawInstance = readFileToJSONObject(instanceFilename);
			SchemaLoader schemaLoader = SchemaLoader.builder()
			        .resolutionScope("http://example.com/") // setting the default resolution scope
		        .build();
			Schema schema = schemaLoader.load(rawSchema);
			schema.validate(rawInstance);
`

the error I get is
`Exception in thread "main" org.everit.json.schema.combatibility.UncheckedIOException: java.net.UnknownHostException: latlon.json
...
`

I tried all possible options I could imagine without success. 

Looking forward for your help and I promisse to update the documentation once I have a running simple example.

Thanks in advance.

**Comment by adveres** [comment]
I spent all day on a similar issue. Here is my layout.

```
/src/main/resources/json/
├── export.schema.json
└── subSchemas
    └── commonModules.schema.json
```

To reference that `subSchemas/commonModules.schema.json` file I had to do multiple things.

### In the schema
The parent schema (`export.schema.json`) has this entry for its `$ref`
```json
    "commonModules": {
      "$id": "#/properties/commonModules",
      "$ref": "/json/subSchemas/commonModules.schema.json"
    },
```

### In Java, making the Schema object.
I also had to make a custom `SchemaClient` to load from the classpath and pass it in to `.httpClient()` when I built my `Schema` object.
```java
public class ClassPathSchemaClient implements SchemaClient {
    @Override
    public InputStream get(String url) {
        return this.getClass().getResourceAsStream(url);
    }
```
```java
        this.schema = SchemaLoader.builder()
                .schemaJson(rawSchema)
                .httpClient(new ClassPathSchemaClient())
                .build()
                .load().build();
        this.validator = builder.build();
```

I may make a PR to get this `ClassPathSchemaClient` put in as a default. I'm unsure if the author has a better way to do this.

**Comment by erosb** [comment]
Actually I wanted to include some sort of classpath-based schema client in the library so @adveres yes please raise a PR. Thank you.

**Comment by erosb** [comment]
@adveres are you fine with this `SchemaClient` or do you have something more advanced? Please take a look: https://github.com/everit-org/json-schema/commit/6ed56f9be37b962c1d9f3b986b336191085b0583#diff-12d6eef23a1c4f81b17bf95e146e265b

Thanks.

**Comment by adveres** [comment]
Sorry, @erosb, I was going to do it but went away for the weekend.

Looks good to me. I was going to have it be separate (without the fallback) and force people to use the `.schemaClient()` builder method. Yours is certainly more usable - nice!

Thank you for handling it!
