### ISSUE TITLE
Support for Draft 8

### ISSUE THREAD

**Issue by kenisteward** [everit-org/json-schema#252]
There are a number of new changes coming in draft 8 for json-schema which you can find here:

https://github.com/json-schema-org/json-schema-spec/milestone/6

A number of them are very helpful (standardized output formatting / support for custom vocabulary etc) and would be great to be supported ASAP.  I was wondering if anyone was looking into the ground work for adding these features.  My project will be heavily using json-schema and we will need to be able to add custom keywords to the validator like ajv has here:

https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md

I saw there was support for custom format validators but could this be extended to create "extensions" to support custom keywords?

Thanks and I look forward to further discussion!

**Comment by kenisteward** [comment]
Thanks for your reply!

From my understanding draft 8 should be released in the next couple weeks. I was hoping to edge some pre work out while waiting

**Comment by kenisteward** [comment]
Any updates on this?

**Comment by erosb** [comment]
The currently ongoing work is in the `draft-2019-09` branch.

**Comment by erosb** [comment]
Hello @kenisteward , recently I [released a new validator library](https://github.com/erosb/json-sKema) that supports draft2020-12 version of json schema. Closing this issue, the everit-org/json-schema library won't see any major updates in the future.
