### ISSUE TITLE
Additional properties is ignored when property is set to null

### ISSUE THREAD

**Issue by bbarin** [everit-org/json-schema#253]
When defining a JSON schema to enforce additionalProperties to be forbidden (set to *false*) - the library ignores it *only* when the property is set to `null` (other values works fine)

**Comment by bbarin** [comment]
Hey, sorry the bug was on the serialization of org.json.JSONObject which ignores `null` values.
Closing it.

**Comment by erosb** [comment]
No problem. I think you can use `JSONObject.NULL` instead of a `null` reference and it will be included during serialization.

**Comment by bbarin** [comment]
Indeed. :)
