### ISSUE TITLE
Support for | in definitions removed?

### ISSUE THREAD

**Issue by coderextreme** [everit-org/json-schema#258]
Check out full source and jars (different root repository):
```
$ git clone https://github.com/coderextreme/json-schema
$ cd json-schema
```
Programs compile in separate ant build:
```
$ ant
```

**Comment by coderextreme** [comment]
I think the issue here is that | is not valid in a URI and definitions use a valid URI

**Comment by erosb** [comment]
Hello, I cloned your project and after replacing all occurences of `|` with `%7C` (its url-encoded form) it worked.

**Comment by coderextreme** [comment]
I tried the same thing, and it didn’t work ??? can you issue a pull request against my project? Thanks!

I’m running 1.10.0

Just try ant on the command line is how I’ve been testing.

John

Sent from Mail for Windows 10

**Comment by erosb** [comment]
Hi! I added a minimal reproduction test here, verifying that % escaping works: https://github.com/everit-org/json-schema/commit/ea06c38df8dcca4d828ce86b9b3af70594adeec3

**Comment by coderextreme** [comment]
Can you explain what this tests? I see %7C, but I also see another | in A|B?  Okay, it looks like I works on my example project as well, But I will need to run a full production run, and change my schema generator as well in my production project.  This will take more time.   This example below shows how we might use | in both X3DUOM and X3D JSON schema, by using %7C in definition “ref$”s, but not in definitions.

John
Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
I commented on the test “pull” so it appears to be working on my system.

Please close this issue.  I will follow up on choice of separator with the X3D folks

John

Sent from Mail for Windows 10

From: John Carlson
Sent: Friday, January 11, 2019 4:01 PM
To: everit-org/json-schema; everit-org/json-schema
Cc: State change; Don Brutzman
Subject: RE: [everit-org/json-schema] Support for | in definitionsremoved?(#258)


Can you explain what this tests? I see %7C, but I also see another | in A|B?  Okay, it looks like I works on my example project as well, But I will need to run a full production run, and change my schema generator as well in my production project.  This will take more time.   This example below shows how we might use | in both X3DUOM and X3D JSON schema, by using %7C in definition “ref$”s, but not in definitions.

John
Sent from Mail for Windows 10

**Comment by erosb** [comment]
> Can you explain what this tests? I see %7C, but I also see another | in A|B?

Yes. In the reference (`"$ref"`) the value is URL-encoded. In the definition itself it is not. The rationale is that the name under `"definitions"` can be any valid JSON string, but when it is referenced, the reference should be a URL (therefore properly encoded). I'm pretty sure it is standard-compliant behaviour. 

If you can't make the schema generator work this way, then you can use a simple post-processor which rewrites all `$ref`s to be URL-encoded. It would look something like this (I just sketched it up in 20 minutes so not very well tested):

```java

import java.util.*;
import java.net.*;
import org.json.*;

public class Main {
    
    private static String PREFIX = "#/definitions/";
    
    static void encodeChildren(Object value) {
        if (value instanceof JSONObject) {
            urlEncodeRefs((JSONObject) value);
        } else if (value instanceof JSONArray) {
            urlEncodeRefs((JSONArray) value);
        }
    }
    
    static void urlEncodeRefs(JSONArray orig) {
        for (int i = 0; i < orig.length(); ++i) {
            Object value = orig.get(i);
            encodeChildren(value);
        }
    }
    
    static void urlEncodeRefs(JSONObject orig) {
        String[] names = JSONObject.getNames(orig);
        for (String name : names) {
            Object value = orig.get(name);
            if ("$ref".equals(name)) {
                if ( ! (value instanceof String)) {
                    throw new RuntimeException("$ref must be a string");
                }
                String refValue = (String) value;
                if (refValue.startsWith(PREFIX)) {
                    refValue = refValue.substring(PREFIX.length());
                    orig.put("$ref", PREFIX + URLEncoder.encode(refValue));
                } else {
                    System.out.println("WARNING: skipping encoding of $ref " + refValue);
                }
            } else {
                encodeChildren(value);
            }
        }
    }
    
    public static void main(String[] args) {
        JSONObject o = new JSONObject(new JSONTokener(System.in));
        urlEncodeRefs(o);
        System.out.println(o);
    }
    
}
```

**Comment by coderextreme** [comment]
Yeah, that trickled through my brain. Thanks for the brain download. Schema generator works fine with a .replace in python.

John

Sent from Mail for Windows 10
