### ISSUE TITLE
Validate a property based on another

### ISSUE THREAD

**Issue by stp72** [everit-org/json-schema#269]
Trying to validate the following data:

```
{
  "portRange": {
    "from": 90,
    "to": 80
  }
}
```

based on the following schema:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions" : {
    "port":{
      "type": "number",
      "minimum": 0,
      "maximum": 65535
    },
    "portRange": {
      "properties": {
        "from": {
          "description": "The lower bound port of the range. (inclusive)",
          "$ref": "#/definitions/port"
        },
        "to" : {
          "description": "The upper bound port of the range. (inclusive)",
          "$ref": "#/definitions/port"
        }
      }
    }
  }
}
```

I would like to validate that the to > from.  I wanted to use a custom FormatValidator, but I'm unable to do so because they are based on strings.  Is there a better way for me to do this?

Thanks for the help and time!

**Comment by erosb** [comment]
Hello,

the json schema specification doesn't have any keywords for numeric comparisons, so this library doesn't support it either.

**Comment by stp72** [comment]
That is what I figured but wanted to confirm.  I guess I'll put this in the business logic instead.  Thanks again for your help!
