### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by da-z** [everit-org/json-schema#27]
Would be nice if this library supported internationalization for the exception messages.

**Comment by erosb** [comment]
Hello,

I don't think i18n is in the scope of the validator itself, but it should be easy to process the `ValidationException`s and create user-readable errors. The `ValidationException#getCausingExceptions()` and `ValidationException#getPointerToViolation()` have been added with this concept in mind. Maybe `getPointerToViolation()` should return a more sophisticated representation of the pointer than a raw string, so it may be some kind of list of pointer fragments.

From this point of view, would you need any further improvements to simply implement i18n outside of the library?

**Comment by atilacamurca** [comment]
Hi,

can you show a simple example of this? Maybe put on the documentation.
