### ISSUE TITLE
SchemaLoader.SchemaLoaderBuilder() throws NullPointerException

### ISSUE THREAD

**Issue by ylin2139** [everit-org/json-schema#275]
I am using 1.11 version in my Grails project. This is how I use it:

try {
            schema = SchemaLoader.load(schemaJson)
            schema.validate(jsonObj)
        } catch(Exception e) {
           //...
        } 

It works fine. I can successfully validate my object. However  I got a NullPointerException in my console (my catch block didn't  catch it).  I tried to trace what caused that, it happened when initiate SchemaLoader. And more precisely, the log message pointed to SchemaLocation: Line 85. 

Did I miss some configuration when using you library? Thanks.

**Comment by erosb** [comment]
Hello, please post the schema json and the exception trace you are getting, thanks
