### ISSUE TITLE
Confusing error message for "minimum" violation

### ISSUE THREAD

**Issue by haydenzone** [everit-org/json-schema#277]
Howdy, 

First off, love this project! Just started using it and it's great. 

I wrote a validation rule asserting that a numeric value should be between 0 and 100. Whenever there is a schema violation, `validationExcept.toString()` is a little un-intuitive. 

```
#/targets/0/rollout_percentage: #: only 1 subschema matches out of 2
```

It'd be helpful if the error message more clearly stated what the issue was. 

Thanks!
Hayden

**Comment by erosb** [comment]
Hi! Can you please post your schema? I suspect you used `"type"` as an array (which construct gets implicitly rewritten to any `"allOf"` schema).

Anyway, `ValidationException#getCausingExceptions()` and `#getAllMessages()` helps a lot. See  [investigating failures](https://github.com/everit-org/json-schema#investigating-failures) in the manual.

**Comment by haydenzone** [comment]
I think that'll work. Thanks!
