### ISSUE TITLE
JSON Schema With AdditionalProperties=false

### ISSUE THREAD

**Issue by beeva-pablovaliente** [everit-org/json-schema#28]
Hi all,

When we are trying to validate a JSON Body against a JSON Schema that has set the additionalProperties to false, we are founding that the Schema.validate() function just return the first parameter that it is not permitted. We can see that behavior in the _org.everit.json.schema.ObjectSchema_ class at line _279_. (Version 1.1.1)

We have seen that there is a commit (https://github.com/everit-org/json-schema/blob/07ba71cb59ee5cc0fa891e3ec8cc9cd6ff08b910/core/src/main/java/org/everit/json/schema/ObjectSchema.java#L279) that resolves this behavior. 

When will be this new version available to download from Maven repository?

Thanks in advance.

**Comment by erosb** [comment]
Hi!

I planned the next version to be released with "format" keyword support. I started working on it in [in my own fork](https://github.com/erosb/json-schema-validator/tree/format) but in the recent weeks I didn't have time to work on it. So maybe it will be ready in a month, but this is just an estimate.

**Comment by beeva-pablovaliente** [comment]
Ok, thanks for your work @erosb 

Regards!

**Comment by erosb** [comment]
@beeva-pablovaliente version 1.2.0 has been released yesterday, it contains the additionalProperties bugfix.
