### ISSUE TITLE
Question about additional schema files

### ISSUE THREAD

**Issue by melnikovdv** [everit-org/json-schema#282]
Hi. I have s schema and an additional child schema with common objects. Validator doesn't work until I put there full path to schema file:

`"images": { "type": "array", "items": { "$ref": "file:///C:/path/to/additional/schema/common.schema.json#/definitions/Image" } }`

Is it possible to avoid full path in child schema reference and to read child schemas from the same folder? 

If I leave as in the [example ](https://json-schema.org/understanding-json-schema/structuring.html), only

`common.schema.json#/definitions/Image`

it fails with an error: java.net.MalformedURLException: no protocol: common.v1.schema.json

If I leave with file: schema as

`file:common.schema.json#/definitions/Image`

it fails with error: java.io.FileNotFoundException: common.v1.schema.json (The system cannot find the file specified)

If I leave as

`file:///common.v1.schema.json#/definitions/Image`

it fails with `java.io.FileNotFoundException: \common.v1.schema.json (The system cannot find the file specified)`

**Comment by erosb** [comment]
> Is it possible to avoid full path in child schema reference

Yes, please refer to the relevant section of [the manual](https://github.com/everit-org/json-schema#ref-resolution). Thanks.
