### ISSUE TITLE
Default values not available unless useDefaults set

### ISSUE THREAD

**Issue by fbacall** [everit-org/json-schema#288]
In my code I would like to access the default value for a schema (using `Schema#hasDefaultValue` and `Schema#getDefaultValue`), but I don't want them to be automatically inserted during the validation process. 

Unless I am mistaken, it seems that they are always `null` unless `useDefaults` is set to true.

PS. Thanks for the great library, I found it much more complete and easy to use than the alternatives.

**Comment by fbacall** [comment]
I now see that `default` is accessible through `Schema#getUnprocessedProperties` when `useDefaults` is off, which is enough for my use case. Feel free to close this!

**Comment by erosb** [comment]
Yes, an other option would be loading the schema twice, once with `useDefaults()` and once without it.
