### ISSUE TITLE
Self-reference validations

### ISSUE THREAD

**Issue by ben-manes** [everit-org/json-schema#289]
We store JsonSchema in the database to validate data against and update the schemas fairly regularly. When adding a new enum definition, validating a schema failed because it validated the reference against the database's copy instead of the local instance. This is because we typically use the fully qualified name, rather than the shortcut to the local definition. This means `uri#definitions/foo` fails while `#definitions/foo` passes when adding a new property that references the newly defined type.

It would seem correct that `SchemaLoader.load(schema, client)` would shortcut resolution of definitions to its URI to use itself, rather than calling the client. The workaround is to make the client do this, e.g.

```java
EntitySchema entitySchema = mapper.convertValue(jsonObject, EntitySchema.class);
byte[] data = mapper.writeValueAsBytes(entitySchema);
SchemaLoader.load(jsonObject, uri -> {
  return entitySchema.getId().toString().equals(uri)
      ? new ByteArrayInputStream(data)
      : schemaClient.apply(uri);
});
```

**Comment by erosb** [comment]
Hello @ben-manes , I think the best approach to the problem would be implementing a `SchemaClient` which caches the received schema jsons (maybe w/ respect to the http cache header, maybe only for the duration of a single schema loading).

The minor problem with the code snippet you posted above is it assumes that the schema is loaded from the URI equivalent to its `"id"`. This may be true in your case, and is a good practice, but nothing ensure it in general.
