### ISSUE TITLE
Relative paths for JSON references are not supported

### ISSUE THREAD

**Issue by iainporter** [everit-org/json-schema#29]
given a root schema and a subschema in a different file:

parent.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"child": {	"$ref": "child.json"}
	}
}

child.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "child.json",
	"type": "object",
	"properties": {
	    "foo": {"type": "string"},
	    "bar": {"type": "string"}
	}
}

I would expect to be able to reference child.json as relative to the location of the root schema. Currently I would have to provide an absolute URI for the root schema id (i.e "id": "http://localhost:/myschemas/parent.json") and deploy that to a web container.

**Comment by erosb** [comment]
Hello,

since in the context of this library the parent schema comes from an input stream and not necessarily from a file, it doesn't really have location, therefore that non-existent location cannot be used as an initial resolution scope. I also can't find anything in the json schema spec which would indirectly expect such behavior from an implementation.

**Comment by erosb** [comment]
Others have requested similar functionality too, so I'm reopening this issue.

Although the location of a schema is still not possible to determine (not even sure if such location exists), it may make sense to optionally pass a base URI to the `SchemaLoader`, against which the relative URIs (`is` values) will be resolved.

**Comment by logslie** [comment]
Hello,

I have defined the following schemas:

**steering-provider.json**
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://jsonschema.net/steeringprovider",
  "type": "object",
  "properties": {
    "id": {
      "id": "http://jsonschema.net/id",
      "type": "string"
    },
    "algorithm": {
      "id": "http://jsonschema.net/algorithm",
      "type": "string",
      "format":"algorithm"
    },
    "links": {
      "id": "http://jsonschema.net/links",
      "type": "object",
      "minProperties": 1
      
    },
    "metaInjectionFields": {
      "id": "http://jsonschema.net/alias",
      "type": "object",
      "minProperties": 1,
      "patternProperties":{"^[a-zA-Z0-9_]*$":{"$ref": "http://jsonschema.net/metaschema"}}

    }
  },
  "required": [
    "id",
    "algorithm",
    "links"
  ]
}

```

**meta-schema.json**

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://jsonschema.net/metaschema",
  "type": "object",
  "properties": {
    "tagname": {
      "id": "http://jsonschema.net/tagname",
      "type": "string"
    },
    "override": {
      "id": "http://jsonschema.net/override",
      "type": "boolean"
    }
  },
  "required": [
    "tagname",
    "override"
  ]
}

```

In **metaInjectionFields** of the first one I have a reference to **meta-schema** file, but it doesn't work.
The validation code is the following:

```
public String validateJson(JSONObject provider) {
		String result = "";
		try {
			InputStream inputStream = getClass().getResourceAsStream("/json-schemas/steering-schema-json");
			JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));
			SchemaLoader schemaLoader = SchemaLoader.builder().schemaJson(rawSchema) 
					.addFormatValidator("algorithm", new AlgorithmValidator()) 
					.build();
			Schema schema = schemaLoader.load().build(); 
			schema.validate(provider);
			result = "SUCCESS";
		} catch (ValidationException e) {
			...

		}catch(Exception ex){
			...
		}
		return result;

	}
```

I'm getting the exception:
` java.io.UncheckedIOException: java.io.FileNotFoundException: http://jsonschema.net/metaschema`

Do I have to load both json schemas to do the validation?
What is it wrong in my code?

Thanks

**Comment by erosb** [comment]
Hello @logslie , I'm not sure if I properly understand your usecase.

 The `metaInjectionFields` refers to `http://jsonschema.net/metaschema` , and this request truly returns  HTTP 404 response (I've just checked it). In such case the `java.net.URL` throws a `FileNotFoundException`.

**Comment by logslie** [comment]
Hi,
My problem is that I need to refer from one Json schema to other. Both are in the same folder of my project.
How do I have to refer to a local json schema file?
Like this?
`"patternProperties":{"^[a-zA-Z0-9_]*$":{"$ref": "meta-schema.json"}}`

Thanks,

**Comment by erosb** [comment]
Yes, exactly.

There is a sample in the integration tests:
https://github.com/everit-org/json-schema/blob/master/tests/src/test/java/org/everit/json/schema/RelativeURITest.java

Root directory of the schemas: https://github.com/everit-org/json-schema/tree/master/tests/src/test/resources/org/everit/json/schema/relative-uri

**Comment by logslie** [comment]
Yeah, I was checking your code before, when you start your server you are setting a new root document to receive request in that path, but when I start the jetty server I'm using CXFServlet, and I don't know how to add a new holder with the new path...
If I don't set the path in the servlet I get the exception:
`java.io.UncheckedIOException: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8081/target/classes/json-schemas/meta-schema.json`

```
	this.server = new Server(this.port);
		// Register and map the dispatcher servlet
        final ServletHolder servletHolder = new ServletHolder( new CXFServlet() );
        final ServletContextHandler servletcontext = new ServletContextHandler();   
        servletcontext.setContextPath( "/" );
        servletcontext.addServlet( servletHolder, "/*" );  
```

Thanks,
