### ISSUE TITLE
java.net.MalformedURLException: when using relative paths between schemas.

### ISSUE THREAD

**Issue by Poorvankbhatia** [everit-org/json-schema#290]
Hi Team, 
I am using this [version](https://mvnrepository.com/artifact/com.github.erosb/everit-json-schema-jdk6) since i want to use JSON Schema Core Draft v7.
But while using relative schema's in my JSON schema ("using $ref and providing relative path") it gives me a java.net.MalformedURLException:

My code for my schema builder looks like as follows:

```
SchemaLoader loader = SchemaLoader.builder()
                .schemaJson(rawSchema)
                .draftV7Support()
                .build();
        Schema schema = loader.load().build();
        schema.validate(inputJson);
```

I am unable to use resolution scope also because the version `1.9.2` does not contains a `schemaClient(SchemaClient.classPathAwareClient())` method. Hence even if i use a resolution scope `.resolutionScope("classpath:///pathToMyJson")` , it says `unknown protocol: classpath`

It does not contains `registerSchemaByURI` method also.

Is there a way to use relative paths in schema's using this library? @erosb

**Comment by Poorvankbhatia** [comment]
> Hi Team,
> I am using this [version](https://mvnrepository.com/artifact/com.github.erosb/everit-json-schema-jdk6) since i want to use JSON Schema Core Draft v7.
> But while using relative schema's in my JSON schema ("using $ref and providing relative path") it gives me a java.net.MalformedURLException:
> 
> My code for my schema builder looks like as follows:
> 
> ```
> SchemaLoader loader = SchemaLoader.builder()
>                 .schemaJson(rawSchema)
>                 .draftV7Support()
>                 .build();
>         Schema schema = loader.load().build();
>         schema.validate(inputJson);
> ```
> I am unable to use resolution scope also because the version `1.9.2` does not contains a `schemaClient(SchemaClient.classPathAwareClient())` method. Hence even if i use a resolution scope `.resolutionScope("classpath:///pathToMyJson")` , it says `unknown protocol: classpath`
> 
> Is there a way to use relative paths in schema's using this library?

**Comment by erosb** [comment]
Hello @Poorvankbhatia ,

to make the `classpath://` protocol work with version `1.9.2` you have to implement a [custom protocol handler](https://stackoverflow.com/questions/861500/url-to-load-resources-from-the-classpath-in-java) for the `java.net.URL` class.
(sidenote: this works by default in spring environments)
