### ISSUE TITLE
Fully resolved json object

### ISSUE THREAD

**Issue by lmcpifi** [everit-org/json-schema#292]
Hi,

No issues here, just a question.  Do you have (or will plan to have) an api that will return the fully resolved json that is being validated on.  As an example a json file which ref's another json file and so on.

**Comment by erosb** [comment]
Hello, we do not plan to support it. But there is an existing library for the bare purpose of handling `"$ref"`s: https://github.com/AndersDJohnson/jackson-json-reference
I'm not sure how stable it is, but you can give it a go.

**Comment by lmcpifi** [comment]
thanks for your prompt reply
