### ISSUE TITLE
Referencing schema files in resources/jar

### ISSUE THREAD

**Issue by HungUnicorn** [everit-org/json-schema#297]
I package json schemas, located in `src/main/resources` in a `event-schemas.jar` and would like this library to be used by importing the dependency(mvn).

`$ref` works well in the unit test of `event-shemas` code, but when using the library in my application, the `$ref` does not work and throws `Malformed URL:  no protocol: ../event.json`.

The difference of the resolution scope is as follows:

my application which imports the `event-schemas.jar`:
```java
SchemaLoader build = SchemaLoader.builder().schemaJson(rawSchema)
.resolutionScope("jar:file:/home/me/.m2/repository/org/my-org/event-schemas/1.0.0-SNAPSHOT/event-schemas-1.0.0.jar!/schemas/events/")
.build();
```
in my-json-schema java code. the resolutionScope is:

```java
SchemaLoader build = SchemaLoader.builder().schemaJson(rawSchema)
.resolutionScope("file:/home/me/.m2/repository/org/my-org/event-schemas/1.0.0-SNAPSHOT/event-schemas-1.0.0.jar!/schemas/events/")
.build();
```

and it works well. resolution scope and schema path are retrieved by:
`getClass().getClassLoader().getResourceAsStream(schemaPath)`
`getClass().getClassLoader().getResource(resolutionScope)`

Does it mean currently the library cannot refer to the schemas in a jar?

I found this was an issue in a scala lib
https://github.com/eclipsesource/play-json-schema-validator/issues/48

Is there sth else I should check?

**Comment by erosb** [comment]
Have you read the [classpath section](https://github.com/everit-org/json-schema/#loading-from-the-classpath) of the manual?

**Comment by HungUnicorn** [comment]
it works after using classpath. thank you!

**Comment by ttiurani** [comment]
Sorry to barge in on a closed issue, but I can't for the life of me get this to work. At least in our Spring Boot `2.1.5` / Spring `5.1.7`, in a normal `@Controller` doing this:

```
    var inputStream = getClass().getResourceAsStream("classpath:///other/jar/file.schema.json");
```

returns null. It doesn't work with `classpath:other...` nor `classpath:/` nor `classpath://` This works:

```
    var inputStream = getClass().getResourceAsStream("/other/jar/file.schema.json");
```

But if I do that I get with the latest `master-SNAPSHOT`:

```
java.io.UncheckedIOException: java.io.IOException: Could not find classpath:///other/jar/subfile.schema.json
        at org.everit.json.schema.loader.ClassPathAwareSchemaClient.get(ClassPathAwareSchemaClient.java:30)
 ```

or with 1.12.0:

```
java.io.UncheckedIOException: java.net.MalformedURLException: unknown protocol: classpath
```

with a reference in the original schema like `"$ref":"classpath:///other/jar/subfile.schema.json#/definitions/MyDefinition"`.

Did you @HungUnicorn do something else to get around this problem?

**Comment by ttiurani** [comment]
I'm starting to feel there's something the matter with 

https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/loader/ClassPathAwareSchemaClient.java#L43

but can't really debug this because 

https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/loader/ClassPathAwareSchemaClient.java#L43

isn't like this:

```
throw new UncheckedIOException(new IOException(String.format("Could not find %s from %s", url, maybeString.get())));
```

which would print what exactly it is searching from `getResourceAsString`.

I tried cloning this repository and using maven to build it, but tests don't pass, and it doesn't produce usable artifacts. @erosb

**Comment by erosb** [comment]
Just built the head revision (6ed2cc4010cca97bc0cb17037a0e24dcdad95941) with `mvn clean install` and it built locally. What error do you get?

**Comment by ttiurani** [comment]
```
# java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode, sharing)
```

`mvn clean install` has lots of problems like:

```
[ERROR] Failures:
[ERROR]   JsonObjectTest.testRequireWithConsumerFailure
Expected: (an instance of org.everit.json.schema.SchemaException and exception with message a string containing "#: required key [aaa] not found")
     but: an instance of org.everit.json.schema.SchemaException <java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.creation.instance.InstantiatorProvider> is a java.lang.NoClassDefFoundError
Stacktrace was: java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.creation.instance.InstantiatorProvider
...
```

```
Tests run: 755, Failures: 1, Errors: 73, Skipped: 4
```

**Comment by erosb** [comment]
Strange. It looks [ok on CI](https://travis-ci.org/everit-org/json-schema), and it also builds successfully for me locally, with the very same java version you use (on linux, for that matter). Can you find any clues in the stacktrace?

**Comment by ttiurani** [comment]
I put the entire stacktrace there. I'm on OSX myself, but I've had odd classpath problems with Hemcrest too.

But if I do `mvn clean install -DskipTests=true`, which passes, and then try to use `0.0.0-develop`  as version, I can't get that to work. Which is really odd, but haven't ever used that 

`<packaging>bundle</packaging>`

which maybe has to do with something. How do I locally make that `master-SNAPSHOT` version that jitpack builds?

**Comment by erosb** [comment]
The `bundle` packaging is about the same as `jar` except it also adds some OSGi-specific headers to the `MANIFEST.MF`, so I doubt if that can cause any problems.
I don't exactly understand the question regarding jitpack. If you specify a commit hash in the `version` tag then jitpack checks out that revision, builds it as a maven artifact and serves it for you from its repository.

**Comment by ttiurani** [comment]
It was actually under a different groupId, the local build is under `org.everit.json` whereas the main README.md says `<groupId>com.github.everit-org.json-schema</groupId>`

After the above log addition, I got this:

```
java.io.UncheckedIOException: java.io.IOException: Could not find classpath:///other/jar/subfile.schema.json from //other/jar/subfile.schema.json
```

So that fails with the double `//` in the beginning.

**Comment by erosb** [comment]
That's right, when you build it locally then the  `groupId` is different from the one you use for installing through jitpack.

I don't clearly see yet what the problem is. Is it a regression?

**Comment by ttiurani** [comment]
I believe that `///` turning into `//` is not what you'd want. Because `classpath://`looks like a typical protocol prefix, having the extra `/` to be the first character is natural. That's how `file:///home...` works.

So I'd say there is an off-by one there with your code.

**Comment by ttiurani** [comment]
Also this is a completely wrong place for this, but my JSON schemas look like this:

```
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/MyDefinition",
  "definitions": {
    "MyDefinition": {
      "required": [
        "myKey"
      ],
      "properties": {
        "myKey": {
          "type": "string"
        }
      }
    }
  }
}
```

and that kind of thing doesn't seem to work at all with this library. Am I doing something unorthodox with these? I want multiple definitions in one file, otherwise things get totally unmanageable.

**Comment by ttiurani** [comment]
@erosb the problem was that I put a String to `schema.validate()`, and the error looked to me like it was about schema validation of the first key of the payload, and not the error of a parameter of the function. Not having type-safety in that function is problematic, and an error message like `Schema.validate() requires JSONObject as parameter but got String` would have saved me an hour.

But thanks a lot for your help, and thank you for your work on what seems like an super useful project!

**Comment by erosb** [comment]
The problem is that it isn't always a `JSONObject`. It can also be a string, and should pass the validation against a schema like `{"type":"string"}`. Same for boolean and numbers.
