### ISSUE TITLE
JSON schema exception location is invalid when the referred schema is not wellformed

### ISSUE THREAD

**Issue by octavianN** [everit-org/json-schema#298]
If I have a main schema, and a reference to other schema ("sch_person.json") that has errors, the schema error location is not set correctly.
There are two cases: 
- if the referred schema is not wellformed (a comma is missing as in the example below), the SchemaException location will be the entire JSON document. This is because in the "JsonPointerEvaluator.executeWith(SchemaClient, String)" the entire JSON object is se as location  see "new SchemaException("failed to parse " + resp, e)".
-  if the referred schema is wellformed (I add the missing comma for "sch_person.json"), the SchemaException location will be "sch_person.json/type". That is not a valid JSONPointer, the "#" character is missing, The problem is that the reference is "sch_person.json" instead of "sch_person.json#", but the validation works fine with or without "#" in the reference. Therefore, I think the JSONPointer from SchemaException  should be created correctly, with "#".

Main Schema 
```
{
   "$schema": "http://json-schema.org/draft-04/schema",
   "title": "Schema title",
   "description": "Description of the schema",
   "type": "object",
   "properties": {
       "id":"number",
       "name": {"type":"string"},
       "employees": {
           "type":"array",
           "items": {"$ref":"sch_person.json"}
       }
   }
}
```
sch_person.json
 ```
{
  "$schema": "http://json-schema.org/draft-06/schema#"
  "definitions": {
    "person": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "children": {
          "type": "array",
          "items": { "$ref": "#/definitions/person" },
          "default": []
        }
      }
    }
  },
  "type": "objects",
  "properties": {
    "person": { "$ref": "#/definitions/person" }
  }
}
```

**Comment by erosb** [comment]
Hi! To determine any paths the library first has to parse the json. As a consequence if the json is unparseable then no tree structure is built and no path can be deduced. Closing, this unfortunately won't be fixed.

**Comment by octavianN** [comment]
Hi,
What I suggest is that instead of setting the entire JSON document as location to set the URL of the document as location. Therefore, in the method "JsonPointerEvaluator.executeWith(SchemaClient, String)"  instead of "new SchemaException("failed to parse " + resp, e)", use "new SchemaException(url, e)". In this way you will have the url of the document as location and it is better. 

For the second problem, when "#" is missing, would be great if you could add "#" in the location path from the SchemaException. I didn't analize very well how you can do this but if I will get to a conclusion I will tell you.
