### ISSUE TITLE
Get the complete schema including the subschemas without any $ref

### ISSUE THREAD

**Issue by HungUnicorn** [everit-org/json-schema#299]
I found the $ref part are in subschemas. Is there a way to get a string representation of the complete schema, and all $ref are replaced by subschemas?

**Comment by erosb** [comment]
Hello, this library's public interface doesn't support $ref resolutions. For users with such requirement I usually recommend trying out this library: https://github.com/AndersDJohnson/jackson-json-reference

**Comment by HungUnicorn** [comment]
thank for you suggesting a library. I mean I can see the subschemas in `org.everit.json.schema` which are in $ref, and then can replace $ref with subschemas to get the complete schema. It's not one call but wouldn't it be useful to have a method `getCompleteSchemaWithRefReplaced()`? One use case is for transforming json schema to other schema that does not support $ref (e.g. Avro), and providing a complete schema would be very useful

**Comment by erosb** [comment]
It _would_ make sense to implement a schema rewriter which eliminates `$ref` indirections, but it isn't currently an implemented feature and I can't promise anything about if/when it will be available.

**Comment by HungUnicorn** [comment]
I see. thank you for the feedback
