### ISSUE TITLE
Version 1.11.1 is not handling patternProperties correctly

### ISSUE THREAD

**Issue by nnanda2016** [everit-org/json-schema#304]
Everit version: 1.11.1
Issue1: `ObjectSchema.getPatternProperties()` is deprecated, but no alternate method has been suggested. This is really bad documentation.

Issue2: This method gives non-null value only if the pattern properties is used for top most level object, if this property is used for some nested object node, this method returns an empty map.

E.g. 
**`Case-1`** `patternProperties` is used for top most level object
```json
{
   "title":"feeds",
   "description":"Feeds user subscribes to",
   "type":"object",
   "patternProperties":{
      "^[A-Za-z]+$":{
         "type":"boolean"
      }
   }
}
```
For this JSON, `objectSchema.getPatternProperties()` returns `{^[A-Za-z]+$={"type":"boolean"}}`

**`Case-2`** `patternProperties` is used for nested object
```json
{
   "title":"pattern-proerties-demo-2",
   "description":"Feeds user subscribes to",
   "type":"object",
   "properties":{
      "firstName":{
         "type":"string"
      },
      "lastUpdatedDate":{
         "type":"string",
         "pattern":"yyyy-MM-dd HH:mm:ss",
         "description":"When was the last time the doc was updated"
      },
      "address": {
      	"type":"object",
      	"patternProperties": {
      		"^[A-Za-z]+$": {
      			"type": "string"
      		}
      	}
      }
   }
}
```
For this JSON, `objectSchema.getPatternProperties()` returns `{}`

For our system we need to validate this. Which API should we use?

**Comment by erosb** [comment]
Hello, in the second case `objectSchema.getPropertySchemas().get("address").getPatternProperties()` will return the single-item map you are looking for (you have to traverse the schema to reach the child-schema you are looking for). 

`getPatternProperties()` is deprecated but it is supported. You can also use `getRegexpPatternProperties()` in which the key is an `org.everit.json.schema.Regexp` instance and not a `java.util.regex.Pattern`. The `Regexp` class was introduced some versions ago when we started supporting multiple regular expression implementations.

**Comment by octavianN** [comment]
The "getRegexpPatternProperties()" is a package private method. Maybe should be public.
