### ISSUE TITLE
Validate enum exception  （is not a valid enum value）

### ISSUE THREAD

**Issue by haoweijia** [everit-org/json-schema#305]
I use the following json file and json schema.
Json:

> {
	"intervals": [{
		"start": "2019-05-20T00:00:00.000+08:00",
		"end": "2019-05-25T00:00:00.000+08:00"
	}, {
		"start": "2019-06-20T00:00:00.000+08:00",
		"end": "2019-06-30T00:00:00.000+08:00"
	}],
	"sets": [{
		"identity": "set1",
		"filterOperator": "OR",
		"filters": [{
			"value": {
				"expression": "beijing",
				"operator": "EQUAL"
			},
			"dimension": "city"
		}, {
			"value": {
				"expression": "xiaoming",
				"operator": "EQUAL"
			},
			"dimension": "name"
		}]
	}, {
		"identity": "set2",
		"filterOperator": "AND",
		"filters": [{
			"value": {
				"expression": "haoweijia",
				"operator": "EQUAL"
			},
			"dimension": "name"
		}, {
			"value": {
				"expression": "18",
				"operator": "EQUAL"
			},
			"dimension": "age"
		}]
	}],
	"computations": [{
		"input": ["set1", "set2"],
		"identity": "set3",
		"setOperator": "UNION"
	}],
	"domain": "domain1",
	"resultType": "INDEX"
}

json schema

> {
  "description": "Index Service Query Language",
  "title": "ISQuery",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "domain": {
      "type": "string"
    },
    "intervals": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/interval"
      }
    },
    "sets": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/set"
      }
    },
    "computations": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/computation"
      }
    },
    "resultType": {
      "$ref": "#/definitions/resultTypeEnum"
    }
  },
  "definitions": {
    "interval": {
      "type": "object",
      "properties": {
        "start": {
          "type": "string"
        },
        "end": {
          "type": "string"
        }
      }
    },
    "constraintOperatorEnum": {
      "enum": [
        "equal",
        "greaterThan",
        "lessThan",
        "greaterThanOrEqual",
        "lessThanOrEqual",
        "range",
        "like",
        "in"
      ]
    },
    "filter": {
      "type": "object",
      "properties": {
        "dimension": {
          "type": "string"
        },
        "value": {
          "type": "object",
          "properties": {
            "operator": {
              "$ref": "#/definitions/constraintOperatorEnum"
            },
            "expression": {
              "type": "string",
              "description": "A regular expression for pattern.",
              "examples": [
                "^.*"
              ]
            }
          }
        }
      }
    },
    "filterOperatorEnum": {
      "enum": [
        "AND",
        "OR"
      ]
    },
    "set": {
      "type": "object",
      "properties": {
        "identity": {
          "type": "string"
        },
        "filters": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/filter"
          }
        },
        "filterOperator": {
          "$ref": "#/definitions/filterOperatorEnum"
        }
      }
    },
    "setOperatorEnum": {
      "enum": [
        "INTERSECTION",
        "UNION",
        "DIFFERENCE",
        "COMPLEMENT"
      ]
    },
    "computation": {
      "type": "object",
      "properties": {
        "identity": {
          "type": "string"
        },
        "setOperator": {
          "$ref": "#/definitions/setOperatorEnum"
        },
        "input": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "resultTypeEnum": {
      "enum": [
        "INDEX",
        "COUNT",
        "ID_LIST"
      ]
    }
  },
  "requires": [
    "domain",
    "intervals",
    "sets",
    "computations",
    "resultType"
  ]
}

code:
`
        JSONObject jsonObject = new JSONObject(isql);

        System.out.println(jsonObject.toString());
        System.out.println();
        System.out.println("---------------------------------------");
        System.out.println();
        InputStream inputStream = ValidationServiceTest.class.getResourceAsStream("/ISQL/ISQL.json");
        JSONTokener jsonTokener = new JSONTokener(inputStream);
        JSONObject rawSchema = new JSONObject(jsonTokener);
        System.out.println(rawSchema.toString());

        Schema schema = SchemaLoader.builder().schemaJson(rawSchema).draftV6Support().build().load().build();

        try{
            schema.validate(jsonObject);
        }catch (ValidationException e){
            System.out.println(e.getErrorMessage());
            System.out.println(e.getMessage());
            List<String> list = e.getAllMessages();
            for(String str : list){
                System.out.println(str);
            }
        }`
exception:

> 8 schema violations found
#: 8 schema violations found
#/computations/0/setOperator: UNION is not a valid enum value
#/resultType: INDEX is not a valid enum value
#/sets/0/filterOperator: OR is not a valid enum value
#/sets/0/filters/0/value/operator: equal is not a valid enum value
#/sets/0/filters/1/value/operator: equal is not a valid enum value
#/sets/1/filterOperator: AND is not a valid enum value
#/sets/1/filters/0/value/operator: equal is not a valid enum value
#/sets/1/filters/1/value/operator: equal is not a valid enum value

**Comment by erosb** [comment]
Hi, what is the question here?
Also please provide a minimal example reproducing the problem, if possible, and also format the json. Thanks.
