### ISSUE TITLE
Pattern is not working as for my requirement.

### ISSUE THREAD

**Issue by ramanjaneyuluMadasu** [everit-org/json-schema#311]
Below code i am using 

JSONObject rawSchema = new JSONObject(new JSONTokener(jsonSchema));
SchemaLoader.load(rawSchema).validate(new JSONObject(jsonString));

"pattern":"[A-Z0-9a-z]*"
jsonstring :{"name" : "@@@####"}

**Comment by erosb** [comment]
Hello, please create a PR with a failing test reproducing your problem, as described in the [contribution guideline](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md), thanks.

**Comment by ramanjaneyuluMadasu** [comment]
Problem was solved.Solution is "pattern":"^[A-Z0-9a-z]*$"
