### ISSUE TITLE
Authentication with token for $ref

### ISSUE THREAD

**Issue by Raphael-Bahuau** [everit-org/json-schema#313]
Hello,

I want to validate a schema in Karate for validation tests but I need to authenticate some $ref http.
Actually I get a 401 when I try to validate.
Maybe I miss something in documentation, I think URI is almost all I want but I'm not sure because the word "authentication" doesn't appear.

Is there a way to setup a header for each $ref nested my schemas ?

Thanks.

**Comment by erosb** [comment]
Hi! The library doesn't have support explicitly for authentication, but you can make it work by
 * implementing a custom `SchemaClient` which adds the necessary authentication header
 * and configure the schema loader to use this client ( `SchemaLoaderBuilder#schemaClient(new YourSchemaClient())` )

Let me know if you get stuck.

**Comment by Raphael-Bahuau** [comment]
Thank, I see there now : https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/loader/SchemaLoader.java#L295
`public static Schema load(final JSONObject schemaJson, final SchemaClient schemaClient) { ... }`

I'm a noobie in httpClient in Java, I already have this function, and I comment my approach, what do you think about that ?
```
// Create a static custom SchemaClient ready to handle a token

public static boolean isValid(String jsonString, String schemaString, String token) throws Exception {
        try {
            JSONObject rawJson = new JSONObject(jsonString);
            JSONObject rawSchema = new JSONObject(new JSONTokener(schemaString));
            
            // There update the token in custom SchemaClient
            
            // And add the variable schemaClient to this function call (seen in the above link)
            Schema schema = SchemaLoader.load(rawSchema);
            schema.validate(rawJson);
            return true;
        } catch (ValidationException e) { ... }
```

**Comment by erosb** [comment]
Hi!
If you take a look at the DefaultSchemaClient you can see that the HTTP request is essentially sent in a one-liner: https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/loader/internal/DefaultSchemaClient.java

You will have to implement a similar SchemaClient, but also send the HTTP basic authentication header. In [this StackOverflow answer](https://stackoverflow.com/a/5137446/3692110) you can see how to do that. I think it will be something like (not tested):
```java
public class YourSchemaClient implements SchemaClient {

    @Override
    public InputStream get(final String url) {
        try {
            URL u = new URL(url);
            URLConnection uc = u.openConnection();
            String userpass = username + ":" + password;
            String basicAuth = "Basic " + new String(Base64.getEncoder().encode(userpass.getBytes()));
            uc.setRequestProperty ("Authorization", basicAuth);
            return (InputStream) u.getContent();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

}
```

Regarding setting up your custom SchemaClient, I recommend doing this way (not tested, just from the top of my head):
```java
JSONObject rawJson = new JSONObject(jsonString);
JSONObject rawSchema = new JSONObject(new JSONTokener(schemaString));
Schemaloader loader = SchemaLoader.builder()
    .schemaJson(rawSchema)
    .schemaClient(new YourSchemaClient())
    .build();
Schema schema = loader.load().build();
schema.validate(rawJson);
return true;
```

**Comment by Raphael-Bahuau** [comment]
So I write your class example (but for a bearer token, anyway).
But the error 401 still appear, so I read the doc of URLConnection and I think the return may be like that :
`return uc.getInputStream();`

So the final class is
```
public class CustomSchemaClient implements SchemaClient {

        String token;

        CustomSchemaClient(String token) {
            this.token = token;
        }

        @Override
        public InputStream get(final String url) {
            try {
                URL u = new URL(url);
                URLConnection uc = u.openConnection();
                uc.setRequestProperty("Authorization", this.token);
                return uc.getInputStream();
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        }
    }
```

And it's finally working :+1:  !
Maybe later I make it static to only change `this.token` on each call (avoid to instanciate on each schema validation).

Thank's for your quickly responses :smile:

**Comment by erosb** [comment]
:+1:
