### ISSUE TITLE
Misleading error message for negative test cases using if then else contruct

### ISSUE THREAD

**Issue by santiagos11** [everit-org/json-schema#314]
**Schema**

`{
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "http://example.com/product.schema.json",
        "title": "Product",
        "description": "A product from Acme's catalog",
        "type": "object",
        "properties": {
            "state": {
                "type": "string"
            },
            "country": {
                "type": "string"
            }
        }
        "required": [
            "country"
        ],
        "if": {
            "properties": {
                "country": {
                    "const": "USA"
                }
            }
        },
        "then": {
            "properties": {
                "state": {
                    "not": {
                        "const": ""
                    }
                }
            },
            "required": [
                "state"
            ]
        },
        "else": {
            "properties": {
                "state": {
                    "const": ""
                }
            }
        }
    }`

**Input**

`{
        "country": "Canada",
        "state": "FL"
    }`

The error message says that both the country and state are fields in error message, when in fact the only field that is in error is the state field:

Field | Error Message(s)
-- | --
#/country | 1.
#/state | 1.

**Comment by erosb** [comment]
Hello @santiagos11 ,

can you please create a PR with a failing test for this, as described in the [contribution guideline](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md) ?

Thanks.
