### ISSUE TITLE
Add support for multiple comments in the same object definition.

### ISSUE THREAD

**Issue by SomeDeveloper13** [everit-org/json-schema#317]
Currently if you want to properly comment your schema, you are relegated to a single $comment field per object/field definition.

This means that if you don't have the ability to replace sections of fields w/ new objects, you are relegated to either removing the comments, or moving them to places that don't really make sense.

See `"$comment": "Part 1"` and `"$comment": "Part 2"` in the example of what I would like to be able to do.

### What I would like to be able to do:
```
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "TBD",
	"title": "TBD",
	"description": "TBD",
	"type": "object",
	"properties": {
		"Form Object": {
			"description": "TBD",
			"type": "object",
			"properties": {
				"FormId": {
					"description": "Form ID",
					"type": "string"
				},
				"$comment": "Part 1",
				"P1Q1": {
					"description": "Field Desc",
					"$ref": "#/definitions/Y_Empty"
				},
				"P1Q2": {
					"description": "Field Desc",
					"$ref": "#/definitions/Y_Empty"
				},
				"$comment": "Part 2",
				"P2Q1": {
					"description": "Field Desc",
					"$ref": "#/definitions/Y_Empty"
				},
				"P2Q2": {
					"description":"Field Desc",
					"$ref": "#/definitions/Y_Empty"
				}
			},
			"$comment": "restricting instance of the object to only those defined in this sub schema",
			"additionalProperties": false
		}
	},
	"$comment": "Restricting instance properties to those defined in the schema",
	"additionalProperties": false,
	"definitions": {
		"Y_Empty": {
			"description": "",
			"type": "string",
			"enum": ["Y", ""]
		}
	}
}
```

**Comment by erosb** [comment]
Hello, 

the schema document should be valid JSON, and according to JSON, an object's keys should be unique, so you can't have two "$comment" keys at the same nesting level.

You can raise this at the [underlying JSON library](https://github.com/stleary/JSON-java/) but I doubt if this feature request will receive any positive feedback.

**Comment by SomeDeveloper13** [comment]
What about allowing a pattern like "$comment1", "$comment2", "$commenta", "$commentb", etc.?
We tried to use it this way, but got an error about the string not being a valid Object.

**Comment by erosb** [comment]
That should be related to something else. This library doesn't care at all about `$comment...` keys, they should all reside in the `Schema#getUnprocessedProperties()` map.
