### ISSUE TITLE
ValidationException mutates List produced by Collectors.toList()

### ISSUE THREAD

**Issue by slisaasquatch** [everit-org/json-schema#319]
The code I'm talking about is [this](https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/ValidationException.java#L27).

I know realistically `toList()` produces an `ArrayList`, which is mutable, but the Javadoc for `toList` says `There are no guarantees on the type, mutability, serializability, or thread-safety of the {@code List} returned`. The easy fix would be replacing the first `Collectors.toList()` with `Collectors.toCollection(ArrayList::new)`.

**Comment by erosb** [comment]
Thanks for reporting this. Fixed in 95d2f990c8eaee0c110f649e2ab39bb0b960b574 , will be included in the next release.
