### ISSUE TITLE
$id field is not being preserved

### ISSUE THREAD

**Issue by snaum** [everit-org/json-schema#327]
"$id" field in the schema is being converted to "id".
This is a side effect that is not expected and not documented.

IMO, schema.toString() should use the version to determine whether to print "id" or "$id"
Please see the below unit test to reproduce.

` 

public void testPreserveID(){
		final JSONObject validSchema1JSON = new JSONObject(validSchema1);
		SchemaLoader loader = SchemaLoader.builder().schemaJson(validSchema1JSON).draftV7Support().build();
		Schema schema = loader.load().build();

		JSONObject resultSchemaJSON = new JSONObject(schema.toString());
		JSONObject originalSchemaJSON = new JSONObject(validSchema1);

		assertEquals(originalSchemaJSON.get("$id"),resultSchemaJSON.get("id"));
	} 

`

**Comment by erosb** [comment]
Hello @snaum currently the in-memory `Schema` objects don't track the draft version based on which they were created. I will think about options to overcome this. Thank you for reporting the problem.

**Comment by erosb** [comment]
This is now fixed and released in version `1.12.0`.
