### ISSUE TITLE
Could not initialize class "SpecificationVersion" being used as a third-party library in ReadyAPI

### ISSUE THREAD

**Issue by vmm86** [everit-org/json-schema#328]
I'm using `org.everit.json.schema-1.11.1.jar` as a third-party library in [ReadyAPI](https://smartbear.com/product/ready-api/overview/) application to test API endpoints and validate JSON requests/responses by JSON schemas obtained from given URLs inside the Groovy script. Jar file is loaded from application's `bin/ext` directory along with some other additional libs.

There is a sample Groovy script to test validation process:

```groovy
import kong.unirest.Unirest

import org.everit.json.schema.loader.SchemaLoader
import org.everit.json.schema.Schema

import org.json.JSONObject
import org.json.JSONTokener

String schemaUrl = "http://domain.com/path/to/schema.json"
JSONObject schemaJson = Unirest.get(schemaUrl).header("content-type", "application/json").header("accept", "application/json").asJson().getBody().getObject()
log.info(schemaJson.class.name + " " + schemaJson)

JSONObject request = new JSONObject(new JSONTokener(context.rawRequest as String))
log.info(request.class.name + " " + request)

SchemaLoader loader = SchemaLoader.builder().schemaJson(schemaJson).draftV6Support().build()
Schema schema = loader.load().build()
schema.validate(request.get("params")) // context.rawRequest
```
`schemaJson ` and `request ` are fine - logging shows the correct JSON objects.

But when I try to get the schema instance on `SchemaLoader loader...` line, the following error occurs: `java.lang.NoClassDefFoundError: Could not initialize class org.everit.json.schema.loader.SpecificationVersion`. It seem to be close to #103.

**Comment by erosb** [comment]
Hello, can you please check if there is other dependency in the project which uses an older version (not 1.11.1) of the library? What is the output of `mvn dependency:tree` ?

**Comment by vmm86** [comment]
> Hello, can you please check if there is other dependency in the project which uses an older version (not 1.11.1) of the library? What is the output of `mvn dependency:tree`?

It's not the Maven or Gradle software project. I "plug" Everit json-schema jar file to ReadyAPI software as an external lib, and then import its classes in Groovy script test step to use it for JSON data validation.

I've found the reason by myself reading ReadyAPI error log file. It was the missing dependency of Everit json-schema itself - `com.damnhandy:handy-uri-templates`.
