### ISSUE TITLE
Draft 8 now known as Draft 2019-09 Released

### ISSUE THREAD

**Issue by Stexxen** [everit-org/json-schema#329]
Looks like its finally released
http://json-schema.org/specification-links.html#2019-09-formerly-known-as-draft-8

Unfortunately to my unexperienced eyes it looks like the changelogs have a quite a few changes.
https://tools.ietf.org/html/draft-handrews-json-schema-02#appendix-G
and
https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#appendix-C

**Comment by erosb** [comment]
Yes, it is a big change, probably it makes more sense to re-read the spec instead of just going through the changelog. Also I'm not sure if draft2019-9 will fit into the API of this library, since they reworked the core terminology. Maybe it will need a BC-breaking release.

**Comment by mst-avaleo** [comment]
Any plans to release support for draft 2019-09?

**Comment by luposlip** [comment]
@erosb I see you have a branch for support of 2019-09. How close is that to a release?

**Comment by erosb** [comment]
Hello @luposlip , sometimes @zgyorffi is working on it, but it isn't under continuous development, so I can't say any ETA. I barely have any time for this project nowadays. Contributions are always welcome though.

**Comment by erosb** [comment]
Hello @Stexxen @luposlip  @mst-avaleo, recently I [released a new validator library](https://github.com/erosb/json-sKema) that supports draft2020-12 version of json schema. Closing this issue, the everit-org/json-schema library won't see any major updates in the future.

**Comment by luposlip** [comment]
Alright @erosb - I'll checkout how easy it is to port code from json-schema to json-sKema.
