### ISSUE TITLE
1.11.1 on repo.spring.io unauthorized

### ISSUE THREAD

**Issue by Gabrinthei** [everit-org/json-schema#330]
Seems the latest publish to repo.spring.io is locked down
For example https://repo.spring.io/plugins-release/com/github/everit-org/json-schema/org.everit.json.schema/1.11.1/org.everit.json.schema-1.11.1.pom

**Comment by erosb** [comment]
Hello @Gabrinthei , please install the latest version from [jitpack](https://github.com/everit-org/json-schema#maven-installation). The spring repo is not an official distribution channel for this library (actually I didn't even know that it is uploaded there..)

**Comment by Gabrinthei** [comment]
Hi! Yeah, I've been trying to get my project to use jitpack, the issue being that it tries spring first and apparently won't fallback to jitpack when it runs into a 401. Is it possible to remove it completely from spring repo? That would fix a lot of headaches

**Comment by erosb** [comment]
You need to ask the spring team about it.
