### ISSUE TITLE
"multipleOf" attribute in json schema doesn't work

### ISSUE THREAD

**Issue by jain20ankit** [everit-org/json-schema#335]
I am trying to define a form field to accept decimal values. For that i am using the "multipleOf" property but it's not working. For 
Case 1 > If i give value as 2.5 then it gives error saying "**Invalid value, Possible nearest values are 2 and 3**" and for 
Case 2 > If i enter 3, it doesn't give any error and submits the form. However all other properties including (minimum,maximum) works

//**Case 1: Json Schema for Decimal field**
"myElement": {
                "maximum": 1000.0,
                "minimum": 0.0,
                "type": "number",
                **"multipleOf" : 0.5**
            }
//**Case 2: Json Schema for Integer value (Even number)**
"myElement": {
                "maximum": 1000.0,
                "minimum": 0.0,
                "type": "number",
                **"multipleOf" : 2**
            }

**Comment by erosb** [comment]
> it gives error saying "Invalid value, Possible nearest values are 2 and 3"

You are most probably at the wrong github project. This library doesn't return errors like this.

**Comment by jain20ankit** [comment]
Following is my gradle entry  
**compile('com.github.everit-org.json-schema:org.everit.json.schema:1.12.0')**
And below is the exact error, I am getting
![image](https://user-images.githubusercontent.com/20131108/67718641-8901e180-f9a6-11e9-93f3-a58f5e8e2b69.png)

**Comment by jain20ankit** [comment]
Hi Erosb, Thanks for quick reply. I have corrected my comment and attached the exact error message screen shot, Please let me know if you want me to open a new issue.

**Comment by erosb** [comment]
@jain20ankit it should be an other library, or an intermediate layer between the UI and this library. Can you please check your import statements? The word "nearest" simply doesn't occur anywhere in the codebase of this validator (just checked).
