### ISSUE TITLE
NoSuchMethodException when trying the example

### ISSUE THREAD

**Issue by Hentra** [everit-org/json-schema#337]
When i tried this (like in the example):

        try(InputStream stream = getClass().getResourceAsStream("schemes/questiondefinition.json")) {
            JSONObject rawSchema = new JSONObject(new JSONTokener(stream));
            Schema schema = SchemaLoader.load(rawSchema);
            schema.validate(new JSONObject(json));
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ValidationException e) {
            System.out.println(e.getMessage());
            e.getCausingExceptions().stream()
                    .map(ValidationException::getMessage)
                    .forEach(System.out::println);
        }

I got this:

    Exception in thread "main" java.lang.NoSuchMethodError: 'void org.json.JSONTokener.<init>(java.io.InputStream)'
        at parser.ConfigurationValidator.validate(ConfigurationValidator.java:17)
        at command.CheckCommand.execute(CheckCommand.java:21)
        at startup.Startup.main(Startup.java:30)

I added the library through gradle like this: 

```
repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation 'commons-cli:commons-cli:1.4'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.github.everit-org:json-schema:1.12.0'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
}
```

**Comment by erosb** [comment]
Hello, this looks like a dependency conflict, please check the version of the org.json library on the classpath.
