### ISSUE TITLE
allOf along with nested if is not working

### ISSUE THREAD

**Issue by pranee513** [everit-org/json-schema#339]
I'm trying wrap nested if else conditions inside the **allof** at root level schema and I'm using **draft7** schema version .I've noticed that my conditions never evaluated due to sub-schema arrays are always empty.I am using a simple address example posted on [json-org](https://json-schema.org/understanding-json-schema/reference/conditionals.html)

Please refer to my question posted on [stackOverflow](https://stackoverflow.com/questions/58864528/jsonschema-validation-using-allof-and-complex-if-else)

![st-q](https://user-images.githubusercontent.com/18104988/69070419-1bb9fd00-09f6-11ea-975d-c2ed20feb240.PNG)

**Comment by erosb** [comment]
Hello, please raise a PR with a failing test reproducing the problem (see the [contributing guidelines](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md) ). Thanks.
