### ISSUE TITLE
Performance problem when validating 

### ISSUE THREAD

**Issue by octavianN** [everit-org/json-schema#341]
If I validate the following instance with the HL7 JSON Schema, the validation never finish.

You can find the HL7 JSON Schema here: https://www.hl7.org/fhir/fhir.schema.json.zip
You can find the instance here:  [instance.zip](https://github.com/everit-org/json-schema/files/3868282/instance.zip)

To compile the JSON Schema it took 65 seconds. But I didn't manage to validate the instance with the schema.
Maybe this can help to detect performance problems.

**Comment by erosb** [comment]
Which version do you use @octavianN ?

**Comment by octavianN** [comment]
I tested with the latest version 1.12.0
