### ISSUE TITLE
Missing synthetic property getter in CombinedSchema

### ISSUE THREAD

**Issue by daniloarcidiacono** [everit-org/json-schema#342]
As per title.

**Comment by erosb** [comment]
For what reason do you need that getter? The synthetic property is for internal use.

**Comment by daniloarcidiacono** [comment]
I'm writing a post-processor which visits a Schema and builds a new one by using the builder classes. Most of the properties of the original schema are retained, including synthetic.

**Comment by erosb** [comment]
You probably won't need the synthetic flag for this purpose. 
I'd prefer not making this flag the part of the public API, because it is a quite unclear internal detail (actual a hacky solution to overcome an initial design issue with the library).

**Comment by daniloarcidiacono** [comment]
ok
