### ISSUE TITLE
Expect at least one of the properties to not have null in type string

### ISSUE THREAD

**Issue by xBentu** [everit-org/json-schema#343]
`"oneOf": [{
    "properties": {
      "property1": {
        "not": {
          "enum": [null]
        }
      }
    }
  },{
    "properties": {
      "property2": {
        "enum": [null]
      }
    }
  }, {
    "properties": {
      "property3": {
        "enum": [null]
      }
    }
  },{
    "properties": {
      "property4": {
        "enum": [null]
      }
    }
  }], "properties": {
    "property1": {
      "description": "description4",
      "type": "string"
    },
    "property2": {
      "description": "description3",
      "type": "string"
    },
    "property3": {
      "description": "description2",
      "type": "string"
    },
    "property4": {
      "description": "description1",
      "type": "string"
    }
}`

Expected result: pass if one of the properties has a string that is not null and fails if all of them are null.

Any help is appreciated, and let me know if you need further explanation.

**Comment by erosb** [comment]
Hello @xBentu , please submit a PR with a failing test, reproducing your problem, as described in the [contribution guideline](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md). Thanks.

**Comment by xBentu** [comment]
@erosb sure, I'll get to work on it asap.  In the mean time, can you explain the proper way to check that one of the properties is returning a string instead of a null.  Maybe I'm just not validating properly.

**Comment by xBentu** [comment]
Fixed the issue, it was on my part mostly due to inexperience.  I had a poorly formed schema to check against, and I was validating in a try/catch.  Once I fixed my schema and took the validation out of the try/catch it works as expected.

**Comment by erosb** [comment]
You will need to look into the `ValidationException#getCausingExceptions()` list. More details in the [investigating failures section of the readme](https://github.com/everit-org/json-schema#investigating-failures)

**Comment by xBentu** [comment]
@erosb thank you for the help.  For custom message I used this: 

`StringBuffer result = new StringBuffer("Validation against Json schema failed: \n");
    try {
      schema.validate(data);
    } catch (ValidationException ex) {
      ex.getAllMessages().stream().peek(e -> result.append("\n")).forEach(result::append);
      throw new AssertionError(result.toString());
    }`
which I found here: 
https://www.codota.com/code/java/methods/org.everit.json.schema.Schema/validate
