### ISSUE TITLE
org.everit.json.schema.NotSchema.toString throws JSONException for valid json *not* schemas

### ISSUE THREAD

**Issue by alin-t** [everit-org/json-schema#345]
When parsing a valid JSON schema, toString method of the returned object throws the following exception: JSONException("Misplaced key.")

```
{  
   "$schema":"http://json-schema.org/draft-04/schema#",
   "not":{  
      "type":"object",
      "properties":{  
         "name":{  
            "type":"string"
         }
      }
   }
}
```

There are cases when the *not* schema is parsed correctly and toString method works as intended:

```
{  
   "not":{  
      "type":"object",
      "properties":{  
         "name":{  
            "type":"string"
         }
      }
   }
}
```

and

```
{  
   "$schema":"http://json-schema.org/draft-04/schema#",
   "oneOf":[  
      {  
         "type":"number"
      }
   ],
   "not":{  
      "type":"object",
      "properties":{  
         "name":{  
            "type":"string"
         }
      }
   }
}
```

I briefly debug through the code and the problem could be with the ToStringVisitor.visitNotSchema and is possible that only mustNotMatch should be passed there. But I may be wrong.

**Comment by erosb** [comment]
Hello, thank you for reporting it, it is now fixed in 51915ddadce6030fa6ac96ae475bc26a6e46473f
