### ISSUE TITLE
Load schema never ends

### ISSUE THREAD

**Issue by octavianN** [everit-org/json-schema#348]
If I want to load the attached JSON Schema "ECV-JsonSchema-tNoBOM.json" to a schema validator, the loading never ends.
I tested with the latest release 1.12.0, using SchemaLoader.load(new JSONObject(schema)).

From what I proffiled it seems that the problem is in "ReferenceLookup.lookupObjById". I don't know very well the code, but the schema does not use IDs for referencing, and it should not stay in "lookupObjById".

[ECV-JsonSchema-tNoBOM.zip](https://github.com/everit-org/json-schema/files/3939552/ECV-JsonSchema-tNoBOM.zip)

**Comment by erosb** [comment]
Thanks for reporting it. The problem is fixed in version `1.12.1`. The schema loaded for me in less than 30 seconds now.
