### ISSUE TITLE
Example value is not supported

### ISSUE THREAD

**Issue by sreekesh93** [everit-org/json-schema#355]
Option to set examples for a field is missing. Is there any other alternative way to set example values?

**Comment by erosb** [comment]
In the current version we don't support `"examples"` explicitly, but you can use `Schema#unprocessedProperties` for this purpose, eg. 

```java
NumberSchema schema = NumberSchema.builder()
    // ...
    .unprocessedProperties(Map.of("examples", asList(2, 4, 6)))
    .build();
```
