### ISSUE TITLE
Unable to resolve json-schema validator using @Grapes(     @Grab(group='com.github.everit-org.json-schema', module='org.everit.json.schema', version='1.9.1') )

### ISSUE THREAD

**Issue by Suchismita1tutun** [everit-org/json-schema#358]

**Comment by erosb** [comment]
You should probably add the jitpack repository (`@GrabResolver(name='restlet', root='https://jitpack.io/')`)

**Comment by Suchismita1tutun** [comment]
Yeah I have added  @GrabResolver(name='itpack.io', root='https://jitpack.io') before this line, but still its failing to load the class , Error : "unable to resolve class org.everit.json.schema.loader.SchemaLoader"

**Comment by Suchismita1tutun** [comment]
Snapshot of the stack trace as below 
[download failed: com.github.everit-org.json-schema#org.everit.json.schema;1.9.1!org.everit.json.schema.jar, download failed:
org.json#json;20190722!json.jar(bundle), download failed: commons-validator#commons-validator;1.6!commons-validator.jar, download failed: commons-digester#commons-digester;1.8.1!commons-digester.jar]

**Comment by Suchismita1tutun** [comment]
This problem is resolved. There was a issue with security to download from mvn repository.
