### ISSUE TITLE
maven central 

### ISSUE THREAD

**Issue by listaction** [everit-org/json-schema#360]
could you please use maven as the repo in addition to jitpack ? we use use maven as the parent.

**Comment by erosb** [comment]
Hell, I do deploy to maven central, though it isn't a primary distribution channel:

```xml

        <dependency>
            <groupId>com.github.erosb</groupId>
            <artifactId>everit-json-schema</artifactId>
            <version>1.12.1</version>
        </dependency>
```

**Comment by mvanini** [comment]
Hi @erosb, could you consider to directly publish this project on maven-central against the forked https://github.com/erosb/everit-json-schema?
