### ISSUE TITLE
Validate part of a document against part of a schema

### ISSUE THREAD

**Issue by zendril** [everit-org/json-schema#361]
If I have a full schema which uses references to a `#/definitions/` section at the bottom of the schema, in order to validate many different sub-parts of the document I have to mock up a FULL document with 1 or 2 minor changes to validate just that subschema.

Is there a way to pass in a partial document and validate with a subschema located in `#/definitions/` ?

**Comment by erosb** [comment]
Hello,

that is not a supported usecase. I think the safest thing you can do is extracting the necessary parts of your schema JSON into a separate JSONObject and try loading that.

One more thing you may attempt is:
 - create a `SchemaLoaderBuilder` instance
 - set its `schemaJson` to the subschema you want to load
 - via reflection, set its `rootScemaJson` to the root document
 - build & load the schema

This is quite hacky, and not sure if it works, and relies on an internal API, therefore it may break in a minor release, etc. I suggest sticking to the first approach (transforming the schema json), if that works.

**Comment by zendril** [comment]
Thanks for the response. 

I found a way to do what I need.. somewhat hacky I guess and essentially is transforming the schema json (or crafting a new one dynamically out of the parts I need)

In code I'm read the subschema (the definitions section) and dynamically add it as the value where the key is `properties`, i also add in `type: object`

That allows me to then validate a partial json (or yml in my case) against just the items in the definition.. and the `$refs` work just fine.

I'll close this as you said, it isn't  really a standard use case.
