### ISSUE TITLE
Cannot load the vega-lite json schema

### ISSUE THREAD

**Issue by cnuernber** [everit-org/json-schema#363]
We are trying to validate vega-lite json data using everit's json schema parser.

For reference, the vega-lite json schema is here:
https://vega.github.io/schema/vega-lite/v2.json

The failure in particular is:
```console
Execution error (URISyntaxException) at java.net.URI$Parser/fail (URI.java:2848).
Illegal character in fragment at index 18: #/definitions/Dict<InlineDataset>
```

I am not sure who exactly is in the wrong here.  The above is definitely not a valid url fragment.  But it would be possible to use some simpler concatenation system and the use URI's when that system fails.  I don't know how many other json schemas use invalid fragments like that.

**Comment by erosb** [comment]
Hello,
I think it would be better to pre-process the schema json and escape the invalid characters, than trying to hack this into the library.

**Comment by cnuernber** [comment]
I agree.  Closing.
