### ISSUE TITLE
Allow option to return line and column location for validation failures

### ISSUE THREAD

**Issue by costas80** [everit-org/json-schema#369]
It would be great if the API would allow me to retrieve instead of JSON Pointers for errors, the line and column location from the offending content. Is this feasible to support?

**Comment by erosb** [comment]
It was requested a few times already. Although I agree it would be useful, it isn't easy to implement. The parsing is done by the underlying org.json library which doesn't retain source information. So I think it can only be implemented if we ship a custom json parser (not much chance for that any time soon). The json pointers were added to work this problem around. I know it isn't an ideal solution.

**Comment by costas80** [comment]
Thanks for the quick reaction @erosb . Checking other Java implementations it seems that Justify (https://github.com/leadpony/justify) supports this. Maybe this could offer a potential approach?

**Comment by erosb** [comment]
Hello @costas80 , I released a [new validator library](https://github.com/erosb/json-sKema#installation), it returns line and column information in the validation errors.
