### ISSUE TITLE
extraneous key [channel] is not permitted

### ISSUE THREAD

**Issue by borgogelli** [everit-org/json-schema#371]
As it's written [here](https://json-schema.org/understanding-json-schema/reference/object.html#properties), I have specified the following property in  the schema 

`...
"additionalProperties": false`

The validator returns the following error
`extraneous key [channel] is not permitted`
even if the json data file is correct. 
(I have validate it with another tool)

**Comment by erosb** [comment]
Please create a PR with a failing test as described in the 
 (contribution guide) [https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md]

**Comment by borgogelli** [comment]
I have written a project and a test class, if you want you can see the errors with
```
git clone https://github.com/iubar/json-validator.git
cd json-validator
mvn -f pom_travis.xml test
```
or see them on Travis.ci at https://travis-ci.org/github/iubar/po-test-json-validator

**Comment by erosb** [comment]
It is a problem with your testrunner. At `EveritTest:156` you return the size of the causing exceptions. But AFAICT the `parseWithTheEveritLib()` should never return 0 if a ValidationException was thrown (even if the `getCausingExceptions()` returns a 0-length list, which is normal).

If you look into the logs of your tests, you can see that the library reports the expected errors.

If you still think that the library has a problem, please create a PR with a failing test as described in the contribution guide. As I already requested....

**Comment by borgogelli** [comment]
Thank you @erosb , It's my fault sorry but for me it was somewhat anti-intuitive to have an empty error list in the presence of a validation error.
