### ISSUE TITLE
In complex schemas referring a subschema via relative classpath throws Exception during validation

### ISSUE THREAD

**Issue by Steffengreiner** [everit-org/json-schema#377]
Heya, 

First of all, Thank you for your hard work in creating this library! 

I am struggling with validating a complex parent schema in which a child schema is referred. 

I created a small maven based project to showcase the issue: 
https://github.com/Steffengreiner/Jsondummy

Basically what I'm trying to do is to provide the `Schemaloader` with a `resolutionscope` to the relative path in which Maven stores the schemas dependent on the user machine.  
Since the program in which the validation process takes place will be executed on different computers with and without internet access, providing an external `http:// `based URL is not feasible.

Therefore the resolution suggested here is sadly not applicable: 
https://github.com/everit-org/json-schema/issues/260

However by specifying the classpath in the `SchemaLoader` as outlined in the documentation:
https://github.com/everit-org/json-schema#ref-resolution

Just leads to either an `UncheckedIOException` if "classpath://" is defined explicitly or an `MalformedURLException` if the path to the maven resource directory is provided without the explicit "classpath" statement.  

So my question would be: Does the `resolutionscope` for a relative path based solution need a different input or is that not possible as of now? 

Thank you for your time and help 

Kind regards, 

Steffen

**Comment by TJC** [comment]
I would love to know the answer to this as well. Did you ever figure out a solution?
