### ISSUE TITLE
Does not recognire struct type

### ISSUE THREAD

**Issue by cegladanych** [everit-org/json-schema#379]
During 
While trying to load json schema the exception is thrown. Looks like [struct] type is not supported

InputStream inputStream = new FileInputStream(json);
JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));
Schema schema = SchemaLoader.load(rawSchema);

org.everit.json.schema.SchemaException: #: unknown type: [struct]

Kind Regards

**Comment by erosb** [comment]
Hello, 

there is no `"struct"` keyword in json schema, the list of possible types can be found here: https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.1

I suggest reading the [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/) document before using this library (or any other implementation).
