### ISSUE TITLE
Property named "type" causes exception "expected type is one of JsonArray or String, found: JsonObject"

### ISSUE THREAD

**Issue by rvraaphorst** [everit-org/json-schema#380]
Hi,

Everit version 1.12.1

I'm trying to come up with a schema for this object:

```
{
  "type": "my content type",
  "name": "content name"
}
```

As described on [StackOverflow](https://stackoverflow.com/questions/62936377/everit-validator-jsonschema-property-named-type), the following schema causes the exception:

actionToken.json#/properties/type: expected type is one of JsonArray or String, found: JsonObject

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "model.json",
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "minLength": 1
        },
        "name": {
            "type": "string",
            "minLength": 1
        }
    },
    "additionalProperties": false,
    "required": [
        "type",
        "name"
    ]
}
```

When the "type" property is omitted, or renamed to something else, the validator works fine:

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "model.json",
    "type": "object",
    "properties": {
        "some-type": {       <<-- Only field name changed
            "type": "string",
            "minLength": 1
        },
        "name": {
            "type": "string",
            "minLength": 1
        }
    },
    "additionalProperties": false,
    "required": [
        "some-type",
        "name"
    ]
}
```

**Comment by erosb** [comment]
Hello, I tried to reproduce the issue in 786e04e51247f78a67a4eb619c6b2b9191a70071 but I couldn't. Please share more details about the issue, or create a PR with a failing test as [explained in the contribution guideline](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md).
