### ISSUE TITLE
Unable to refer properties containing "#" sign

### ISSUE THREAD

**Issue by bsanchezb** [everit-org/json-schema#386]
I have a schema containing definitions from [RFC 7515](https://tools.ietf.org/html/rfc7515). It contains a parameter with a name "x5t#S256" which causes the problem when I try to refer it from another place. I have something similar to this code:
```
...
"x5tArray": {
    "type": "array",
    "items": {"$ref": "#/definitions/x5t#S256"},
    "minItems": 1
}
...
```

When I execute SchemaLoader.load(), the following exception is thrown:
```
java.lang.IllegalArgumentException: Illegal character in fragment at index 17: #/definitions/x5t#S256
	at java.base/java.net.URI.create(URI.java:906)
	at java.base/java.net.URI.resolve(URI.java:1089)
	at org.everit.json.schema.loader.internal.ReferenceResolver.resolve(ReferenceResolver.java:48)
	at org.everit.json.schema.loader.internal.ReferenceResolver.resolve(ReferenceResolver.java:26)
	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:134)
        ...
```
The URI class does not expect to get "#" hash sign in the path. 

Currently I bypass the issue, by re-defining the "x5t#S256" parameter directly in my array. But I think it is not the expected behavior, is not it?

Best regards,
Aleksandr.

**Comment by erosb** [comment]
Hello, the json pointers should be in URI-encoded format, so the `#` character should be substituted by `%23` in the `$ref`. I added an example in 853c936b3584de455fb810952531c3e5e332b6c1 .

**Comment by bsanchezb** [comment]
Thank you @erosb for the quick reply!

Indeed, it works.

Regards,
Aleksandr.
