### ISSUE TITLE
Json schema validation : required attributes based on attributes from different object in same json

### ISSUE THREAD

**Issue by MadhuVenkatesh93** [everit-org/json-schema#388]
I have a requirement where i need to define attribute in one object as required based on value of attribute in another object.

e.g> 

      {"if" : {
        "properties" : {
          "Status" : {
            "const" : "CANCELLED"
          }
        },
        "required" : [
          "Status"
        ]
      },
      "then" : {
        "required" : [
          "Reason"
        ]
      }
    }

above condition works. However below e.g doesn't work

      {"if" : {
        "properties" : {
          "#/Details/HasAgreement" : {
            "const" : true
          }
        },
        "required" : [
          "#/Details/HasAgreement"
        ]
      },
      "then" : {
        "required" : [
          "#/Contract/EffectiveDate"
        ]
      }
    }

I'm guessing that the way how I'm referring attributes from different objects in same json is wrong. what is the right way?

Thanks, Madhu

**Comment by erosb** [comment]
Hello, according the the json schema specification, the `"required"` array should contain a list of property names. Reference resolution is not involved at all.
