### ISSUE TITLE
How to add definitions?

### ISSUE THREAD

**Issue by JoshMcCullough** [everit-org/json-schema#396]
Using the fluent API, how would you add top-level definitions? 

For example: https://json-schema.org/understanding-json-schema/structuring.html#reuse

Note -- I started adding this functionality in my own fork but it is not correct or complete: https://github.com/TeslaGov/json-schema/tree/jsm/definition-schemas

**Comment by erosb** [comment]
It isn't explicitly supported by the builder API but you can put it together. I added a minimal example in 060a8e0 .

**Comment by JoshMcCullough** [comment]
I see, thanks.
