### ISSUE TITLE
org.everit.json.schema.ValidationException: #/date: expected type: String, found: Date

### ISSUE THREAD

**Issue by lledo3** [everit-org/json-schema#399]
I'm not sure why I'm getting this error when validating my json against my schema:

Schema:
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "title": "JSON schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "required": [
    "assetid",
    "date",
    "e",
    "bmi",
    "sc",
    "lg",
    "hc"
  ],
  "properties": {
    "assetid": {
      "$id": "#/properties/assetid",
      "description": "An explanation about the purpose of this instance.",
      "title": "The assetid schema",
      "type": "integer"
    },
    "date": {
      "$id": "#/properties/date",
      "description": "An explanation about the purpose of this instance.",
      "title": "The date schema",
      "type": "string"
    },
    "e": {
      "$id": "#/properties/e",
      "description": "An explanation about the purpose of this instance.",
      "title": "The e schema",
      "type": "number"
    },
    "bmi": {
      "$id": "#/properties/bmi",
      "description": "An explanation about the purpose of this instance.",
      "title": "The bmi schema",
      "type": "number"
    },
    "sc": {
      "$id": "#/properties/sc",
      "description": "An explanation about the purpose of this instance.",
      "title": "The sc schema",
      "type": "number"
    },
    "lg": {
      "$id": "#/properties/lg",
      "description": "An explanation about the purpose of this instance.",
      "title": "The lg schema",
      "type": "number"
    },
    "hc": {
      "$id": "#/properties/hc",
      "description": "An explanation about the purpose of this instance.",
      "title": "The hc schema",
      "type": "number"
    }
  },
  "additionalProperties": true
}

And here is a JSOn example:

{
  "assetid": 533,
  "date": "2020-11-17",
  "e": 25.97,
  "bmi": 15.87,
  "sc": -9.73,
  "lg": 0.07,
  "hc": -4.4
}

It's not making any sense to me. I even used an online schema validator and everything worked.

**Comment by erosb** [comment]
Hello, I created a reproducer in 9757387 and it passed (the object validated successfully). Maybe there is a problem with the java code.
