### ISSUE TITLE
maximum field does not work properly with numbers around 1.0E16

### ISSUE THREAD

**Issue by AgustinBettati** [everit-org/json-schema#400]
schema:
`
{   
    "type": "number",
    "maximum": 9999999999999999    
}
`
payload:
`10000000000000000` or `10000000000000001`
This does not return a maximum value exceeded validation. 

**Note:** When the payload is `10000000000000002` the validation is returned correctly.

**Observations**
From debugging the code i found that when calling .doubleValue() in https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/NumberSchemaValidatingVisitor.java#L67 the number is truncated to 1.0E16 as well as the numberSubject value.

**Comment by zgyorffi** [comment]
Thanks for raising the issue.

Here is the explanation. The underlying json parser library parses numbers as either Long or Double:
https://github.com/stleary/JSON-java/blob/5b845f28cfdc26919b1416ec2067da4a0753aeb6/JSONObject.java#L2169
Those types cannot be compared directly so json-schema takes the doubleValue() of every Number types for comparison. However it loses precision at great numbers:
https://howtodoinjava.com/java-examples/correctly-compare-float-double/

A solution might be to check if both numbers are Long and it that case the numbers can be compared directly. But this does not address the issue completely. E.g. comparing `9999999999999999` and `10000000000000000.0` (Long and Double)

In my opinion the desirable would be to compare numbers as BigDecimals. A newer version (20201115) of the library parses numbers with decimal notation as BigDecimal by default so the precision is not lost:
https://github.com/stleary/JSON-java/blob/fdde43cd3bfede55095bdb3dfcac4ce36d99e456/src/main/java/org/json/JSONObject.java#L2107
Using that version and converting the instances of other Number types to BigDecimal before comparison would be a correct solution I think. I tried the newer version and do not see any obstacle to use it. What is your opinion @erosb ?

**Comment by erosb** [comment]
Hello @zgyorffi , many thanks for spending time on analyzing this issue. Please proceed with a PR with the suggested fix. 
I assume the problem won't go away on android (since the android SDK contains an old version of the org.json library).

**Comment by AgustinBettati** [comment]
Thanks for the detailed response! 
Do you have an ETA for the coming release where this fix could be included?

**Comment by zgyorffi** [comment]
I think we could release it in a week.

**Comment by AgustinBettati** [comment]
Thank you very much for the quick fix 👍
