### ISSUE TITLE
Single quotes in array pass validation

### ISSUE THREAD

**Issue by Exscotticus** [everit-org/json-schema#406]
I tried validating JSON against a schema that used single quotes in an array like this...

`['foo', 'bar']`

...when proper JSON would be like this...

`["foo", "bar"]`

The single quotes pass validation. I understand we can implement a custom FormatValidator. But this really seems like something that should be handled by default. Single quotes are not JSON.

**Comment by erosb** [comment]
I agree. The JSON parser itself is implemented in the [JSON-java](https://github.com/stleary/JSON-java) project,not directly in this project. That parser is known to be lenient and to accept invalid JSON (including single quotes, no quotes at all, trailing spaces in objects and arrays, etc). So if you want to validate the lexical correctness of a JSON string then you will need an other project to do that.

**Comment by Exscotticus** [comment]
Thanks for responding. Can you suggest a strict Java JSON validation package?

**Comment by Exscotticus** [comment]
I tested the Gson serializer and it seems to work well.
