### ISSUE TITLE
SchemaException(java.lang.String, java.lang.Exception) called with incorrect argument

### ISSUE THREAD

**Issue by SvaponiAkelius** [everit-org/json-schema#407]
`org.everit.json.schema.SchemaException#SchemaException(java.lang.String, java.lang.Exception)` is called with first argument as message instead of schemaLocation. Example `new SchemaException("failed to parse " + resp, e);`.

See
- com/github/everit-org/json-schema/org.everit.json.schema/1.12.2/org.everit.json.schema-1.12.2-sources.jar!/org/everit/json/schema/loader/JsonPointerEvaluator.java:93
- com/github/everit-org/json-schema/org.everit.json.schema/1.12.2/org.everit.json.schema-1.12.2-sources.jar!/org/everit/json/schema/loader/internal/JSONPointer.java:86

**Comment by erosb** [comment]
Thanks for reporting it, I created #408 with a fix.
