### ISSUE TITLE
DateTimeFormatValidator fails for valid format

### ISSUE THREAD

**Issue by theod0sis** [everit-org/json-schema#410]
I am getting ValidationException because DateTimeFormatValidator is failing to validate a valid format:
org.everit.json.schema.ValidationException: [2021-03-31T09:08:48.150+0000] is not a valid date-time. Expected [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,9}Z]
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties":{
      "date":{
         "type":"string",
         "format":"date-time"
      }
   },
}
```

I checked on https://www.jsonschemavalidator.net/ and is saying that the date is in correct format.

**Comment by erosb** [comment]
JSON Schema draft-04 refers to [RFC 3339](https://tools.ietf.org/html/rfc3339#page-10) which defines the offset as:
```
time-numoffset  = ("+" / "-") time-hour ":" time-minute
```
In your input `+0000` doesn't conform to that, it should be `+00:00`.
