### ISSUE TITLE
Not able to find the latest version on maven central

### ISSUE THREAD

**Issue by anshulsinghchauhan** [everit-org/json-schema#415]
Hi Team,
I am using maven central repo to utilise the library but the latest version is available only through jitpack. Any specific reason Why the latest versions are not available on maven central repo.

**Comment by erosb** [comment]
Hello, if you want to stick to maven central instead of jitpack, you can use these coordinates:

```xml
        <dependency>
            <groupId>com.github.erosb</groupId>
            <artifactId>everit-json-schema</artifactId>
            <version>1.12.2</version>
        </dependency>
```

**Comment by anshulsinghchauhan** [comment]
Thanks for the details will use the same....
