### ISSUE TITLE
Integers and strings are always imported as required

### ISSUE THREAD

**Issue by AalokAhluwalia** [everit-org/json-schema#416]
Hi, I'm using this library to parse json schemas and noticed that strings and integers were always parsed and set to required. Take for example the minimal json schema below: 
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "My schema description",
  "properties": {
    "messageId": {
      "type": "string",
    },
    "sentAt": {
      "type": "integer",
    },
  },
  "required": []
}
```
I import the schema using:
```
val schema = '<the above schema>'
val schemaRoot = SchemaLoader.builder().schemaJson(JSONObject(schema)).build().load().build() as ObjectSchema
schemaRoot.propertySchemas.map{println(it.key + " " +  it.value.location.toString() + " "+ it.value.required() + " " + it.value.type())}
```
Producing:
```
messageId #/properties/messageId true string
sentAt #/properties/sentAt true integer
```
I am using version `1.12.2`. My suggested fix is in the SchemaExtractor.java in the `loadForExplicitType` to remove the explicit required(true) calls chained after building the schema. PR fix will be committed shortly...

**Comment by erosb** [comment]
Something looks wrong here. This doesn't even compile for me. the `propertySchemas` is a  `Map<String, Schema>` , and the value (which is a `Schema` instance) does not have `required()` and `type()` here. Maybe you mix your code together with some other library?

**Comment by AalokAhluwalia** [comment]
Above code is kotlin. There is no required method for schemas, but looks like we defined:
```
fun Schema.required(): Boolean {
    return when (this) {
        is ArraySchema -> this.requiresArray()
        is NumberSchema -> this.requiresInteger()
        is ObjectSchema -> this.requiresObject()
        is StringSchema -> this.requireString()
        else -> false
    }
}
```
Is there any way to parse the result of `SchemaLoader.builder().schemaJson(JSONObject(schema)).build().load().build()` to see if a particular field is required? Looks like requiresString and requiresInteger weren't doing what we expected

**Comment by AalokAhluwalia** [comment]
Looks like Object schemas has: `requiredProperties`. Will be using that instead of checking requiresString, requiresInteger.
