### ISSUE TITLE
Validating against `multipleOf: 0` throws java.lang.ArithmeticException

### ISSUE THREAD

**Issue by arielmirra** [everit-org/json-schema#426]
schema:
`{"type": "number", "multipleOf" : 0}`

payload:
- Any number other than 0 it throws `java.lang.ArithmeticException: Division by zero`
- Zero throws `java.lang.ArithmeticException: Division undefined`

Is this the expected behavior? Or are they corner cases that are not being handled?

Thanks!

**Comment by erosb** [comment]
Hello, according to the [most recent version](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.2.1) of the json schema spec, the `"multipleOf"` value should be stricly greater than 0. So this is an issue with the schema, not the validator. However it would make sense to add a safety net in the schema loader too, to fail early when an incorrect schema is being loaded.
