### ISSUE TITLE
Distribute through maven central also

### ISSUE THREAD

**Issue by mohitpali** [everit-org/json-schema#427]
The dependency is distributed through jitpack, while some enterprise customers do not want to add jitpack as a repository. Would it be possible to distribute it through maven central ?
```
<dependency>
    <groupId>com.github.everit-org.json-schema</groupId>
    <artifactId>org.everit.json.schema</artifactId>
    <version>1.12.2</version>
</dependency>
```

**Comment by erosb** [comment]
It is also distributed with the following coordinates:

```xml

        <dependency>
            <groupId>com.github.erosb</groupId>
            <artifactId>everit-json-schema</artifactId>
            <version>1.12.3</version>
        </dependency>    
```

**Comment by blacktooth** [comment]
@erosb Can your repository be considered official? Does it mirror the community repo and are new versions published timely?

**Comment by erosb** [comment]
Yes, currently the same release script that tags the new version also publishes on maven central with the `com.github.erosb:everit-json-schema` coordinates.
