### ISSUE TITLE
Remove JitPack repo from core POM when uploading to Maven Central

### ISSUE THREAD

**Issue by michael-o** [everit-org/json-schema#430]
Please remove this snippet from the POM at least when uploading to Maven Central:
https://github.com/everit-org/json-schema/blob/5210f30df7a93fe1128fbe720f4835ecc381fd3c/core/pom.xml#L283-L288

It imposes several issues on the developer using your library:
* This is highly [discouraged](https://central.sonatype.org/publish/requirements/#a-complete-example-pom) by Sonatype OSSRH upload requirements.
* JitPack is a very problematic repo: see https://issues.apache.org/jira/browse/WAGON-611
* You impose a repo on a user which might be several problem inside a corporate environment

I was able to build the project (`core` only) from master without JitPack repo and an empty local repo if I use the clone from @erosb and apply the following patch:
```patch
osipovmi@deblndw011x:~/var/Projekte/json-schema/core ((1.13.0) *%)
$ git diff
diff --git a/core/pom.xml b/core/pom.xml
index a4595acc..73fdefd4 100644
--- a/core/pom.xml
+++ b/core/pom.xml
@@ -18,8 +18,8 @@
 -->
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
     <modelVersion>4.0.0</modelVersion>
-    <groupId>org.everit.json</groupId>
-    <artifactId>org.everit.json.schema</artifactId>
+    <groupId>com.github.erosb</groupId>
+    <artifactId>everit-json-schema</artifactId>
     <version>1.13.0</version>
     <packaging>bundle</packaging>
     <properties>
@@ -138,8 +138,8 @@
                 <configuration>
                     <oldVersion>
                         <dependency>
-                            <groupId>com.github.everit-org.json-schema</groupId>
-                            <artifactId>org.everit.json.schema</artifactId>
+                            <groupId>${project.groupId}</groupId>
+                            <artifactId>${project.artifactId}</artifactId>
                             <version>1.12.3</version>
                             <type>jar</type>
                         </dependency>
@@ -279,11 +279,4 @@
             <scope>test</scope>
         </dependency>
     </dependencies>
-
-    <repositories>
-        <repository>
-            <id>jitpack.io</id>
-            <url>https://jitpack.io</url>
-        </repository>
-    </repositories>
 </project>
```

Note: Hunk 2 can be applied immediately to the origin repo.

PS: I am a Maven core developer

**Comment by joshbybee** [comment]
I am also running into this issue in a corporate environment, the jitpack.io download dependency will randomly fail like this during an AzureDevOps pipeline build:

```
Downloading from : https://jitpack.io/com/github/everit-org/json-schema/org.everit.json.schema/1.9.2/org.everit.json.schema-1.9.2.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:22 min
[INFO] Finished at: 2021-09-29T13:19:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mule-custom-api: Could not resolve dependencies for project com.mycompany:mule-mule-custom-api:mule-application:1.0.0-SNAPSHOT: Could not transfer artifact com.github.everit-org.json-schema:org.everit.json.schema:jar:1.9.2 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by michael-o** [comment]
> I am also running into this issue in a corporate environment, the jitpack.io download dependency will randomly fail like this during an AzureDevOps pipeline build:
> 
> ```
> Downloading from : https://jitpack.io/com/github/everit-org/json-schema/org.everit.json.schema/1.9.2/org.everit.json.schema-1.9.2.jar
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  08:22 min
> [INFO] Finished at: 2021-09-29T13:19:51Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project mule-custom-api: Could not resolve dependencies for project com.mycompany:mule-mule-custom-api:mule-application:1.0.0-SNAPSHOT: Could not transfer artifact com.github.everit-org.json-schema:org.everit.json.schema:jar:1.9.2 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> ```

You have  been  hit by https://issues.apache.org/jira/browse/WAGON-611.  ShitPack, not JitPack.

**Comment by erosb** [comment]
Version 1.14.0 should be soon available on maven central without depending on jitpack. Please let me know if there are any further problems with it.

**Comment by michael-o** [comment]
> 
> 
> Version 1.14.0 should be soon available on maven central without depending on jitpack. Please let me know if there are any further problems with it.

Fantastic, thank you!
