### ISSUE TITLE
JSON schema validation fails when there is no internet connection

### ISSUE THREAD

**Issue by mkjdesilva** [everit-org/json-schema#433]
I am getting below error while trying to validate a JSON against a schema
```
 java.io.UncheckedIOException: java.net.UnknownHostException: json-schema.org
  at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:27)
```

The schema has a ref to "$ref": "http://json-schema.org/draft-07/schema#" and this fails at DefaultSchemaClient.java:27 when there is no internet connection.

Is there a way to get around this issue ?

**Comment by erosb** [comment]
Hello, I suggest downloading all external dependencies in advance, and [pre-registering the schema JSON objects in the schema loader config](https://github.com/everit-org/json-schema#registering-schemas-by-uri).

**Comment by Relequestual** [comment]
@erosb You don't include the meta-schemas by default?

**Comment by erosb** [comment]
@Relequestual is there any reason to do that?

**Comment by Relequestual** [comment]
@erosb Yes.
I would expect when a JSON Schema is provided, it's validated against the appropriate meta-schema before being used.
Downloading the meta-schema required each time adds unnecessary overhead (an HTTP request), especially for CI test workflows which are run often.

Besides, we (JSON Schema) make an explict statement that you should not expect to be able to find anything at the dialect URI (The value for `$schema` is the dialect URI).

**Comment by erosb** [comment]
> I would expect when a JSON Schema is provided, it's validated against the appropriate meta-schema before being used.

The library throws informative exceptions in case the schema turns out to be un-processable. This is done programmatically using an internal API and the meta-schema is not used for this purpose (hence, the library doesn't expect to be able to find anything at the dialect URI).

**Comment by Relequestual** [comment]
In which case, fair enough!
I'd expect this to be done in addition to the meta-schema evaluation should it fail.
I would guess using the meta-schema might be a quick first pass.

Having said that, I'm not sure that would be beneficial. I'm not sure my coffee has kicked in yet!
