### ISSUE TITLE
Make  org.everit.json.schema.ReferenceSchema#getReferenceValue() public?

### ISSUE THREAD

**Issue by fmoussallam** [everit-org/json-schema#434]
Hello and thanks for this great product.

I need access to **org.everit.json.schema.ReferenceSchema#getReferenceValue()** while parsing a json schema but that method is not public.

Is there a reason for this?

Is it possible de make it public?

**Comment by erosb** [comment]
I can't see any obstacle, fixed in 7ef48372ea063570261418b27c0b4d1a37eb30be
