### ISSUE TITLE
Uploading 1.12.2 to Maven Central

### ISSUE THREAD

**Issue by tomsfernandez** [everit-org/json-schema#436]
Hi! Is there a way to upload this artifact to Maven Central instead of Jitpack? I saw that there are some versions in Central: https://mvnrepository.com/artifact/org.everit.json/org.everit.json.schema

If there is a way I can help I would be glad to do it.

**Comment by erosb** [comment]
You can find the same artifact on maven central with the
com.github.erosb:everit-json-schema coordinates.
