### ISSUE TITLE
Missing json-schema artifacts in mulesoft's artifatory repo (multiple versions)

### ISSUE THREAD

**Issue by piyushn-stripe** [everit-org/json-schema#437]
Hi,
I was trying to build a project that depends on json-schema and I seem to be hitting errors indicating that the jars for release 1.12.1 are missing. Looking at: https://repository.mulesoft.org/nexus/content/repositories/public/com/github/everit-org/json-schema/org.everit.json.schema/ it looks like there's only: 1.11.1 and 1.9.2 and releases such as: 1.10.0, 1.12.0, 1.12.1, 1.12.2 are missing: https://mvnrepository.com/artifact/com.github.everit-org.json-schema/org.everit.json.schema?repo=mulesoft-public
Is this something that needs to be fixed / artifacts that need to be re-published?

**Comment by erosb** [comment]
You can try the recent versions with the `com.github.erosb:everit-json-schema:1.13.0` coordinates. I'm not aware of the mulesoft repo, that is maintained independently from this project.

**Comment by piyushn-stripe** [comment]
Ah ok, I was under the impression that you folks also published your artifacts there.
