### ISSUE TITLE
Validate if field exists in schema

### ISSUE THREAD

**Issue by v1ctor** [everit-org/json-schema#44]
Hi!
I would like to add new feature to validate if field exists in schema.
```java
Schema schema = SchemaLoader.load(schemaAsJsonObject);
Assert.assertTrue(schema.hasField('rectangle.a'))
```
In first glance I think that I have to validate only propertySchemas recursievly and patternProperties.
Could you please point if there are some corner cases of this solution?

**Comment by v1ctor** [comment]
Hi @erosb You could close this task :)
Also could you please tell me when you will release new version of the library?

**Comment by erosb** [comment]
Hi! After merging your PR I recognized that your ObjectSchema#definesProperty() implementation handles escaping & recursion only for properties, but not for patternProperies and schemaDependencies. I started working on it. With some luck I will finish it tonight.

**Comment by erosb** [comment]
Okey, all looks fine, the new release is [available on GitHub](https://github.com/everit-org/json-schema/releases/tag/1.4.0).
@balazs-zsoldos please deploy version 1.4.0 to maven central , thanks.
