### ISSUE TITLE
Support for Draft 2020-12 or Draft 2019-09

### ISSUE THREAD

**Issue by mejuhi** [everit-org/json-schema#441]
We have a use case where we would like to use the latest Draft version while doing validation on schema,

I have noticed two issues which were opened #329  and #252  for support for Draft 2019-09.
wanted to know if there is any eta on it, and If there are any plans on supporting Draft 2020-12?

**Comment by erosb** [comment]
Hello @mejuhi @kdefives the new validator suppoting draft2020-12 was released last week, please take a look: https://github.com/erosb/json-sKema
