### ISSUE TITLE
SchemaArray's definesProperty implementation

### ISSUE THREAD

**Issue by vokhanhhuy** [everit-org/json-schema#442]
We have a use case of checking whether a property is defined in json schema. My target is to check if the field `type` is defined in the schema, and the field `type` is in an object of an array `adjustments` using [definesProperty](https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/Schema.java#L197-L199) method.

- Here is the Json schema sample: `{
  "type": "object",
  "title": "title",
  "properties": {
    "adjustments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "default": "hello"
          }
        },
        "required": [
          "type"
        ]
      }
    }
  }
}`

After trying some json pointers (i.e `schema.definesProperty("#/adjustments/0/type") == false`) with no luck, I have looked into the code and found that [ArraySchema](https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/ArraySchema.java) has no implementation but inherit with default false for method `definesProperty`. Any chance we can have this one implemented so that we can check for defined properties in an ArraySchema?

Thank you!

**Comment by erosb** [comment]
Hello @vokhanhhuy ,

thank you for raising this issue. The `definesProperty()` method wasn't supported for arrays until now because there are a lot of edge cases to be worked around when implementing it, but today fortunately I could find some time to provide a reasonably solid solution. Please review #443 if it fit your needs. I would like to merge it in a few days.

**Comment by vokhanhhuy** [comment]
Hi @erosb , it was super fast! It's exactly what I am looking for. Will have it tested sometime this week. I am looking forward to the latest release. Really appreciate it.
Thanks!
