### ISSUE TITLE
"Format" attribute works only with type "string".

### ISSUE THREAD

**Issue by marcopiccolo-atos** [everit-org/json-schema#446]
At the moment (v 1.5.1), the "format" attribute, when used for custom validation, does not work with types other than String.
You could easily extend this to other types, by "stringing" the value.

**Comment by nashcrash** [comment]
Better still it would be that the FormatValidator class is implemented with the "Generics"...

**Comment by nashcrash** [comment]
I fork the project for test issue: [https://github.com/nashcrash/json-schema](https://github.com/nashcrash/json-schema)

**Comment by albrechtflo-hg** [comment]
@marcopiccolo-atos According to the [JSON Schema Spec](https://json-schema.org/understanding-json-schema/reference/numeric.html), format is not allowed for numeric types, so why should it be supported? (I am currently investigating an error where a JSON Schema generation library generates `format` for `int` fields, this is why I am asking.)

**Comment by marcopiccolo-atos** [comment]
hi @albrechtflo-hg 
I don't remember the specifics for this issue as it's been more than a year and I didn't write any kind of context for it.
As you stated format is allowed only on String types and numeric fields have different keyword for a rough validation.
I think this issue can be closed.

Thanks for the time
