### ISSUE TITLE
Bump commons-validator to 1.7 for updated IANA TLD list when running format=email validations

### ISSUE THREAD

**Issue by nickgibbon** [everit-org/json-schema#447]
Emails from TLDs added after the release of commons-validator 1.6 (eg .inc which was registered in 2019) are failing format=email validation. Updating commons-validator to 1.7 will allow format=email validation to use the refreshed IANA TLD list (version 2020073100 instead of version 2017020400)

**Comment by erosb** [comment]
Thanks, fixed in ce47e6ef
