### ISSUE TITLE
The library Maven coordinates and availability on https://jitpack.io

### ISSUE THREAD

**Issue by sergeykad** [everit-org/json-schema#449]
The library seems to be unavailable on https://jitpack.io since I started getting errors for it during the build starting yesterday.

I am also confused regarding the naming. The `README.md` file instructs to use `com.github.everit-org.json-schema` while it looks on https://mvnrepository.com/ that the recent versions were published under `com.github.erosb`. Which one is correct?

**Comment by erosb** [comment]
Hello, if you use maven central, then the correct coordinates are `com.github.erosb:everit-json-schema`. I think I will remove the jitpack instructions from the README.

**Comment by sergeykad** [comment]
Thanks. That was an extremely fast answer.

**Comment by erosb** [comment]
@richardtippl-ext90046 no need to add the jitpack repo, maven central is fine. I will remove JitPack from the Maven installation guide.
