### ISSUE TITLE
dependentRequired validation not working?

### ISSUE THREAD

**Issue by tlkthp** [everit-org/json-schema#453]
Example from - https://json-schema.org/understanding-json-schema/reference/conditionals.html#dependentrequired

Since there is no "billing_address" this validation should fail but it doesn't. Is there any config to enable dependentRequired validation? How do I enforce it?

        JSONObject schemaObj = new JSONObject("{\n" +
                "\"$schema\": \"https://json-schema.org/draft/2020-12/schema\"," +
                "  \"type\": \"object\",\n" +
                "\n" +
                "  \"properties\": {\n" +
                "    \"name\": { \"type\": \"string\" },\n" +
                "    \"credit_card\": { \"type\": \"number\" },\n" +
                "    \"billing_address\": { \"type\": \"string\" }\n" +
                "  },\n" +
                "\n" +
                "  \"required\": [\"name\"],\n" +
                "\n" +
                "  \"dependentRequired\": {\n" +
                "    \"credit_card\": [\"billing_address\"]\n" +
                "  }\n" +
                "}");
        Schema schema = SchemaLoader.builder()
                                    .schemaJson(schemaObj)
                                    .draftV7Support()
                                    .build()
                                    .load()
                                    .build();

        schema.validate(new JSONObject("{\n" +
                "  \"name\": \"John Doe\",\n" +
                "  \"credit_card\": 5555555555555555\n" +
                "}"));

**Comment by erosb** [comment]
Hello @tlkthp  , I [released a new validator](https://github.com/erosb/json-sKema#installation) which supports json schema draft2020-12, including the `"dependentRequired"` keyword.
