### ISSUE TITLE
key null: expected type is one of JSONObject, found: JSONArray

### ISSUE THREAD

**Issue by anupriyagb** [everit-org/json-schema#454]
Hi, 
I am using everit 1.5.1 version. I am trying to load schema (draft 07) but it is giving me SchemaException  :  _org.everit.json.schema.SchemaException: key null: expected type is one of JSONObject, found: JSONArray._ 
 
**Please note : This schema shows valid on https://jsonschemalint.com/#!/version/draft-07/markup/json , says -
Message
Schema is valid according to draft-07.**

 Code I am using is : 

_private Schema loadSchema(String schemaType){
        InputStream sourceSchema = this.getClass().getClassLoader().getResourceAsStream(schemaType);
        JSONTokener schemaData = new JSONTokener(sourceSchema);
        JSONObject schemaObj = new JSONObject(schemaData);
        return SchemaLoader.load(schemaObj);
    }_
Schema is attached (adding in text format as json is not supported as an attachment) . 
[Enhanced JSON Schema - Version3.txt](https://github.com/everit-org/json-schema/files/8140655/Enhanced.JSON.Schema.-.Version3.txt)

Please have a look and provide solution asap.

**Comment by erosb** [comment]
Version 1.5.1 is very old. I suggest trying version [1.14.0](https://github.com/everit-org/json-schema#maven-installation). Also, you need to explicitly enable draft-07 support (see [here](https://github.com/everit-org/json-schema#draft-4-draft-6-or-draft-7)).

**Comment by anupriyagb** [comment]
Thank you for the prompt response. 
Version 1.14.0 : I tried its dependency in gradle. But I could not found it. Can you share it's gradle dependency. 

Also, draft07support() method is not available. Please refer : 
![image](https://user-images.githubusercontent.com/53825553/155707362-b47e31f0-02ee-47d0-8eb9-7a86327b3e4e.png)

**Comment by erosb** [comment]
I think you need
```
dependencies {
    implementation 'com.github.erosb:everit-json-schema:1.14.0'
}
```
But I'm not a gradle user myself so I'm not sure.

**Comment by anupriyagb** [comment]
I tried the same, but it is not working. 

Also JFYI, I was using attached schema earlier (it is also draft07 schema) without any explicit draft07support. It was working. 
[oldSchema.txt](https://github.com/everit-org/json-schema/files/8140821/oldSchema.txt)

But now, I have to use the enhanced json schema as attached in the issue desc comment. 

Could you please go through the schemas once.  Else, Please suggest on enabling draft07support.

**Comment by anupriyagb** [comment]
Response awaiting, pls

**Comment by erosb** [comment]
I won't have time to work more on it this week & next week, unfortunately.

**Comment by erosb** [comment]
The validator is correct, your schema is invalid. You can validate your schema against the [meta-schema](https://json-schema.org/draft-07/schema) to get more details.

I assume the "oneOf" keyword is nested under "properties" by accident.
