### ISSUE TITLE
schema validation of string types is too lenient

### ISSUE THREAD

**Issue by whistlingdogg** [everit-org/json-schema#458]
If a schema declares a property of type "string", the validation passes even if the value of the property is not quoted. 

e.g.

{ "requestofsomesort": { "id": thisstringshouldbequoted }}

will validate fine. This causes issues if the json string is subsequently processed both other libraries (faster xml for example). The JSONObject created by a tokener appears to be quite lenient is what it accepts (javadoc supports this). I have seen a reference to a JsonStrictTokener but cannot find any implementation or distributed library. I appreciate that this is probably an issue with JSONObject rather than this schema validation. If the validation supported other json implementations then...

https://json-schema.org/understanding-json-schema/reference/string.html suggests that the above is not legal. Also https://jsonlint.com/

**Comment by erosb** [comment]
Hello, the parsing code is in the [upstream library](https://github.com/stleary/JSON-java), you can file an issue there to have a more strict parsing mode. This library works with the parsed values, so it doesn't know if the original string literal was quoted or not.

**Comment by whistlingdogg** [comment]
agreed that this is not a defect with the validation library
