### ISSUE TITLE
What is registerSchemaByURI used for?

### ISSUE THREAD

**Issue by DominikSarnowski** [everit-org/json-schema#462]
Hello.
Can I use it to register different schemas to validate different objects?
If yes, how to load those different schemas at runtime?

Or is it only to combine schemas that relates one to another?

Can you clarify it to me, please?

**Comment by erosb** [comment]
> Can I use it to register different schemas to validate different objects?

No. This is for referencing other schema documents from your schema. Ie. if you register a schema with an URI like `urn:uuid:57458a26-fc1e-42cb-9636-cff91c5ee807` then you can refer to it in your schema with `"$ref": "urn:uuid:.`urn:uuid:57458a26-fc1e-42cb-9636-cff91c5ee807#/definitions/Subschema`.

If you want to validate different objects against different schemas, then you have to build separate `Schema` instances and pick the appropriate schema for validation based on your object (it is up to you).

**Comment by DominikSarnowski** [comment]
> 

So this $ref is static in another file, or I can dynamically point to it in the app?
@erosb I don't really get how to use those registered schemas programmatically from the code.

**Comment by DominikSarnowski** [comment]
I just wanted to make sure if I correctly understand what is registerSchemaByURI used for.

I wanted to make prototype bean of schemas in SpringBoot application to be able to extract it to common library and based on properties create schemas. But at the same time if the application needs to use more than 1 schema at the same time I would need separate bean for the other needed schemas.

**Comment by erosb** [comment]
I suggest creating your own SchemaFactory class and instantiate it as a
singleton bean. Its client beans can use the factory to create schemas as
per your application needs.
