### ISSUE TITLE
expected type: JSONObject, found: Integer

### ISSUE THREAD

**Issue by vishwanathpatil2193** [everit-org/json-schema#470]
Issue: I want to read any Object from JSON and therefore, i generated this schema. Looks like there is error while validating the input against schema:

The error: expected type: JSONObject, found: Integer

INPUT:
"abc": {
          "attributeName": "somexyz",
          "value": 100
        }

SCHEMA USED:
"output": {
                "type": "object",
                "id": "someID",
                "properties": {
                  "attributeName": {
                    "type": "string"
                  },
                  "value": {
                    "type": "object",
                    "id": "urn:jsonschema:java:lang:Object"
                  }
                }
              }

**Comment by erosb** [comment]
in the input: `"value": 100` - this is an integer

in the schema, `"value"` is set to be an object:
```
"value": {
"type": "object",
"id": "urn:jsonschema:java:lang:Object"
}
```
