### ISSUE TITLE
startTime != endTime

### ISSUE THREAD

**Issue by sunzhongzhengIT** [everit-org/json-schema#471]
How do you know if two values are equal ?
Achieve a goal:
startTime != endTime

**Comment by erosb** [comment]
Hello, this can't be done with json schema.

**Comment by sunzhongzhengIT** [comment]
> 你好，这不能用 json 模式来完成。

Thank you for your reply. I also want to ask,Can I verify that a value is not equal to "XXX“.

**Comment by erosb** [comment]
Yes, you can do that with something like
```
"not": {
  "const": "XXX"
}
```
