### ISSUE TITLE
Want to use EarlyFailingFailureReporter in SchemaLoader more gracefully

### ISSUE THREAD

**Issue by SortfGrowingup** [everit-org/json-schema#472]
Hello  @erosb , I like the everit-json-schema project code style very much. In the process of reading, I learned a lot of new programming ideas.

I current use version is  com.github.erosb:everit-json-schema:1.14.1
When using {SchemaLoader}, I want to use class {EarlyFailingFailureReporter} more elegantly.

See Schema SchemaLoader Validator.

**Comment by erosb** [comment]
Hello, thank you for the kind words. How do you use it currently and what do you mean by using it more elegantly?

**Comment by SortfGrowingup** [comment]
I want the {Schema} generated using {SchemaLoader} can use {EarlyFailingFailureReporter}. 

Or before executing {Schema. validate}, you can select use {CollectingFailureReporter} or {EarlyFailingFailureReporter}.

But at present, the {schema} generated by {SchemaLoader} will always choose to use {CollectingFailureReporter}.

For {Schema} oneself, also the specific implementation of {ValidationFailureReporter} cannot be selected

**Comment by erosb** [comment]
> Or before executing {Schema. validate}, you can select use {CollectingFailureReporter} or {EarlyFailingFailureReporter}.

You can actually do that by using the validator builder:
```
Validator.builder()
                .failEarly()
                .build()
                .performValidation(schema, instance);
```

**Comment by SortfGrowingup** [comment]
Thank you. The problem is solved.
I have always focused on SchemaLoader and Schema, ignoring the independence of Validator.

```jsx

Object input = getType() == 0 ? dataCenter.getJSONObject(getPointer()) : dataCenter.getJSONArray(getPointer());
//getSchema().validate(input);
Validator.builder()
               .failEarly()
               .build()
               .performValidation(getSchema(), input);

```
