### ISSUE TITLE
$ref limitation in complex schemas

### ISSUE THREAD

**Issue by DominikSarnowskiSapiens** [everit-org/json-schema#477]
Hello,
I have a big schema. I splitted it into 5 smaller schemas. Some of them are still huge so I splitted those as well. So I have like 5 levels of schemas.

I see only 2 first levels of schemas are taken into consideration while validating object against the schema of highest level.

Is it possible there is some limitation here or I'm doing something wrong here.

1 level schema: X-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "X",
  "properties": {
"X1": {
"type": "string"
}
"Yies": {
      "type": "array",
      "items": {
            "$ref": "classpath://jsonSchema/Y-schema.json"
          }
    }}}
2 level schema: Y-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
"id": "Y"
  "type": "object",
  "title": "Y",
  "properties": {
"Y1": {
"type": "string"
}
"Zies": {
      "type": "array",
      "items": {
            "$ref": "classpath://jsonSchema/Z-schema.json"
          }
    }}}
3 level schema: Z-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
"id": "Z"
  "type": "object",
  "title": "Z",
  "properties": {
"Z1": {
"type": "string"
"maxLength": 2
}
"Oies": {
      "type": "array",
      "items": {
            "$ref": "classpath://jsonSchema/O-schema.json"
          }
    }}}

I validate it with:

X {
"X1": "dga"
"Yies": [
{
"Y1": "nnn"
"Zies": [
{
"Z1": "ggg"
"Oies":[...]
}
]
}
]

I get validation error while violating X1 and Y1 rules but Z1 looks like is omitted.
Do you have any suggestion?

**Comment by DominikSarnowskiSapiens** [comment]
I found the issue on my side while processing thoses errors.

Everything is woring fine!

**Comment by erosb** [comment]
I'm glad I didn't have to investigate this :)
Please be aware of that this library implements json-schema draft-07 which is not the same as the version covered by the specification documents currently published at json-schema.org (which is version 2020-12).
Also I would appreciate if next time you would [read the contribution guideline](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md) and send an appropriate PR with a test describing your problem. Thanks.
