### ISSUE TITLE
oneOf required is not working correctly

### ISSUE THREAD

**Issue by sriharsha9598** [everit-org/json-schema#480]
Hello Team,
My usecase is to validate that input json contain only one of the properties mentioned in schema. But, when 2 properties are sent in input json, '2 subschemas matched instead of one' exception message is not received. 

`
	
	public static void main(String[] args) {
		Schema schema = SchemaLoader.load(new JSONObject("{\n"
				+ "  \"oneOf\": [\n"
				+ "    {\"required\": [\"union-query\"]},\n"
				+ "    {\"required\": [\"sql-string\"]},\n"
				+ "    {\"required\": [\"rest-url\"]},\n"
				+ "  ],\n"
				+ "  \"type\": \"object\",\n"
				+ "  \"additionalProperties\": false,\n"
				+ "  \"properties\": {\n"
				+ "    \"union-query\": {\"type\": \"string\"},\n"
				+ "    \"rest-url\": {\"type\": \"string\"},\n"
				+ "    \"sql-string\": {\"type\": \"string\"},\n"
				+ "  }\n"
				+ "}"));
		
		JSONObject inputJson = new JSONObject("{\n"
				+ "  \"union-query\": \"xyz\",\n"
				+ "  \"sql-string\": \"xyz\",\n"
				+ "}");
		try {
			 schema.validate(inputJson);
			 System.out.println("JSON is valid");
        } 
		 catch (ValidationException e) {
			 List<String> messages = new ArrayList<String>();
	         collectMessages(e, messages);
	         System.err.println(String.join("\n", messages));
        }
	}
	private static void collectMessages(ValidationException ve, List<String> messages) {
        List<ValidationException> exceptions = ve.getCausingExceptions();
        if (exceptions.isEmpty()) {
            messages.add(ve.getMessage());
        }
        for (ValidationException innerVe : ve.getCausingExceptions()) {
			collectMessages(innerVe, messages);
		}
    }	

`

I have cross verified in some other schema validation libraries and in that both messages : 1. 2 subschemas matched instead of one, 2. required key [rest-url] not found are thrown.

Kindly check and do the needful.

**Comment by erosb** [comment]
Hello @sriharsha9598 I added a reproducer in commit 8ee9f5a2 and the validation fails as expected.
Can you please check he library version you use? The latest is 1.14.1.
If the problem persists then please raise a PR with a unittest reproducing your problem. Thanks.

**Comment by sriharsha9598** [comment]
Hello @erosb 
Thank you for answering.
I understood that the problem is not in validation but the way of collecting messages and I have fixed it from my side.

**Comment by sriharsha9598** [comment]
Hello @erosb ,
`{
  "schemaLocation": "#",
  "pointerToViolation": "#",
  "causingExceptions": [{
    "pointerToViolation": "#",
    "causingExceptions": [{
      "schemaLocation": "#/oneOf/2",
      "pointerToViolation": "#",
      "causingExceptions": [],
      "keyword": "required",
      "message": "required key [rest-url] not found"
    }],
    "keyword": "oneOf",
    "message": "#: 2 subschemas matched instead of one"
  }],
  "keyword": "allOf",
  "message": "#: only 1 subschema matches out of 2"
}`
This is the exception we have got as you shared. But, the actual error and exception message expected in the above case is : "2 subschemas matched instead of one" only but why the other two messages are thrown. 
Is there any reason for throwing multiple messages like this? Why don't the exception be analysed and the exception message be simple and summarised?

**Comment by erosb** [comment]
Hello, your schema gets transformed into the following during the schema loader:
```
{
  "allOf": [
    {
      "oneOf": ...
    },
    {
      "type": "object",
      "additionalProperties": false,
      "properties": ...
    }
  ]
}
```

That is the reason why the `"oneOf"` error is not the top-level error but a cause.
