### ISSUE TITLE
Schema types do not implement equals

### ISSUE THREAD

**Issue by tylersouthwick** [everit-org/json-schema#49]
The different schema types (StringSchema, ArraySchema, etc) do not implement equals() and so cannot be compared to each other.

**Comment by erosb** [comment]
@tylersouthwick I added `toString()` implementations too, the new release is already out on github.
@balazs-zsoldos please release version 1.4.1 on maven central too, thanks.

**Comment by erosb** [comment]
@balazs-zsoldos could you please release version 1.4.1 on maven central?
Thanks.

**Comment by balazs-zsoldos** [comment]
I am not in Hungary at the moment and my network usage is very limited. I will be back home around midnight and release it to maven-central.

**Comment by balazs-zsoldos** [comment]
@erosb @tylersouthwick  Deployed to maven central. Should be available within 10-20 minutes and searchable within 1-2 hours.

**Comment by erosb** [comment]
Great, thank you.
