### ISSUE TITLE
$ref resolution issue when referencing an external schema

### ISSUE THREAD

**Issue by jiyoontbd** [everit-org/json-schema#490]
Hello! Thank you for building and maintaining this library. I really appreciate it! 

I read the bug report guideline but I think that was written for bugs around unexpected ValidationException test cases. I am having trouble with $ref resolution, as many others have, the closest issue to what I'm experiencing being [this one](https://github.com/everit-org/json-schema/issues/438) 

I'm trying to use class path aware client to build my schema like this
```kotlin
val messageSchema = SchemaLoader.builder()
      .schemaClient(SchemaClient.classPathAwareClient())
      .resolutionScope("classpath:/") // All my schemas are in src/main/resource directory
      .draftV7Support()
      .schemaJson(messageSchemaJson)
      .build()
      .load()
      .build()
```

And I have these two schemas,  
`message.schema.json`:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://tbdex.io/message.schema.json",
  "definitions": {
    "MessageMetadata": {
      "type": "object",
      "properties": {
        "from": {
          "$ref": "definitions.json#/definitions/did",
          "description": "The sender's DID"
        },...
```
and `definitions.json`:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://tbdex.io/definitions.json",
  "type": "object",
  "definitions": {
    "did": {
      ...
    }
  }
}
```

Because I used the classpath aware client, i would have expected `"$ref": "definitions.json#/definitions/did"` to work, however it is oddly throwing this error: `java.io.UncheckedIOException: java.io.FileNotFoundException: https://tbdex.io/definitions.json`. 

I cannot figure out why it's trying to find the file in `https://tbdex.io/definitions.json` - that isn't what I passed into `$ref`.

Please let me know if I need to format this issue a different way. 

Thank you! 😊

**Comment by jiyoontbd** [comment]
oddly, this problem just disappears when i remove `"$id": "https://tbdex.io/message.schema.json"` from `message.schema.json`...

**Comment by erosb** [comment]
Hello @jiyoontbd  , AFAIR that is a correct behavior. `$id` sets the lexical context base URL, and the `"$ref"` is resolved against this context base URL. Moreover, resolving a relative URL against an absolute URL isn't just a plain concatenation, so if the base URL is `https://tbdex.io/message.schema.json` and the relative URL is `definitions.json` then indeed the correctly resolved, absolute URL is ``https://tbdex.io/definitions.json`.

If you remove the `$id` then it will be resolved against your initial resolution scope (so the base URL is `classpath:/`). You can think about the resolution scope as a default `$id`.

**Comment by jiyoontbd** [comment]
@erosb thank you for that context! i had better read up more on the relationship between `$ref` and `$id` in json schema. closing this issue now 😊
