### ISSUE TITLE
Support for specs 2020-12 and 2019-09

### ISSUE THREAD

**Issue by ledex** [everit-org/json-schema#502]
Hi all! Is there a plan to include support for the specs `2020-12` and `2019-09`? 
Thanks and cheers!

**Comment by erosb** [comment]
Hello @ledex this repository is in maintenance mode, the active project is https://github.com/erosb/json-sKema/ (which passes about 97% of the draft2020-12 testsuite).

**Comment by ledex** [comment]
Hi @erosb! Thanks for the hint. I will have a look at your new libary.
