### ISSUE TITLE
java.lang.ClassCastException: class org.json.JSONObject$Null cannot be cast to class java.lang.String (org.json.JSONObject$Null is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by mpet** [everit-org/json-schema#510]
Hi,

I am trying to validate using the following code:

`public void validate(JsonNode stndDefinedData) throws ValidationException{   
        // Read values from the JsonNode
        logger.info("Validating stndDefinedData");
       String openApiSpec = schemaReference.getUrl(); // Replace with the actual path to your OpenAPI file
        SwaggerParseResult result = new OpenAPIV3Parser().readLocation(openApiSpec, null, null);

        if (result.getMessages().isEmpty()) {
            OpenAPI openAPI = result.getOpenAPI();

            // Extract the schema from the OpenAPI specification
            ObjectMapper mapper = new ObjectMapper();
            JsonNode schemaNode = mapper.convertValue(
                    openAPI.getComponents().getSchemas().get("NotifyNewAlarm"), JsonNode.class);

            // Convert the schemaNode to JSONObject
            JSONObject jsonSchema = new JSONObject(new JSONTokener(schemaNode.toString()));

            // Load the schema
            Schema schema = SchemaLoader.load(jsonSchema);

            // Sample data to validate
            JSONObject jsonDataObj = new JSONObject(new JSONTokener(stndDefinedData.toString()));

            // Validate the data
            try {
                schema.validate(jsonDataObj);
                System.out.println("Data is valid");
            } catch (org.everit.json.schema.ValidationException e) {
                System.out.println("Data is invalid: " + e.getMessage());
            }
        } else {
            result.getMessages().forEach(System.out::println);
        }
         System.out.println("test");

      

    }`
    
    I can load everything but when I come to this line:

`  Schema schema = SchemaLoader.load(jsonSchema);`
    
    I get the following error message:

java.lang.ClassCastException: class org.json.JSONObject$Null cannot be cast to class java.lang.String (org.json.JSONObject$Null is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.specVersionInSchema(SchemaLoader.java:136)
        at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.build(SchemaLoader.java:147)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:307)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:291)
        at org.onap.dcaegen2.services.sdk.services.external.schema.manager.service.SchemaValidator2.validate(SchemaValidator2.java:69)
        at org.onap.dcaegen2.services.sdk.services.external.schema.manager.service.StndDefinedValidator.validate(StndDefinedValidator.java:79)
        at org.onap.dcaegen2.services.sdk.services.external.schema.manager.service.StndDefinedValidatorTest.shouldValidateStndDefinedFieldsInEventAndReturnFalseWhenInvalidEventIsGiven(StndDefinedValidatorTest.java:75)
        
        This is the openapi schema used:
        
        https://forge.3gpp.org/rep/sa5/MnS/-/blob/Integration_Rel16_SA5_155_YAML/OpenAPI/TS28532_FaultMnS.yaml
        
        Any ideas why I get this exception?
        
        br,

//mike

**Comment by erosb** [comment]
Hello, it seems your schema json goes through plenty of transformations, and somewhere a `"$schema":null` property is added, on which the exception is thrown (which is quite reasonable, since the value of `$schema` must be a string.

Maybe after this line `       JSONObject jsonSchema = new JSONObject(new JSONTokener(schemaNode.toString()));` you could remove it programmatically, like `jsonSchema.remove("$schema");`

**Comment by mpet** [comment]
Hello,
Thanks for reply. Seems like I have null for others too. Do you know the reason for these null?

**Comment by erosb** [comment]
I don't know, since it gets added before the validator library is called.
