### ISSUE TITLE
Is org.everit.json.schema.Validator thread-safe

### ISSUE THREAD

**Issue by jacob2221** [everit-org/json-schema#511]
Hi,

I am planning to create a custom validator with lenient flag turned on for primitives as shown in the code below - 

````
Validator validator = Validator.builder()
	.primitiveValidationStrategry(PrimitiveValidationStrategy.LENIENT)
	.build();
validator.performValidation(schema, input);
````
I am using spring boot. Can I create one instance of this validator and use it across the application or do you recommend creating new Validator each time I need to apply schema validation?

**Comment by erosb** [comment]
Hello, as the README says:

> Note: the Validator class is immutable and thread-safe, so you don't have to create a new one for each validation, it is enough to configure it only once.

On the other hand it is also cheap to create an instance, so if you want, there is no issue with creating a new instance for each validation, and expose only the Schema object as a spring bean.

**Comment by jacob2221** [comment]
Thank you
