### ISSUE TITLE
Validator in lenient mode does not allow numeric value for string field with enum

### ISSUE THREAD

**Issue by jacob2221** [everit-org/json-schema#512]
Hi,
I have below field definition portion in a schema with draft-07- 
````
"packageType": {
                    "type": "string",
                    "description": "Shape of package.",
                    "enum": [
                      "1",
                      "2",
                      "3"
                    ],
                    "example": "1"
                  }
````
I am using validator in leniet mode as shown below 

````
Validator.builder().primitiveValidationStrategy(PrimitiveValidationStrategy.LENIENT).build();
````

When I pass "packageType" : 1 in payload, it complains saying 1 is not supported value. In lenient mode, can I not pass a number for a string field? Is there any other way to make it work apart from defining the enum like below (this works but shows the same number twice in error message)

````
"enum": [
                      "1",1,
                      "2",2,
                      "3",3
                    ]
````

**Comment by erosb** [comment]
I think lenient mode applies only to validating against the `"type"` keyword. So you may also define your `"packageType"` as 

```
{
  "type" "integer",
  "minimum": 1,
  "maximum": 3
}
```
and it should accept `"packageType":"2"` while validating in lenient mode.

**Comment by jacob2221** [comment]
ok thanks. It works!
