### ISSUE TITLE
Expose formatValidator in StringSchema

### ISSUE THREAD

**Issue by ankitshah111** [everit-org/json-schema#53]
I'm trying to use the latest version of your library for a purpose slightly different that that is intended for the library. I see that StringSchema doesnt have a getter for formatValidator. I assume, I can get the required property from its parent requiredProperties getter. However, I cant get access to its formats. Also, NotSchema, doesnt have a getter for the mustNotMatch Schema. It would be helpful to get access to it as well.

**Comment by erosb** [comment]
I've just fixed thisin HEAD.
May I ask what is your slightly different usage scenario?
