### ISSUE TITLE
Validator for Java 6

### ISSUE THREAD

**Issue by rdruilhe** [everit-org/json-schema#7]
Hello,

I'd like to use this json schema validator library for a personal project using an old version of OSGi (which runs on Java 6). I am not familiar with the Function/Consumer classes from Java 8. Could you give me a clue to replace this Function/Consumer pattern to be compliant with Java 6.

Thanks.

**Comment by erosb** [comment]
Hello @rdruilhe ,

at the first glance I doubt if it is possible to make this library work on java6 as-is. There are 2 problems:
* you need a standalone backport of the stream API which compiles to java6. The [streamsupport library](http://sourceforge.net/projects/streamsupport/) seems to be an option though you will need to slightly modify the import statements
* you need to recompile the library to java6 and that seems to be a harder issue. I tried to change pom.xml and set the target version to 1.6 while keeping the source version at 1.8 but javac doesn't compile it. Therefore you would need to backport the source to 1.6 compatible syntax, which is IMO a lot of work (the library makes an extensive use of lambdas and method references).

You may look around streamsupport and [retrolambda](https://github.com/orfjackal/retrolambda) but I think it would make more sense to try to upgrade your runtime to java8. I don't see any reasons why an old java6 codebase wouldn't compile & run on a newer java runtime.

**Comment by rdruilhe** [comment]
Hello @erosb,

Thanks for the answer. I will look at the solutions you mentioned.
