### ISSUE TITLE
Json schema allowing String parameter type receive a string without the double quotation marks.

### ISSUE THREAD

**Issue by xalexslx** [everit-org/json-schema#77]
According to the official spec, a String should be between quotation marks (""). However, when I test against a string parameter without the quotation marks (eg: "key": MyValue instead of "key": "MyValue") it doesn't fail the validation. Also, it only passes the validation if there is a word in the value, but if I send "key": 1234 it will fail with the correct as expected.

![Json String spec](http://www.json.org/string.gif)

There is any configuration to make it fail if the quotation marks are missing from a string value?

**Comment by erosb** [comment]
This seems to be a problem with the underlying JSON parser and not with this project itself. This validation library is supposed to validate the structure of an already parsed JSON, not the bare JSON string itself. So you might file an issue here: https://github.com/stleary/JSON-java
