### ISSUE TITLE
Incorrect error message for arrays

### ISSUE THREAD

**Issue by drawohkam** [everit-org/json-schema#78]
When an array has the "maxItems" set. The validation error message fails to display the maxItems value.

      try
      {
         String schemaString = "{\"type\": \"object\", \"properties\": {\"foo\": {\"type\": \"array\", \"maxItems\": 1, \"items\": {\"type\": \"string\"}}}}";
         Schema schema = SchemaLoader.load(new JSONObject(schemaString));
         schema.validate(new JSONObject("{\"foo\": [\"\", \"\"]}"));
      } catch (ValidationException e)
      {
         System.out.println(e.getMessage());
      }

The error message:

#/foo: expected maximum item count: null, found: 2

The "null" should be 1 in this example.

**Comment by erosb** [comment]
Thanks for reporting it @drawohkam , I fixed it in https://github.com/everit-org/json-schema/commit/1343ab3bb0875a4cae8a0adc0af284ec41e18659 , it will be included in the next release.
