### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by ckmohan** [everit-org/json-schema#79]
Hi,

I am using this repo for json validation, 
but the below test fails if I have required element in the schema definition.
Is there any other option available to validate the schema ?

Note: V1 and V2 are same

JSONObject jsonSchema = new JSONObject(new JSONTokener(
        PeopleSchemaContractValidationTest.class
                .getResourceAsStream("/json/schema/dob-updated_v1.json")));

JSONObject jsonSubject = new JSONObject(new JSONTokener(
        PeopleSchemaContractValidationTest.class
                .getResourceAsStream("/json/schema/dob-updated_v2.json")));

Schema schema = SchemaLoader.load(jsonSchema);
schema.validate(jsonSubject); - Fails

//Schema
{
  "id": "http://json-schema.org/draft-04/schema#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "dateOfBirth": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "dateOfBirth"
  ]
}

Regards
CK

**Comment by erosb** [comment]
Could you please create a PR with a failing test as it is described in the [contributing guidelines](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md) ?
