### ISSUE TITLE
Creative Commons License found in test file issue25/subject-valid.json

### ISSUE THREAD

**Issue by ddevos78** [everit-org/json-schema#80]
My company uses your very good validation library (currently at level 1.3.0) in our product, and upon attempting to upgrade our version to the latest.. our lawyers detected that one of your test files (https://github.com/everit-org/json-schema/tree/master/tests/src/test/resources/org/everit/json/schema/issues/issue25/subject-valid.json) has a Creative Commons License (https://creativecommons.org/licenses/by-sa/3.0) attributed to it.

This license has been deemed problematic by our lawyers due to the 'Sharealike' clauses in the license.

Is it possible for you to delete this test file ?

NOTE: From what I have been told, it would appear that your actually violating the Creative Commons License by having this file in your repository and not formally recognizing the license (but you should defer to your lawyers advice on this topic given I'm personally not an expert in this area).

**Comment by erosb** [comment]
Hello @ddevos78 ,

thank you for your feedback. The issue25/subject-valid.json file belongs to the integration tests which are not the part of the core library. The maven artifact is built from the [core directory](https://github.com/everit-org/json-schema/tree/master/core) , which doesn't include the source file you mentioned. So if you include the library in your product as a maven dependency then this file won't be included in your software.

I hope this satisfies your lawyers. If not, then let me know and I will create a new file reproducing issue 25 .

**Comment by ddevos78** [comment]
Hi @erosb ,

Thanks so much for quick reply. I had already explained to the lawyers that the test file in question is not actually distributed in the final product, unfortunately they tell me that the mere presence of this file (with the Creative Commons License attached) in your repository implies that your product (the final jar) has been produced using that file and hence the Creative Commons License needs to be recognized, which is huge problem for commercial software.

So if you can remove the file and produce a new official release which has no ties to the old test file than I would be extremely grateful.

**Comment by erosb** [comment]
Hello @balazs-zsoldos ,
could you please deploy version [1.5.1](https://github.com/everit-org/json-schema/releases/tag/1.5.1) to maven central? I've just tagged it. Thanks,

**Comment by erosb** [comment]
@ddevos78 in the meanwhile you can start using version `1.5.1` throught [JitPack](http://jitpack.io), by adding the followings to your `pom.xml`

```
<dependencies>
        <dependency>
            <groupId>com.github.everit-org.json-schema</groupId>
            <artifactId>org.everit.json.schema</artifactId>
            <version>1.5.1</version>
        </dependency>
    </dependencies>
    
    <repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

**Comment by balazs-zsoldos** [comment]
@erosb Sorry for the delay.  I will deploy it in this evening.

**Comment by balazs-zsoldos** [comment]
Release command executed. Should be available on maven-central within 1-2 hours.

**Comment by erosb** [comment]
Great, thank you.
