### ISSUE TITLE
Error : key null : expected type is one of JSONObject, found Integer 

### ISSUE THREAD

**Issue by MariamNers** [everit-org/json-schema#82]
Hi,
I understand this must be a very straightforward error but I am not able to debug it.. I am getting the above error when I load my schema as per your instructions, however I do not have an Integer in my schema, so I dont even know where to start debugging this... Apologies if this is a stupid question.

```
{
"title": "PS",
"description" : "smth",
"type" : "object",
"properties":{
 "PD":{
"description" : "smth",
"type" : "array",
"items" :{
"anyOf": [
{
"type": "string"
},
{
"type":"boolean"
}
]
},
"minimum" : 0
},
 "PD2":{
"description" : "smth",
"type" : "array",
"items" :{
"anyOf": [
{
"type": "string"
},
{
"type":"boolean"
},
]
},
"minimum" : 1
},
"currentUser": {
"description" : "smt",
"type" : "string",
"minimum" :1 
}
}
}
```

**Comment by erosb** [comment]
Hello, would you please validate your schema against the [meta-schema](http://json-schema.org/schema) ?

**Comment by MariamNers** [comment]
Hi, thanks for quick response. I did , and I can't see anything wrong unless you are hinting that there is something wrong in my schema?

**Comment by erosb** [comment]
I can see 2 suspisious things in your schema:
 * you use the key `"minimum"` in array schema definitions. It should be `"minItems"` to take effect
 * you also use the key `"minimum"` for the string schema (`"currentUser"`). It should be `"minLength"`.

But I don't know if these problems are related to the exception.

**Comment by erosb** [comment]
@MariamNers I've just tried out your schema with version `1.5.1` of the library and the schema is loaded successfully, so I couldn't reproduce the problem.

Please create a pull request with a reproduction testcase as it is described in the [contributing guidelines](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md). Thanks.

**Comment by MariamNers** [comment]
@erosb Actually solved the issue... It was a combination of dashes and undescores that the schema didn't like + missed a bracket as well... Thanks for your help anyway!
