### ISSUE TITLE
No api to create schema unless use web html to create

### ISSUE THREAD

**Issue by tigerge000** [everit-org/json-schema#83]
as a tester,I get the source json,I wanted take it to generate schemaJson,but now only use the web to generate,it's too lose time;

**Comment by erosb** [comment]
Hello @tigerge000 , I'm not sure if I understand properly what your request is. This project doesn't have any web interfaces. Also, there are 2 ways for programmatically creating schemas:
 * first, you can construct a `JSONObject` instance from Java code and pass that to the `SchemaLoader.load()` call
 * second, the `Schema` subclasses have appropriate builders for generating schemas, although this isn't properly documented. You can find an example here though: http://stackoverflow.com/questions/38449968/generate-json-schema-manally-using-java-codegson-without-any-pojo/38478478#38478478
