### ISSUE TITLE
Validation ignores characters in the end of the file

### ISSUE THREAD

**Issue by pgeadas** [everit-org/json-schema#84]
Hi.

I found an interesting behavior with the validation of a schema, causing some unwanted results.
Is the validation ignoring extra characters at the end of the file? 

I have a correct schema, but appended extra invalid chars after at the end of the file, and the validation does not detect them.

Can some one clarify?

Thanks.

**Comment by erosb** [comment]
Hello Pedro, this schema library uses the org.json library (
https://github.com/stleary/JSON-Java ) for parsing the raw json content.
Would you please open an issue at that project?

Thank you,
