### ISSUE TITLE
Causing exceptions list is empty

### ISSUE THREAD

**Issue by Sudesh1989** [everit-org/json-schema#89]
Hi, getCausingExceptions() method in the ValidationException class is returning an Empty List for a single schema violation. It returns a valid list for multiple schema violations.

**Comment by erosb** [comment]
Hello @Sudesh1989 that is right. The causes form a tree structure. If there is only a single validation then this tree has only a single node, represented by the `ValidationException` being thrown, therefore it doesn't have any additional causes.
