### ISSUE TITLE
default value support?

### ISSUE THREAD

**Issue by mrwilby** [everit-org/json-schema#91]
We're exploring the use of this framework for programmatic schema generation, i.e. generating schemas using the builder/fluent API exposed as part of this library.

Does the library support default property values? I couldn't seem to find this but I may be overlooking it.

Thanks!

**Comment by erosb** [comment]
Hello @mrwilby ,

currently the library doesn't support the `"default"` keyword. Although it is the part of the specification, a lot of implementations don't support it, and I personally didn't find it a good idea to mix validation of the input with modification (populating with defaults).

Anyway, we can keep this issue open, as a feature request.

**Comment by slinkydeveloper** [comment]
Hi! I need it too, maybe if you add this feature and enable it with a flag?

**Comment by erosb** [comment]
Hello @mrwilby , default values are now supported in version 1.7.0.

**Comment by ganpa** [comment]
@erosb the schema allows default values to be invalid. Any reason for this ? Or do you plan to support validations for default values in the future ?

**Comment by erosb** [comment]
Hello @ganpa , the schema allows default values to be invalid because this is what the JSON Scema specification says.

Citing [section 10.2](http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.2):

> This keyword can be used to supply a default JSON value associated with a particular schema. It is RECOMMENDED that a default value be valid against the associated schema.

**Comment by ganpa** [comment]
Yes. It says it is recommended and not must. But it would be great if the library validates default values too.
