### ISSUE TITLE
Why 2 test folders

### ISSUE THREAD

**Issue by DavidThi808** [everit-org/json-schema#92]
Hi all;

Why are there 2 sections for unit tests? json-schema-master\test and json-schema-master\core\src\test both have a ton of unit tests in them. Why the split?

thanks - dave

**Comment by erosb** [comment]
Hello David,

the top-level (`json-schema-master/test/`) directory contains integration tests, while the `json-schema-master/core/src/test/` contains the lower-level unittests.

By integration tests I mean 2 kinds of tests:
 * the [official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) for json schema is copied here, this is a language-independent package of testcases, and it is executed by the parameterized `TestSuiteTest` and `V6TestSuiteTest` classes.
 * the rest of the directories are mostly reproduction tests for the issues reported on GitHub.

These integration tests handle the library as a black-box, they test it externally, so they don't separate the schema loading process and the validation.

On the other hand, unittests are lower level, eg. one test can test if the proper `Schema` instance is built from a given schema json document, and an other test can verify if a constructed Schema instance performs the validation properly, but unittests generally don't test these 2 things at once (with a few exceptions).

**Comment by DavidThi808** [comment]
thank you
