### ISSUE TITLE
Issue in schemaLoader

### ISSUE THREAD

**Issue by eakarsu** [everit-org/json-schema#99]
I used this schema. But SchemaLoader.load returns empty schema. What is wrong with this json schema?

{
	"schema": {
					"$ref": "#/definitions/response"
			},

    "definitions":{
           "response":{
           }
    }
}

**Comment by erosb** [comment]
> What is wrong with this json schema?

2 things:
 - the top-level `"schema"` key is unnecessary. `"schema"` is not a keyword of JSON Schema
 - even after removing the `"schema"` key and putting the `"$ref"` to the top-level, the `"#/definitions/response"` reference points to an empty schema.

In case you are in the progress of learning json schema, I advise you to practice and experiment using an application like this: http://www.jsonschemavalidator.net/

**Comment by eakarsu** [comment]
But I did this with another json validator ajv : https://github.com/epoberezkin/ajv
It worked. 

What I do is just converting what i did with ajv to java based solution.

**Comment by erosb** [comment]
Ajv is known to support non-standard and experimental features, based on the opinion and preferences of the developers.
